	db 0 ; no more evolutions
	db 0, THUNDERPUNCH
	db 1, THUNDERPUNCH
	db 1, ZAP_CANNON
	db 1, MAGNETIC_FLUX
	db 1, ION_DELUGE
	db 1, DRAGON_PULSE
	db 1, FIRE_PUNCH
	db 1, TACKLE
	db 1, GROWL
	db 1, THUNDER_WAVE
	db 1, THUNDERSHOCK
	db 4, THUNDER_WAVE
	db 8, THUNDERSHOCK
	db 11, COTTON_SPORE
	db 16, CHARGE
	db 20, TAKE_DOWN
	db 25, ELECTRO_BALL
	db 29, CONFUSE_RAY
	db 35, POWER_GEM
	db 40, DISCHARGE
	db 46, COTTON_GUARD
	db 51, SIGNAL_BEAM
	db 57, LIGHT_SCREEN
	db 62, THUNDER
	db 65, DRAGON_PULSE
	db 0 ; no more level-up moves