EeveeEvosAttacks:
	db EVOLVE_ITEM, WATER_STONE, VAPOREON
	db EVOLVE_ITEM, FIRE_STONE, FLAREON
	db EVOLVE_ITEM, THUNDERSTONE, JOLTEON
	db EVOLVE_MAPGROUP
	map LAUREL_FOREST_MAIN
	map LAUREL_FOREST_BEACH
	map LAUREL_FOREST_POKEMON_ONLY
	map CASTRO_FOREST
	map HAUNTED_FOREST
	map ILEX_FOREST
	db -1, LEAFEON
	db EVOLVE_MAPGROUP
	map ROUTE_70
	map ROUTE_71
	map CLATHRITE_B1F
	map CLATHRITE_B2F
	map CLATHRITE_1F
	map CLATHRITE_KYOGRE
	map ROUTE_84
	map CAPER_CITY
	db -1, GLACEON
	db EVOLVE_SYLVEON, SYLVEON
	db EVOLVE_HAPPINESS, TR_MORNDAY, ESPEON
	db EVOLVE_HAPPINESS, TR_NITE, UMBREON
	db 0 ; no more evolutions
	db 1, TACKLE
	db 4, TAIL_WHIP
	db 7, SING
	db 10, SAND_ATTACK
	db 13, QUICK_ATTACK
	db 16, GROWTH
	db 19, BATON_PASS
	db 22, BITE
	db 25, SWIFT
	db 28, ENDURE
	db 28, FLAIL
	db 31, VAPORIZE
	db 34, TAKE_DOWN
	db 37, HEAL_BELL
	db 40, CHARM
	db 43, IRON_TAIL
	db 46, DOUBLE_EDGE
	db 49, METALLURGY
	db 0 ; no more level-up moves
