TangelaEvosAttacks:
	db EVOLVE_MOVE, ANCIENTPOWER, TANGROWTH
TangelaMoves:
	db 0 ; no more evolutions
	db 1, WRAP
	db 4, POISONPOWDER
	db 7, VINE_WHIP
	db 10, GROWTH
	db 14, ABSORB
	db 18, PAIN_SPLIT
	db 22, MEGA_DRAIN
	db 25, CONFUSION
	db 28, ANCIENTPOWER
	db 31, STUN_SPORE
	db 33, ANCIENTPOWER
	db 34, SPRING_BUDS
	db 37, MORNING_SUN
	db 40, LEECH_SEED
	db 43, SLEEP_POWDER
	db 46, GIGA_DRAIN
	db 49, SYNTHESIS
	db 52, NATURE_POWER
	db 56, AMNESIA
	db 0 ; no more level-up moves
