	db 0 ; no more evolutions
	db 0, SLASH
	db 1, SLASH
	db 1, NIGHT_SLASH
	db 1, GROWL
	db 1, DISARMING_VOICE
	db 1, HYPNOSIS
	db 1, DRAINING_KISS
	db 1, IMPRISON
	db 1, PSYBEAM
	db 1, LIFE_DEW
	db 1, CHARM
	db 1, CALM_MIND
	db 1, PSYCHIC
	db 1, DREAM_EATER
	db 1, FUTURE_SIGHT
	db 1, LEER
	db 1, FURY_CUTTER
	db 1, DOUBLE_TEAM
	db 1, CONFUSION
	db 9, HELPING_HAND
	db 12, FEINT
	db 15, TELEPORT
	db 18, AERIAL_ACE
	db 23, FALSE_SWIPE
	db 28, PROTECT
	db 35, SWORDS_DANCE
	db 42, PSYCHO_CUT
	db 49, HEAL_PULSE
	db 56, QUICK_GUARD
	db 56, WIDE_GUARD
	db 63, CLOSE_COMBAT
	db 0 ; no more level-up moves