	db 0 ; no more evolutions
	db 1, RECYCLE
	db 1, COVET
	db 1, STOCKPILE
	db 1, SWALLOW
	db 1, SCREECH
	db 1, FLING
	db 1, METRONOME
	db 1, FLAIL
	db 1, LAST_RESORT
	db 1, LICK
	db 1, TACKLE
	db 1, DEFENSE_CURL
	db 1, BLOCK
	db 12, YAWN
	db 16, BITE
	db 20, REST
	db 20, SNORE
	db 20, SLEEP_TALK
	db 24, CRUNCH
	db 28, BODY_SLAM
	db 32, HEAVY_SLAM
	db 36, AMNESIA
	db 40, HIGH_HORSEPOWER
	db 44, HAMMER_ARM
	db 48, BELLY_DRUM
	db 52, BELCH
	db 56, GIGA_IMPACT
	db 0 ; no more level-up moves