	db EVOLVE_ITEM, THUNDERSTONE, JOLTEON
	db EVOLVE_ITEM, WATER_STONE, VAPOREON
	db EVOLVE_ITEM, FIRE_STONE, FLAREON
	db EVOLVE_HAPPINESS, TR_MORNDAY, ESPEON
	db EVOLVE_HAPPINESS, TR_NITE, UMBREON
	db EVOLVE_ITEM, ICE_STONE, GLACEON
	db EVOLVE_ITEM, LEAF_STONE, LEAFEON
	db EVOLVE_ITEM, SHINY_STONE, SYLVEON
	db 0 ; no more evolutions
	db 1, COVET
	db 1, HELPING_HAND
	db 1, TACKLE
	db 1, GROWL
	db 1, TAIL_WHIP
	db 5, SAND_ATTACK
	db 10, QUICK_ATTACK
	db 15, BABY_DOLL_EYES
	db 20, SWIFT
	db 25, BITE
	db 30, COPYCAT
	db 35, BATON_PASS
	db 40, TAKE_DOWN
	db 45, CHARM
	db 50, DOUBLE_EDGE
	db 55, LAST_RESORT
	db 0 ; no more level-up moves