	db 0 ; no more evolutions
	db 0, MIRROR_SHOT
	db 0, AUTOTOMIZE
	db 1, MIRROR_SHOT
	db 1, AUTOTOMIZE
	db 1, HEAVY_SLAM
	db 1, ZAP_CANNON
	db 1, MAGNET_RISE
	db 1, TOXIC_SPIKES
	db 1, TACKLE
	db 1, PROTECT
	db 1, SELFDESTRUCT
	db 1, BUG_BITE
	db 6, SELFDESTRUCT
	db 9, BUG_BITE
	db 12, TAKE_DOWN
	db 17, RAPID_SPIN
	db 20, BIDE
	db 23, NATURAL_GIFT
	db 28, SPIKES
	db 32, PAYBACK
	db 36, EXPLOSION
	db 42, IRON_DEFENSE
	db 46, GYRO_BALL
	db 50, DOUBLE_EDGE
	db 56, MAGNET_RISE
	db 60, ZAP_CANNON
	db 64, HEAVY_SLAM
	db 0 ; no more level-up moves