	db 0 ; no more evolutions
	db 0, PETAL_DANCE
	db 1, PETAL_DANCE
	db 1, PETAL_BLIZZARD
	db 1, TACKLE
	db 1, GROWL
	db 1, RAZOR_LEAF
	db 1, POISONPOWDER
	db 6, RAZOR_LEAF
	db 9, POISONPOWDER
	db 12, SYNTHESIS
	db 18, REFLECT
	db 22, MAGICAL_LEAF
	db 26, NATURAL_GIFT
	db 34, SWEET_SCENT
	db 40, LIGHT_SCREEN
	db 46, BODY_SLAM
	db 54, SAFEGUARD
	db 60, AROMATHERAPY
	db 66, SOLARBEAM
	db 70, PETAL_BLIZZARD
	db 0 ; no more level-up moves