	db ABSOL ; 359

	db  65,  130,  60,  75,  75,  60
  ;  hp  atk  def  spd sat sdf

	db DARK, DARK ; type
	db 30 ; catch rate
	db 163 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 25 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/absol/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_SLOW ; growth rate
	dn EGG_FIELD, EGG_FIELD ; egg groups

	; tm/hm learnset
	tmhm X_SCISSOR, FOUL_PLAY, DARK_PULSE, THROAT_CHOP, KNOCK_OFF, BRUTAL_SWING, THIEF, SNARL, PAYBACK, SNATCH, TAUNT, TORMENT, THUNDER, THUNDERBOLT, SHOCK_WAVE, CHARGE_BEAM, THUNDER_WAVE, SUPERPOWER, ROCK_SMASH, FIRE_BLAST, FLAMETHROWER, SUNNY_DAY, WILL_O_WISP, BOUNCE, AERIAL_ACE, SHADOW_BALL, SHADOW_CLAW, SPITE, BLIZZARD, ICE_BEAM, ICY_WIND, HAIL, GIGA_IMPACT, HYPER_BEAM, STRENGTH, FACADE, HIDDEN_POWER, ROUND, CUT, SNORE, ECHOED_VOICE, FALSE_SWIPE, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, LASER_FOCUS, PROTECT, PSYCH_UP, SLEEP_TALK, SUBSTITUTE, SWAGGER, SWORDS_DANCE, TOXIC, DREAM_EATER, ZEN_HEADBUTT, CALM_MIND, MAGIC_COAT, REST, ROLE_PLAY, STONE_EDGE, ROCK_SLIDE, ROCK_TOMB, SANDSTORM, IRON_TAIL, WATER_PULSE, RAIN_DANCE, ENDURE, BODY_SLAM, FOCUS_ENERGY, SWIFT, ASSURANCE, BATON_PASS, AIR_SLASH, RETALIATE, FUTURE_SIGHT, PSYCHO_CUT, PLAY_ROUGH, MEGAHORN, CLOSE_COMBAT, HEX
	; end