	db ACCELGOR ; 617

	db  80,  70,  40,  145,  100,  60
  ;  hp  atk  def  spd sat sdf

	db BUG, BUG ; type
	db 75 ; catch rate
	db 173 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 15 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/accelgor/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_BUG, EGG_BUG ; egg groups

	; tm/hm learnset
	tmhm LEECH_LIFE, SIGNAL_BEAM, U_TURN, BUG_BITE, STRUGGLE_BUG, INFESTATION, KNOCK_OFF, FOCUS_BLAST, DRAIN_PUNCH, ENERGY_BALL, GIGA_DRAIN, GIGA_IMPACT, HYPER_BEAM, FACADE, HIDDEN_POWER, ROUND, SNORE, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, LASER_FOCUS, PROTECT, SLEEP_TALK, SUBSTITUTE, SWAGGER, SLUDGE_BOMB, VENOSHOCK, GASTRO_ACID, TOXIC, REST, SANDSTORM, RAIN_DANCE, ENDURE, BODY_SLAM, SWIFT, MUD_SHOT, AGILITY, REVERSAL, BATON_PASS, GUARD_SWAP, POWER_SWAP, BUG_BUZZ, SKITTER_SMACK, SPIKES, ENCORE, VENOM_DRENCH, TOXIC_SPIKES
	; end