	db AERODACTYL ; 142

	db  80,  105,  65,  130,  60,  75
  ;  hp  atk  def  spd sat sdf

	db ROCK, FLYING ; type
	db 45 ; catch rate
	db 180 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F12_5 ; gender ratio
	db 100 ; unknown 1
	db 35 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/aerodactyl/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_SLOW ; growth rate
	dn EGG_FLYING, EGG_FLYING ; egg groups

	; tm/hm learnset
	tmhm BRUTAL_SWING, THIEF, PAYBACK, TAUNT, TORMENT, DRAGON_PULSE, DRAGON_CLAW, ROCK_SMASH, FIRE_BLAST, HEAT_WAVE, FLAMETHROWER, SUNNY_DAY, SKY_ATTACK, FLY, AERIAL_ACE, SKY_DROP, DEFOG, ROOST, TAILWIND, EARTHQUAKE, EARTH_POWER, BULLDOZE, GIGA_IMPACT, HYPER_BEAM, STRENGTH, FACADE, HIDDEN_POWER, ROUND, SNORE, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, LASER_FOCUS, PROTECT, ROAR, SLEEP_TALK, SUBSTITUTE, SWAGGER, TOXIC, REFLECT, REST, STONE_EDGE, ROCK_SLIDE, ROCK_TOMB, SMACK_DOWN, ROCK_POLISH, SANDSTORM, STEALTH_ROCK, IRON_TAIL, IRON_HEAD, STEEL_WING, AQUA_TAIL, RAIN_DANCE, ENDURE, SWIFT, ASSURANCE, SCARY_FACE, AGILITY, FIRE_FANG, CRUNCH, THUNDER_FANG, ICE_FANG, PSYCHIC_FANGS, DUAL_WINGBEAT, HURRICANE, METEOR_BEAM, ROCK_BLAST, DRAGON_DANCE
	; end