	db ARBOK ; 24

	db  60,  95,  69,  80,  65,  79
  ;  hp  atk  def  spd sat sdf

	db POISON, POISON ; type
	db 90 ; catch rate
	db 157 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/arbok/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_FIELD, EGG_DRAGON ; egg groups

	; tm/hm learnset
	tmhm INFESTATION, DARK_PULSE, THROAT_CHOP, BRUTAL_SWING, THIEF, PAYBACK, SNATCH, TORMENT, DRAGON_TAIL, SUNNY_DAY, SPITE, SEED_BOMB, GIGA_DRAIN, EARTHQUAKE, STOMPING_TANTRUM, BULLDOZE, GIGA_IMPACT, HYPER_BEAM, STRENGTH, FACADE, HIDDEN_POWER, ROUND, SNORE, BIND, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, PROTECT, SLEEP_TALK, SUBSTITUTE, SWAGGER, SLUDGE_WAVE, SLUDGE_BOMB, POISON_JAB, VENOSHOCK, GASTRO_ACID, TOXIC, REST, ROCK_SLIDE, ROCK_TOMB, IRON_TAIL, AQUA_TAIL, RAIN_DANCE, ENDURE, BODY_SLAM, DIG
	; end