	db ARCANINE ; 59

	db  90,  110,  80,  95,  100,  80
  ;  hp  atk  def  spd sat sdf

	db FIRE, FIRE ; type
	db 75 ; catch rate
	db 194 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F25 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/arcanine/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_SLOW ; growth rate
	dn EGG_FIELD, EGG_FIELD ; egg groups

	; tm/hm learnset
	tmhm THIEF, SNARL, OUTRAGE, DRAGON_PULSE, WILD_CHARGE, SUPERPOWER, ROCK_SMASH, OVERHEAT, FIRE_BLAST, HEAT_WAVE, FLAMETHROWER, FLAME_CHARGE, SUNNY_DAY, WILL_O_WISP, AERIAL_ACE, SOLAR_BEAM, BULLDOZE, GIGA_IMPACT, HYPER_BEAM, HYPER_VOICE, STRENGTH, FACADE, COVET, HIDDEN_POWER, ROUND, SNORE, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, HELPING_HAND, LASER_FOCUS, PROTECT, ROAR, SAFEGUARD, SLEEP_TALK, SUBSTITUTE, SWAGGER, TOXIC, REFLECT, REST, IRON_TAIL, IRON_HEAD, ENDURE, BODY_SLAM, SWIFT, SCARY_FACE, AGILITY, REVERSAL, FIRE_FANG, FLARE_BLITZ, SCORCHING_SANDS, FIRE_SPIN, CRUNCH, DIG, THUNDER_FANG, PSYCHIC_FANGS, RETALIATE, PLAY_ROUGH, CLOSE_COMBAT
	; end