	db ARCEUS ; 493

	db  120,  120,  120,  120,  120,  120
  ;  hp  atk  def  spd sat sdf

	db NORMAL, NORMAL ; type
	db 3 ; catch rate
	db 324 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_UNKNOWN ; gender ratio
	db 100 ; unknown 1
	db 120 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/arceus/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_SLOW ; growth rate
	dn EGG_NONE, EGG_NONE ; egg groups

	; tm/hm learnset
	tmhm X_SCISSOR, SIGNAL_BEAM, DARK_PULSE, SNARL, PAYBACK, QUASH, DRACO_METEOR, OUTRAGE, DRAGON_PULSE, DRAGON_CLAW, THUNDER, THUNDERBOLT, SHOCK_WAVE, CHARGE_BEAM, THUNDER_WAVE, FOCUS_BLAST, BRICK_BREAK, ROCK_SMASH, OVERHEAT, FIRE_BLAST, HEAT_WAVE, FLAMETHROWER, SUNNY_DAY, WILL_O_WISP, FLY, AERIAL_ACE, DEFOG, TAILWIND, SHADOW_BALL, SHADOW_CLAW, SOLAR_BEAM, ENERGY_BALL, GIGA_DRAIN, GRASS_KNOT, EARTHQUAKE, EARTH_POWER, BULLDOZE, BLIZZARD, ICE_BEAM, ICY_WIND, HAIL, GIGA_IMPACT, HYPER_BEAM, LAST_RESORT, HYPER_VOICE, STRENGTH, FACADE, HIDDEN_POWER, ROUND, CUT, SNORE, ECHOED_VOICE, FRUSTRATION, RETURN, CONFIDE, DOUBLE_TEAM, LASER_FOCUS, PROTECT, PSYCH_UP, RECYCLE, ROAR, SAFEGUARD, SLEEP_TALK, SUBSTITUTE, SWAGGER, SWORDS_DANCE, WORK_UP, SLUDGE_BOMB, POISON_JAB, TOXIC, DREAM_EATER, PSYCHIC, PSYSHOCK, ZEN_HEADBUTT, CALM_MIND, GRAVITY, LIGHT_SCREEN, MAGIC_COAT, REFLECT, REST, TELEKINESIS, TRICK, TRICK_ROOM, STONE_EDGE, ROCK_SLIDE, ROCK_TOMB, SANDSTORM, STEALTH_ROCK, IRON_TAIL, FLASH_CANNON, IRON_HEAD, IRON_DEFENSE, AQUA_TAIL, SURF, LIQUIDATION, DIVE, WATERFALL, WATER_PULSE, RAIN_DANCE, ENDURE, STEEL_BEAM, BULLET_SEED, WHIRLPOOL, RETALIATE, BRINE, AVALANCHE
	; end