	db ARTICUNO ; 144

	db  90,  85,  100,  85,  95,  125
  ;  hp  atk  def  spd sat sdf

	db ICE, FLYING ; type
	db 3 ; catch rate
	db 261 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_UNKNOWN ; gender ratio
	db 100 ; unknown 1
	db 80 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/articuno/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_SLOW ; growth rate
	dn EGG_NONE, EGG_NONE ; egg groups

	; tm/hm learnset
	tmhm SIGNAL_BEAM, U_TURN, ROCK_SMASH, SUNNY_DAY, SKY_ATTACK, FLY, AERIAL_ACE, SKY_DROP, DEFOG, ROOST, TAILWIND, BLIZZARD, ICE_BEAM, FROST_BREATH, ICY_WIND, AURORA_VEIL, HAIL, GIGA_IMPACT, HYPER_BEAM, FACADE, HIDDEN_POWER, ROUND, SNORE, FRUSTRATION, RETURN, CONFIDE, DOUBLE_TEAM, LASER_FOCUS, PROTECT, ROAR, SLEEP_TALK, SUBSTITUTE, SWAGGER, TOXIC, REFLECT, REST, SANDSTORM, STEEL_WING, WATER_PULSE, RAIN_DANCE, ENDURE, SWIFT, AGILITY, WEATHER_BALL, ICICLE_SPEAR, AIR_SLASH, DUAL_WINGBEAT, BRAVE_BIRD, HURRICANE, AVALANCHE, TRIPLE_AXEL
	; end