	db AVALUGG ; 713

	db  95,  117,  184,  28,  44,  46
  ;  hp  atk  def  spd sat sdf

	db ICE, ICE ; type
	db 255 ; catch rate
	db 180 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/avalugg/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_MONSTER, EGG_MINERAL ; egg groups

	; tm/hm learnset
	tmhm SUPERPOWER, ROCK_SMASH, EARTHQUAKE, STOMPING_TANTRUM, BULLDOZE, BLIZZARD, ICE_BEAM, FROST_BREATH, ICY_WIND, HAIL, GIGA_IMPACT, HYPER_BEAM, STRENGTH, FACADE, HIDDEN_POWER, ROUND, SNORE, FRUSTRATION, RETURN, AFTER_YOU, ATTRACT, BLOCK, CONFIDE, DOUBLE_TEAM, PROTECT, ROAR, SAFEGUARD, SLEEP_TALK, SUBSTITUTE, SWAGGER, TOXIC, REST, STONE_EDGE, ROCK_SLIDE, ROCK_TOMB, ROCK_POLISH, FLASH_CANNON, IRON_HEAD, GYRO_BALL, IRON_DEFENSE, SURF, WATER_PULSE, RAIN_DANCE, ENDURE, BODY_SLAM, HEAVY_SLAM, BODY_PRESS, HIGH_HORSEPOWER, HYDRO_PUMP, ICICLE_SPEAR, CRUNCH, ICE_FANG, AVALANCHE
	; end