	db BLAZIKEN ; 257

	db  80,  120,  70,  80,  110,  70
  ;  hp  atk  def  spd sat sdf

	db FIRE, FIGHTING ; type
	db 45 ; catch rate
	db 239 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F12_5 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/blaziken/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_SLOW ; growth rate
	dn EGG_FIELD, EGG_FIELD ; egg groups

	; tm/hm learnset
	tmhm U_TURN, KNOCK_OFF, FLING, DUAL_CHOP, THUNDER_PUNCH, FOCUS_PUNCH, FOCUS_BLAST, SUPERPOWER, BRICK_BREAK, LOW_SWEEP, POWER_UP_PUNCH, ROCK_SMASH, LOW_KICK, BULK_UP, BLAST_BURN, OVERHEAT, FIRE_BLAST, HEAT_WAVE, FLAMETHROWER, FIRE_PLEDGE, FIRE_PUNCH, FLAME_CHARGE, SUNNY_DAY, WILL_O_WISP, BOUNCE, AERIAL_ACE, ACROBATICS, DEFOG, SHADOW_CLAW, SOLAR_BEAM, EARTHQUAKE, BULLDOZE, GIGA_IMPACT, HYPER_BEAM, LAST_RESORT, STRENGTH, FACADE, HIDDEN_POWER, ROUND, CUT, SNORE, ECHOED_VOICE, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, HELPING_HAND, LASER_FOCUS, PROTECT, ROAR, SLEEP_TALK, SUBSTITUTE, SWAGGER, SWORDS_DANCE, WORK_UP, POISON_JAB, TOXIC, REST, ROLE_PLAY, STONE_EDGE, ROCK_SLIDE, ROCK_TOMB, ENDURE, MEGA_KICK, BODY_SLAM, MEGA_PUNCH, FOCUS_ENERGY, SWIFT, ASSURANCE, AGILITY, REVERSAL, BLAZE_KICK, BATON_PASS, FLARE_BLITZ, SCORCHING_SANDS, COACHING, FIRE_SPIN, REVENGE, DIG, BRAVE_BIRD, HEAT_CRASH, CLOSE_COMBAT, AURA_SPHERE
	; end