	db BOUFFALANT ; 626

	db  95,  110,  95,  55,  40,  95
  ;  hp  atk  def  spd sat sdf

	db NORMAL, NORMAL ; type
	db 45 ; catch rate
	db 172 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/bouffalant/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_FIELD, EGG_FIELD ; egg groups

	; tm/hm learnset
	tmhm THROAT_CHOP, PAYBACK, TAUNT, OUTRAGE, WILD_CHARGE, SUPERPOWER, ROCK_SMASH, SUNNY_DAY, AERIAL_ACE, EARTHQUAKE, STOMPING_TANTRUM, BULLDOZE, GIGA_IMPACT, UPROAR, STRENGTH, FACADE, HIDDEN_POWER, ROUND, CUT, SNORE, ENDEAVOR, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, PROTECT, SLEEP_TALK, SUBSTITUTE, SWAGGER, SWORDS_DANCE, WORK_UP, POISON_JAB, TOXIC, ZEN_HEADBUTT, REST, STONE_EDGE, ROCK_SLIDE, ROCK_TOMB, IRON_HEAD, SMART_STRIKE, SURF, RAIN_DANCE, ENDURE, BODY_SLAM, HIGH_HORSEPOWER, FOCUS_ENERGY, SCARY_FACE, REVERSAL, REVENGE, RETALIATE, LASH_OUT, MEGAHORN, CLOSE_COMBAT
	; end