	db BRUXISH ; 779

	db  68,  105,  70,  92,  70,  70
  ;  hp  atk  def  spd sat sdf

	db WATER, PSYCHIC ; type
	db 80 ; catch rate
	db 166 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 16 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/bruxish/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_WATER2, EGG_WATER2 ; egg groups

	; tm/hm learnset
	tmhm SIGNAL_BEAM, PAYBACK, FLING, EMBARGO, SNATCH, TAUNT, TORMENT, BULK_UP, AERIAL_ACE, BLIZZARD, ICE_BEAM, FROST_BREATH, GIGA_IMPACT, UPROAR, FACADE, HIDDEN_POWER, ROUND, SNORE, FRUSTRATION, RETURN, AFTER_YOU, ATTRACT, CONFIDE, DOUBLE_TEAM, PAIN_SPLIT, PROTECT, SAFEGUARD, SLEEP_TALK, SUBSTITUTE, SWAGGER, SWORDS_DANCE, VENOSHOCK, TOXIC, DREAM_EATER, PSYCHIC, ALLY_SWITCH, CALM_MIND, LIGHT_SCREEN, MAGIC_COAT, MAGIC_ROOM, REFLECT, REST, TELEKINESIS, TRICK_ROOM, WONDER_ROOM, IRON_TAIL, AQUA_TAIL, SURF, LIQUIDATION, SCALD, WATERFALL, WATER_PULSE, RAIN_DANCE, ENDURE
	; end