	db CLAWITZER ; 693

	db  71,  73,  88,  59,  120,  89
  ;  hp  atk  def  spd sat sdf

	db WATER, WATER ; type
	db 155 ; catch rate
	db 100 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 15 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/clawitzer/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_SLOW ; growth rate
	dn EGG_WATER1, EGG_WATER3 ; egg groups

	; tm/hm learnset
	tmhm U_TURN, DARK_PULSE, DRAGON_PULSE, FOCUS_BLAST, BOUNCE, SHADOW_BALL, ICE_BEAM, ICY_WIND, GIGA_IMPACT, HYPER_BEAM, FACADE, HIDDEN_POWER, ROUND, CUT, SNORE, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, HELPING_HAND, LASER_FOCUS, PROTECT, SLEEP_TALK, SUBSTITUTE, SWAGGER, SWORDS_DANCE, SLUDGE_WAVE, SLUDGE_BOMB, VENOSHOCK, TOXIC, REST, ROCK_SLIDE, SMACK_DOWN, IRON_TAIL, FLASH_CANNON, AQUA_TAIL, SURF, LIQUIDATION, DIVE, SCALD, WATERFALL, WATER_PULSE, RAIN_DANCE, ENDURE, FLIP_TURN, TERRAIN_PULSE, AURA_SPHERE
	; end