	db CLEFAIRY ; 35

	db  70,  45,  48,  35,  60,  65
  ;  hp  atk  def  spd sat sdf

	db FAIRY, FAIRY ; type
	db 150 ; catch rate
	db 113 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F75 ; gender ratio
	db 100 ; unknown 1
	db 10 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/clefairy/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_FAST ; growth rate
	dn EGG_FAIRY, EGG_FAIRY ; egg groups

	; tm/hm learnset
	tmhm SIGNAL_BEAM, KNOCK_OFF, FLING, SNATCH, THUNDER, THUNDERBOLT, THUNDER_PUNCH, SHOCK_WAVE, CHARGE_BEAM, THUNDER_WAVE, DAZZLING_GLEAM, FOCUS_PUNCH, BRICK_BREAK, DRAIN_PUNCH, POWER_UP_PUNCH, ROCK_SMASH, FIRE_BLAST, FLAMETHROWER, FIRE_PUNCH, SUNNY_DAY, BOUNCE, SHADOW_BALL, SOLAR_BEAM, GRASS_KNOT, BLIZZARD, ICE_BEAM, ICE_PUNCH, ICY_WIND, LAST_RESORT, HYPER_VOICE, UPROAR, STRENGTH, FACADE, COVET, HIDDEN_POWER, ROUND, SNORE, ECHOED_VOICE, ENDEAVOR, FRUSTRATION, RETURN, AFTER_YOU, ATTRACT, CONFIDE, DOUBLE_TEAM, HEAL_BELL, HELPING_HAND, PROTECT, PSYCH_UP, RECYCLE, SAFEGUARD, SLEEP_TALK, SUBSTITUTE, SWAGGER, WORK_UP, TOXIC, DREAM_EATER, PSYCHIC, PSYSHOCK, ZEN_HEADBUTT, ALLY_SWITCH, CALM_MIND, GRAVITY, LIGHT_SCREEN, MAGIC_COAT, REFLECT, REST, ROLE_PLAY, TELEKINESIS, TRICK, WONDER_ROOM, STEALTH_ROCK, IRON_TAIL, WATER_PULSE, RAIN_DANCE, ENDURE, MEGA_KICK, BODY_SLAM, MEGA_PUNCH, MAGICAL_LEAF, BATON_PASS, METRONOME, DIG, AMNESIA, DUAL_WINGBEAT, RETALIATE, FAKE_TEARS, STORED_POWER, IMPRISON, PLAY_ROUGH, CHARM, METEOR_BEAM, ENCORE, MYSTICAL_FIRE, DRAINING_KISS, MISTY_EXPLOSION, MISTY_TERRAIN, TRI_ATTACK, COSMIC_POWER
	; end