	db COALOSSAL ; 839

	db  110,  80,  120,  30,  80,  90
  ;  hp  atk  def  spd sat sdf

	db ROCK, FIRE ; type
	db 45 ; catch rate
	db 255 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 16 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/coalossal/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_SLOW ; growth rate
	dn EGG_MINERAL, EGG_MINERAL ; egg groups

	; tm/hm learnset
	tmhm OVERHEAT, FIRE_BLAST, HEAT_WAVE, FLAMETHROWER, FIRE_PUNCH, WILL_O_WISP, SOLAR_BEAM, EARTHQUAKE, EARTH_POWER, BULLDOZE, GIGA_IMPACT, HYPER_BEAM, FACADE, ROUND, SNORE, ATTRACT, PROTECT, SLEEP_TALK, SUBSTITUTE, REFLECT, REST, STONE_EDGE, ROCK_SLIDE, ROCK_TOMB, SANDSTORM, STEALTH_ROCK, IRON_HEAD, GYRO_BALL, IRON_DEFENSE, SCALD, ENDURE, MEGA_KICK, BODY_SLAM, HEAVY_SLAM, SELF_DESTRUCT, BODY_PRESS, MEGA_PUNCH, HIGH_HORSEPOWER, FLARE_BLITZ, SCORCHING_SANDS, FIRE_SPIN, DIG, SAND_TOMB, METEOR_BEAM, ROCK_BLAST, SPIKES, HEAT_CRASH
	; end