	db COBALION ; 638

	db  91,  90,  129,  108,  90,  72
  ;  hp  atk  def  spd sat sdf

	db STEEL, FIGHTING ; type
	db 3 ; catch rate
	db 261 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_UNKNOWN ; gender ratio
	db 100 ; unknown 1
	db 80 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/cobalion/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_SLOW ; growth rate
	dn EGG_NONE, EGG_NONE ; egg groups

	; tm/hm learnset
	tmhm X_SCISSOR, TAUNT, VOLT_SWITCH, MAGNET_RISE, THUNDER_WAVE, FOCUS_BLAST, SUPERPOWER, BRICK_BREAK, ROCK_SMASH, BOUNCE, AERIAL_ACE, GIGA_IMPACT, HYPER_BEAM, STRENGTH, FACADE, HIDDEN_POWER, ROUND, CUT, SNORE, FALSE_SWIPE, FRUSTRATION, RETURN, BLOCK, CONFIDE, DOUBLE_TEAM, HELPING_HAND, LASER_FOCUS, PROTECT, PSYCH_UP, ROAR, SAFEGUARD, SLEEP_TALK, SUBSTITUTE, SWAGGER, SWORDS_DANCE, WORK_UP, POISON_JAB, TOXIC, ZEN_HEADBUTT, CALM_MIND, REFLECT, REST, STONE_EDGE, ROCK_POLISH, SANDSTORM, STEALTH_ROCK, FLASH_CANNON, IRON_HEAD, SMART_STRIKE, IRON_DEFENSE, ENDURE, STEEL_BEAM, SWIFT, SCARY_FACE, REVERSAL, COACHING, REVENGE, AIR_SLASH, RETALIATE, MEGAHORN, CLOSE_COMBAT
	; end