	db COMFEY ; 764

	db  51,  52,  90,  100,  82,  110
  ;  hp  atk  def  spd sat sdf

	db FAIRY, FAIRY ; type
	db 60 ; catch rate
	db 170 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F75 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/comfey/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_FAST ; growth rate
	dn EGG_GRASS, EGG_GRASS ; egg groups

	; tm/hm learnset
	tmhm U_TURN, THIEF, FLING, TAUNT, DAZZLING_GLEAM, SUNNY_DAY, ACROBATICS, DEFOG, TAILWIND, SOLAR_BEAM, ENERGY_BALL, SEED_BOMB, GIGA_DRAIN, GRASS_KNOT, SYNTHESIS, WORRY_SEED, HYPER_BEAM, FACADE, COVET, HIDDEN_POWER, ROUND, SNORE, ECHOED_VOICE, BIND, FRUSTRATION, RETURN, AFTER_YOU, ATTRACT, CONFIDE, DOUBLE_TEAM, HEAL_BELL, HELPING_HAND, NATURE_POWER, PAIN_SPLIT, PROTECT, PSYCH_UP, SAFEGUARD, SLEEP_TALK, SUBSTITUTE, SWAGGER, TOXIC, ALLY_SWITCH, CALM_MIND, LIGHT_SCREEN, MAGIC_COAT, REST, ROLE_PLAY, TELEKINESIS, TRICK, TRICK_ROOM, ENDURE, MAGICAL_LEAF, GRASSY_GLIDE, GRASSY_TERRAIN, BULLET_SEED, AMNESIA, STORED_POWER, PLAY_ROUGH, POLLEN_PUFF, CHARM, ENCORE, DRAINING_KISS
	; end