	db COPPERAJAH ; 879

	db  122,  130,  69,  30,  80,  69
  ;  hp  atk  def  spd sat sdf

	db STEEL, STEEL ; type
	db 90 ; catch rate
	db 175 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 26 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/copperajah/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_FIELD, EGG_MINERAL ; egg groups

	; tm/hm learnset
	tmhm BRUTAL_SWING, SNARL, PAYBACK, FLING, TAUNT, OUTRAGE, SUPERPOWER, BRICK_BREAK, EARTHQUAKE, EARTH_POWER, STOMPING_TANTRUM, BULLDOZE, GIGA_IMPACT, HYPER_BEAM, FACADE, ROUND, SNORE, ATTRACT, PROTECT, SLEEP_TALK, SUBSTITUTE, WORK_UP, ZEN_HEADBUTT, REST, STONE_EDGE, ROCK_SLIDE, ROCK_TOMB, STEALTH_ROCK, FLASH_CANNON, IRON_HEAD, IRON_DEFENSE, ENDURE, STEEL_BEAM, MEGA_KICK, BODY_SLAM, HEAVY_SLAM, STEEL_ROLLER, BODY_PRESS, HIGH_HORSEPOWER, SCREECH, SCARY_FACE, MUD_SHOT, REVENGE, DIG, PLAY_ROUGH, ROCK_BLAST, HEAT_CRASH, POWER_WHIP
	; end