	db DARMANITAN-STANDARD ; 555

	db  105,  140,  55,  95,  30,  55
  ;  hp  atk  def  spd sat sdf

	db FIRE, FIRE ; type
	db 60 ; catch rate
	db 168 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/darmanitan/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_SLOW ; growth rate
	dn EGG_FIELD, EGG_FIELD ; egg groups

	; tm/hm learnset
	tmhm U_TURN, THIEF, PAYBACK, FLING, SNATCH, TAUNT, TORMENT, FOCUS_PUNCH, FOCUS_BLAST, SUPERPOWER, BRICK_BREAK, POWER_UP_PUNCH, ROCK_SMASH, BULK_UP, OVERHEAT, FIRE_BLAST, HEAT_WAVE, FLAMETHROWER, FIRE_PUNCH, FLAME_CHARGE, SUNNY_DAY, WILL_O_WISP, SOLAR_BEAM, GRASS_KNOT, EARTHQUAKE, BULLDOZE, GIGA_IMPACT, HYPER_BEAM, UPROAR, STRENGTH, FACADE, HIDDEN_POWER, ROUND, SNORE, ENDEAVOR, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, LASER_FOCUS, PROTECT, ROAR, SLEEP_TALK, SUBSTITUTE, SWAGGER, WORK_UP, TOXIC, PSYCHIC, ZEN_HEADBUTT, REST, TRICK, STONE_EDGE, ROCK_SLIDE, ROCK_TOMB, SMACK_DOWN, IRON_HEAD, GYRO_BALL, IRON_DEFENSE, ENDURE, MEGA_KICK, BODY_SLAM, BODY_PRESS, MEGA_PUNCH, FOCUS_ENERGY, REVERSAL, FIRE_FANG, FLARE_BLITZ, FIRE_SPIN, DIG, EXPANDING_FORCE, GUARD_SWAP, POWER_SWAP, FUTURE_SIGHT, LASH_OUT, BURNING_JEALOUSY, ENCORE, MYSTICAL_FIRE
	; end