	db DECIDUEYE ; 724

	db  78,  107,  75,  70,  100,  100
  ;  hp  atk  def  spd sat sdf

	db GRASS, GHOST ; type
	db 45 ; catch rate
	db 239 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F12_5 ; gender ratio
	db 100 ; unknown 1
	db 16 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/decidueye/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_SLOW ; growth rate
	dn EGG_FLYING, EGG_FLYING ; egg groups

	; tm/hm learnset
	tmhm U_TURN, LOW_SWEEP, SUNNY_DAY, SKY_ATTACK, ACROBATICS, DEFOG, ROOST, TAILWIND, SHADOW_BALL, SHADOW_CLAW, SPITE, FRENZY_PLANT, SOLAR_BEAM, ENERGY_BALL, GRASS_PLEDGE, SEED_BOMB, GIGA_DRAIN, GRASS_KNOT, SYNTHESIS, WORRY_SEED, GIGA_IMPACT, HYPER_BEAM, FACADE, COVET, HIDDEN_POWER, ROUND, SNORE, ECHOED_VOICE, FALSE_SWIPE, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, LASER_FOCUS, NATURE_POWER, PROTECT, SAFEGUARD, SLEEP_TALK, SUBSTITUTE, SWAGGER, SWORDS_DANCE, WORK_UP, TOXIC, LIGHT_SCREEN, REST, SMACK_DOWN, STEEL_WING, ENDURE, SWIFT, SOLAR_BLADE, GRASSY_GLIDE, LEAF_STORM, BATON_PASS, AIR_SLASH, NASTY_PLOT, DUAL_WINGBEAT, BRAVE_BIRD, HURRICANE, IMPRISON, PSYCHO_CUT, SKITTER_SMACK, HEX, POLTERGEIST, PHANTOM_FORCE, LEAF_BLADE
	; end