	db DEDENNE ; 702

	db  67,  58,  57,  101,  81,  67
  ;  hp  atk  def  spd sat sdf

	db ELECTRIC, FAIRY ; type
	db 200 ; catch rate
	db 151 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/dedenne/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_FIELD, EGG_FAIRY ; egg groups

	; tm/hm learnset
	tmhm SIGNAL_BEAM, U_TURN, THIEF, FLING, THUNDER, THUNDERBOLT, WILD_CHARGE, THUNDER_PUNCH, VOLT_SWITCH, SHOCK_WAVE, ELECTROWEB, CHARGE_BEAM, MAGNET_RISE, THUNDER_WAVE, DAZZLING_GLEAM, SUNNY_DAY, AERIAL_ACE, GRASS_KNOT, GIGA_IMPACT, LAST_RESORT, FACADE, COVET, HIDDEN_POWER, ROUND, CUT, SNORE, FRUSTRATION, RETURN, SUPER_FANG, ATTRACT, CONFIDE, DOUBLE_TEAM, HELPING_HAND, PROTECT, RECYCLE, SLEEP_TALK, SUBSTITUTE, SWAGGER, TOXIC, ALLY_SWITCH, REST, IRON_TAIL, RAIN_DANCE, ENDURE, ELECTRIC_TERRAIN, ELECTRO_BALL, DIG, RETALIATE, PLAY_ROUGH, CHARM, RISING_VOLTAGE, EERIE_IMPULSE
	; end