	db DELCATTY ; 301

	db  70,  65,  65,  90,  55,  55
  ;  hp  atk  def  spd sat sdf

	db NORMAL, NORMAL ; type
	db 60 ; catch rate
	db 140 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F75 ; gender ratio
	db 100 ; unknown 1
	db 15 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/delcatty/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_FAST ; growth rate
	dn EGG_FIELD, EGG_FAIRY ; egg groups

	; tm/hm learnset
	tmhm PAYBACK, THUNDER, THUNDERBOLT, WILD_CHARGE, SHOCK_WAVE, CHARGE_BEAM, THUNDER_WAVE, ROCK_SMASH, SUNNY_DAY, SHADOW_BALL, SOLAR_BEAM, GRASS_KNOT, STOMPING_TANTRUM, BLIZZARD, ICE_BEAM, ICY_WIND, GIGA_IMPACT, HYPER_BEAM, LAST_RESORT, HYPER_VOICE, UPROAR, STRENGTH, FACADE, COVET, HIDDEN_POWER, ROUND, SNORE, ECHOED_VOICE, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, HEAL_BELL, HELPING_HAND, LASER_FOCUS, PROTECT, PSYCH_UP, SAFEGUARD, SLEEP_TALK, SUBSTITUTE, SWAGGER, WORK_UP, TOXIC, DREAM_EATER, ZEN_HEADBUTT, CALM_MIND, REST, IRON_TAIL, WATER_PULSE, RAIN_DANCE, ENDURE, SWIFT, DIG, RETALIATE
	; end