	db DHELMISE ; 781

	db  70,  131,  100,  40,  86,  90
  ;  hp  atk  def  spd sat sdf

	db GHOST, GRASS ; type
	db 25 ; catch rate
	db 181 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_UNKNOWN ; gender ratio
	db 100 ; unknown 1
	db 24 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/dhelmise/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_MINERAL, EGG_MINERAL ; egg groups

	; tm/hm learnset
	tmhm KNOCK_OFF, BRUTAL_SWING, THIEF, PAYBACK, EMBARGO, BRICK_BREAK, SUNNY_DAY, AERIAL_ACE, SHADOW_BALL, SHADOW_CLAW, SPITE, SOLAR_BEAM, ENERGY_BALL, GIGA_DRAIN, GRASS_KNOT, SYNTHESIS, EARTHQUAKE, BULLDOZE, GIGA_IMPACT, HYPER_BEAM, FACADE, HIDDEN_POWER, ROUND, SNORE, FRUSTRATION, RETURN, BLOCK, CONFIDE, DOUBLE_TEAM, HELPING_HAND, PAIN_SPLIT, PROTECT, SLEEP_TALK, SUBSTITUTE, SWAGGER, SWORDS_DANCE, SLUDGE_WAVE, TOXIC, ALLY_SWITCH, REST, ROLE_PLAY, TELEKINESIS, ROCK_SLIDE, FLASH_CANNON, IRON_HEAD, GYRO_BALL, IRON_DEFENSE, SURF, LIQUIDATION, RAIN_DANCE, ENDURE, HEAVY_SLAM, STEEL_ROLLER, BODY_PRESS, SOLAR_BLADE, ASSURANCE, GRASSY_GLIDE, MUDDY_WATER, WHIRLPOOL, HYDRO_PUMP, HEX, POWER_WHIP, BRINE, POLTERGEIST, PHANTOM_FORCE
	; end