	db DRACOZOLT ; 880

	db  90,  100,  90,  75,  80,  70
  ;  hp  atk  def  spd sat sdf

	db ELECTRIC, DRAGON ; type
	db 45 ; catch rate
	db 177 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_UNKNOWN ; gender ratio
	db 100 ; unknown 1
	db 36 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/dracozolt/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_SLOW ; growth rate
	dn EGG_NONE, EGG_NONE ; egg groups

	; tm/hm learnset
	tmhm BRUTAL_SWING, TAUNT, DRACO_METEOR, OUTRAGE, DRAGON_PULSE, DRAGON_CLAW, THUNDER, THUNDERBOLT, WILD_CHARGE, THUNDER_PUNCH, THUNDER_WAVE, LOW_KICK, FIRE_BLAST, FLAMETHROWER, SUNNY_DAY, EARTHQUAKE, EARTH_POWER, STOMPING_TANTRUM, BULLDOZE, GIGA_IMPACT, HYPER_BEAM, FACADE, ROUND, SNORE, PROTECT, SLEEP_TALK, SUBSTITUTE, REST, STONE_EDGE, ROCK_SLIDE, ROCK_TOMB, IRON_TAIL, RAIN_DANCE, ENDURE, MEGA_KICK, BODY_SLAM, MEGA_PUNCH, HIGH_HORSEPOWER, FIRE_FANG, ELECTRO_BALL, FIRE_SPIN, BREAKING_SWIPE, THUNDER_FANG, METEOR_BEAM, ROCK_BLAST, RISING_VOLTAGE
	; end