	db DRAGAPULT ; 887

	db  88,  120,  75,  142,  100,  75
  ;  hp  atk  def  spd sat sdf

	db DRAGON, GHOST ; type
	db 45 ; catch rate
	db 300 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 41 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/dragapult/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_SLOW ; growth rate
	dn EGG_AMORPHOUS, EGG_DRAGON ; egg groups

	; tm/hm learnset
	tmhm U_TURN, THIEF, DRACO_METEOR, OUTRAGE, DRAGON_PULSE, DRAGON_CLAW, THUNDER, THUNDERBOLT, THUNDER_WAVE, FIRE_BLAST, FLAMETHROWER, WILL_O_WISP, FLY, ACROBATICS, SHADOW_BALL, SOLAR_BEAM, GIGA_IMPACT, HYPER_BEAM, FACADE, ROUND, SNORE, ATTRACT, HELPING_HAND, PROTECT, SLEEP_TALK, SUBSTITUTE, ALLY_SWITCH, LIGHT_SCREEN, REFLECT, REST, STEEL_WING, SURF, DIVE, SCALD, ENDURE, BODY_SLAM, SWIFT, ASSURANCE, AGILITY, BATON_PASS, HYDRO_PUMP, BREAKING_SWIPE, PSYCHIC_FANGS, BEAT_UP, DRAGON_DANCE, HEX, BRINE, PHANTOM_FORCE, TRI_ATTACK
	; end