	db DRAMPA ; 780

	db  78,  60,  85,  36,  135,  91
  ;  hp  atk  def  spd sat sdf

	db NORMAL, DRAGON ; type
	db 70 ; catch rate
	db 170 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/drampa/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_MONSTER, EGG_DRAGON ; egg groups

	; tm/hm learnset
	tmhm SIGNAL_BEAM, SNARL, FLING, DRACO_METEOR, OUTRAGE, DRAGON_PULSE, DRAGON_CLAW, DRAGON_TAIL, THUNDER, THUNDERBOLT, SHOCK_WAVE, THUNDER_WAVE, FOCUS_BLAST, SUPERPOWER, FIRE_BLAST, HEAT_WAVE, FLAMETHROWER, SUNNY_DAY, FLY, DEFOG, ROOST, TAILWIND, SHADOW_BALL, SHADOW_CLAW, SOLAR_BEAM, ENERGY_BALL, GRASS_KNOT, EARTHQUAKE, STOMPING_TANTRUM, BULLDOZE, BLIZZARD, ICE_BEAM, ICY_WIND, GIGA_IMPACT, HYPER_BEAM, HYPER_VOICE, UPROAR, FACADE, HIDDEN_POWER, ROUND, SNORE, ECHOED_VOICE, ENDEAVOR, FRUSTRATION, RETURN, ATTRACT, BLOCK, CONFIDE, DOUBLE_TEAM, HELPING_HAND, NATURE_POWER, PROTECT, PSYCH_UP, ROAR, SAFEGUARD, SLEEP_TALK, SUBSTITUTE, WORK_UP, TOXIC, CALM_MIND, LIGHT_SCREEN, REST, ROCK_SLIDE, STEEL_WING, SURF, WATER_PULSE, RAIN_DANCE, ENDURE, SWIFT, HYDRO_PUMP, BREAKING_SWIPE, SCALE_SHOT, AMNESIA, HURRICANE, PLAY_ROUGH, LASH_OUT, DRAGON_DANCE
	; end