	db DRAPION ; 452

	db  70,  90,  110,  95,  60,  75
  ;  hp  atk  def  spd sat sdf

	db POISON, DARK ; type
	db 45 ; catch rate
	db 175 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/drapion/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_SLOW ; growth rate
	dn EGG_BUG, EGG_WATER3 ; egg groups

	; tm/hm learnset
	tmhm LEECH_LIFE, X_SCISSOR, BUG_BITE, STRUGGLE_BUG, INFESTATION, DARK_PULSE, THROAT_CHOP, KNOCK_OFF, BRUTAL_SWING, THIEF, SNARL, PAYBACK, FLING, TAUNT, TORMENT, BRICK_BREAK, ROCK_SMASH, SUNNY_DAY, AERIAL_ACE, SHADOW_BALL, EARTHQUAKE, STOMPING_TANTRUM, BULLDOZE, GIGA_IMPACT, HYPER_BEAM, STRENGTH, FACADE, HIDDEN_POWER, ROUND, CUT, SNORE, FALSE_SWIPE, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, PROTECT, ROAR, SLEEP_TALK, SUBSTITUTE, SWAGGER, SWORDS_DANCE, SLUDGE_BOMB, POISON_JAB, VENOSHOCK, TOXIC, REST, ROCK_SLIDE, ROCK_TOMB, IRON_TAIL, IRON_DEFENSE, AQUA_TAIL, RAIN_DANCE, ENDURE, SCREECH, ASSURANCE, SCARY_FACE, AGILITY, FIRE_FANG, CRUNCH, DIG, THUNDER_FANG, ICE_FANG, RETALIATE, BUG_BUZZ, LASH_OUT, SKITTER_SMACK, SAND_TOMB, VENOM_DRENCH, PIN_MISSILE, CROSS_POISON, TOXIC_SPIKES
	; end