	db DREDNAW ; 834

	db  90,  115,  90,  74,  48,  68
  ;  hp  atk  def  spd sat sdf

	db WATER, ROCK ; type
	db 75 ; catch rate
	db 170 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 21 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/drednaw/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_MONSTER, EGG_WATER1 ; egg groups

	; tm/hm learnset
	tmhm THROAT_CHOP, PAYBACK, SUPERPOWER, EARTHQUAKE, EARTH_POWER, STOMPING_TANTRUM, BULLDOZE, BLIZZARD, ICE_BEAM, GIGA_IMPACT, HYPER_BEAM, FACADE, ROUND, SNORE, FALSE_SWIPE, ATTRACT, PROTECT, SLEEP_TALK, SUBSTITUTE, SWORDS_DANCE, POISON_JAB, REST, STONE_EDGE, ROCK_SLIDE, ROCK_TOMB, SANDSTORM, STEALTH_ROCK, IRON_TAIL, SMART_STRIKE, IRON_DEFENSE, SURF, LIQUIDATION, DIVE, SCALD, WATERFALL, RAIN_DANCE, ENDURE, BODY_SLAM, BODY_PRESS, HIGH_HORSEPOWER, ASSURANCE, SCARY_FACE, MUD_SHOT, REVENGE, MUDDY_WATER, WHIRLPOOL, HYDRO_PUMP, SCALE_SHOT, CRUNCH, DIG, ICE_FANG, SKITTER_SMACK, SAND_TOMB, RAZOR_SHELL, METEOR_BEAM, ROCK_BLAST, MEGAHORN
	; end