	db DUNSPARCE ; 206

	db  100,  70,  70,  45,  65,  65
  ;  hp  atk  def  spd sat sdf

	db NORMAL, NORMAL ; type
	db 190 ; catch rate
	db 145 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/dunsparce/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_FIELD, EGG_FIELD ; egg groups

	; tm/hm learnset
	tmhm THIEF, THUNDER, THUNDERBOLT, WILD_CHARGE, SHOCK_WAVE, CHARGE_BEAM, THUNDER_WAVE, ROCK_SMASH, FIRE_BLAST, FLAMETHROWER, SUNNY_DAY, ROOST, SHADOW_BALL, SPITE, SOLAR_BEAM, EARTHQUAKE, DRILL_RUN, STOMPING_TANTRUM, BULLDOZE, BLIZZARD, ICE_BEAM, LAST_RESORT, STRENGTH, FACADE, HIDDEN_POWER, ROUND, SNORE, BIND, ENDEAVOR, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, HELPING_HAND, PAIN_SPLIT, PROTECT, PSYCH_UP, SLEEP_TALK, SUBSTITUTE, SWAGGER, POISON_JAB, TOXIC, DREAM_EATER, ZEN_HEADBUTT, CALM_MIND, MAGIC_COAT, REST, ROCK_SLIDE, ROCK_TOMB, STEALTH_ROCK, IRON_TAIL, GYRO_BALL, AQUA_TAIL, WATER_PULSE, RAIN_DANCE, ENDURE, BODY_SLAM, SCREECH, BATON_PASS, SCALE_SHOT, AIR_SLASH, DIG, AMNESIA, DUAL_WINGBEAT, RETALIATE, STORED_POWER, SKITTER_SMACK, HEX, TERRAIN_PULSE
	; end