	db ENTEI ; 244

	db  115,  115,  85,  100,  90,  75
  ;  hp  atk  def  spd sat sdf

	db FIRE, FIRE ; type
	db 3 ; catch rate
	db 261 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_UNKNOWN ; gender ratio
	db 100 ; unknown 1
	db 80 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/entei/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_SLOW ; growth rate
	dn EGG_NONE, EGG_NONE ; egg groups

	; tm/hm learnset
	tmhm SNARL, QUASH, ROCK_SMASH, OVERHEAT, FIRE_BLAST, HEAT_WAVE, FLAMETHROWER, FLAME_CHARGE, SUNNY_DAY, WILL_O_WISP, SHADOW_BALL, SOLAR_BEAM, STOMPING_TANTRUM, BULLDOZE, GIGA_IMPACT, HYPER_BEAM, STRENGTH, FACADE, HIDDEN_POWER, ROUND, CUT, SNORE, FRUSTRATION, RETURN, CONFIDE, DOUBLE_TEAM, HELPING_HAND, LASER_FOCUS, PROTECT, PSYCH_UP, ROAR, SLEEP_TALK, SUBSTITUTE, SWAGGER, TOXIC, CALM_MIND, REFLECT, REST, STONE_EDGE, SANDSTORM, IRON_TAIL, IRON_HEAD, RAIN_DANCE, ENDURE, BODY_SLAM, SWIFT, SCARY_FACE, AGILITY, REVERSAL, FIRE_FANG, FLARE_BLITZ, SCORCHING_SANDS, FIRE_SPIN, WEATHER_BALL, CRUNCH, DIG
	; end