	db ESCAVALIER ; 589

	db  70,  135,  105,  20,  60,  105
  ;  hp  atk  def  spd sat sdf

	db BUG, STEEL ; type
	db 75 ; catch rate
	db 173 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 15 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/escavalier/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_BUG, EGG_BUG ; egg groups

	; tm/hm learnset
	tmhm X_SCISSOR, SIGNAL_BEAM, BUG_BITE, STRUGGLE_BUG, INFESTATION, KNOCK_OFF, BRUTAL_SWING, TAUNT, FOCUS_BLAST, ROCK_SMASH, AERIAL_ACE, ENERGY_BALL, GIGA_DRAIN, DRILL_RUN, GIGA_IMPACT, HYPER_BEAM, FACADE, HIDDEN_POWER, ROUND, CUT, SNORE, FALSE_SWIPE, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, LASER_FOCUS, PROTECT, SLEEP_TALK, SUBSTITUTE, SWAGGER, SWORDS_DANCE, POISON_JAB, TOXIC, REST, IRON_HEAD, SMART_STRIKE, IRON_DEFENSE, RAIN_DANCE, ENDURE, STEEL_BEAM, SCREECH, SCARY_FACE, AGILITY, REVERSAL, REVENGE, BUG_BUZZ, RAZOR_SHELL, MEGAHORN, CLOSE_COMBAT, ENCORE
	; end