	db FROSLASS ; 478

	db  70,  80,  70,  110,  80,  70
  ;  hp  atk  def  spd sat sdf

	db ICE, GHOST ; type
	db 75 ; catch rate
	db 168 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F100 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/froslass/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_FAIRY, EGG_MINERAL ; egg groups

	; tm/hm learnset
	tmhm SIGNAL_BEAM, PAYBACK, FLING, EMBARGO, SNATCH, TAUNT, TORMENT, THUNDER, THUNDERBOLT, SHOCK_WAVE, THUNDER_WAVE, WILL_O_WISP, SHADOW_BALL, SPITE, BLIZZARD, ICE_BEAM, ICE_PUNCH, FROST_BREATH, ICY_WIND, AURORA_VEIL, HAIL, GIGA_IMPACT, HYPER_BEAM, FACADE, HIDDEN_POWER, ROUND, SNORE, FRUSTRATION, RETURN, ATTRACT, BLOCK, CONFIDE, DOUBLE_TEAM, LASER_FOCUS, PAIN_SPLIT, PROTECT, PSYCH_UP, SAFEGUARD, SLEEP_TALK, SUBSTITUTE, SWAGGER, TOXIC, DREAM_EATER, PSYCHIC, ALLY_SWITCH, LIGHT_SCREEN, REFLECT, REST, TELEKINESIS, TRICK, WATER_PULSE, RAIN_DANCE, ENDURE, BODY_SLAM, WEATHER_BALL, ICICLE_SPEAR, CRUNCH, ICE_FANG, FAKE_TEARS, IMPRISON, CHARM, SPIKES, HEX, POLTERGEIST, DRAINING_KISS, AVALANCHE, TRIPLE_AXEL
	; end