	db GALLADE ; 475

	db  68,  125,  65,  80,  65,  115
  ;  hp  atk  def  spd sat sdf

	db PSYCHIC, FIGHTING ; type
	db 45 ; catch rate
	db 233 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F0 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/gallade/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_SLOW ; growth rate
	dn EGG_HUMANLIKE, EGG_AMORPHOUS ; egg groups

	; tm/hm learnset
	tmhm X_SCISSOR, SIGNAL_BEAM, THROAT_CHOP, KNOCK_OFF, THIEF, FLING, SNATCH, TAUNT, TORMENT, DUAL_CHOP, THUNDERBOLT, THUNDER_PUNCH, SHOCK_WAVE, CHARGE_BEAM, THUNDER_WAVE, DAZZLING_GLEAM, FOCUS_PUNCH, FOCUS_BLAST, BRICK_BREAK, DRAIN_PUNCH, LOW_SWEEP, POWER_UP_PUNCH, ROCK_SMASH, LOW_KICK, BULK_UP, FIRE_PUNCH, SUNNY_DAY, WILL_O_WISP, AERIAL_ACE, SHADOW_BALL, ENERGY_BALL, GRASS_KNOT, EARTHQUAKE, BULLDOZE, ICE_PUNCH, ICY_WIND, GIGA_IMPACT, HYPER_BEAM, HYPER_VOICE, STRENGTH, FACADE, HIDDEN_POWER, ROUND, CUT, SNORE, ECHOED_VOICE, FALSE_SWIPE, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, HELPING_HAND, LASER_FOCUS, PAIN_SPLIT, PROTECT, PSYCH_UP, RECYCLE, SAFEGUARD, SLEEP_TALK, SUBSTITUTE, SWAGGER, SWORDS_DANCE, WORK_UP, POISON_JAB, TOXIC, DREAM_EATER, PSYCHIC, PSYSHOCK, ZEN_HEADBUTT, ALLY_SWITCH, CALM_MIND, LIGHT_SCREEN, MAGIC_COAT, MAGIC_ROOM, REFLECT, REST, SKILL_SWAP, TELEKINESIS, TRICK, TRICK_ROOM, WONDER_ROOM, STONE_EDGE, ROCK_SLIDE, ROCK_TOMB, RAIN_DANCE, ENDURE, MEGA_KICK, BODY_SLAM, MEGA_PUNCH, SWIFT, SOLAR_BLADE, MAGICAL_LEAF, REVERSAL, COACHING, REVENGE, AIR_SLASH, RETALIATE, EXPANDING_FORCE, STORED_POWER, FUTURE_SIGHT, IMPRISON, PSYCHO_CUT, CHARM, CLOSE_COMBAT, ENCORE, DRAINING_KISS, LEAF_BLADE, TRIPLE_AXEL, MISTY_TERRAIN, AURA_SPHERE
	; end