	db GARBODOR ; 569

	db  80,  95,  82,  75,  60,  82
  ;  hp  atk  def  spd sat sdf

	db POISON, POISON ; type
	db 60 ; catch rate
	db 166 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/garbodor/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_MINERAL, EGG_MINERAL ; egg groups

	; tm/hm learnset
	tmhm INFESTATION, DARK_PULSE, THIEF, PAYBACK, FLING, THUNDERBOLT, FOCUS_BLAST, DRAIN_PUNCH, SUNNY_DAY, SPITE, SOLAR_BEAM, SEED_BOMB, GIGA_DRAIN, STOMPING_TANTRUM, EXPLOSION, GIGA_IMPACT, HYPER_BEAM, FACADE, HIDDEN_POWER, ROUND, SNORE, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, PAIN_SPLIT, PROTECT, RECYCLE, SLEEP_TALK, SUBSTITUTE, SWAGGER, GUNK_SHOT, SLUDGE_WAVE, SLUDGE_BOMB, VENOSHOCK, TOXIC, PSYCHIC, REST, SMACK_DOWN, ROCK_POLISH, RAIN_DANCE, ENDURE, BODY_SLAM, SELF_DESTRUCT, BODY_PRESS, SCREECH, AMNESIA, ROCK_BLAST, SPIKES, VENOM_DRENCH, CROSS_POISON, TOXIC_SPIKES, CORROSIVE_GAS
	; end