	db GIRATINA ; 487

	db  150,  100,  120,  90,  100,  120
  ;  hp  atk  def  spd sat sdf

	db GHOST, DRAGON ; type
	db 3 ; catch rate
	db 306 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_UNKNOWN ; gender ratio
	db 100 ; unknown 1
	db 120 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/giratina/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_SLOW ; growth rate
	dn EGG_NONE, EGG_NONE ; egg groups

	; tm/hm learnset
	tmhm DARK_PULSE, BRUTAL_SWING, PAYBACK, DRACO_METEOR, OUTRAGE, DRAGON_PULSE, DRAGON_CLAW, DRAGON_TAIL, THUNDER, THUNDERBOLT, SHOCK_WAVE, CHARGE_BEAM, THUNDER_WAVE, ROCK_SMASH, SUNNY_DAY, WILL_O_WISP, FLY, AERIAL_ACE, DEFOG, SHADOW_BALL, SHADOW_CLAW, SPITE, ENERGY_BALL, EARTHQUAKE, EARTH_POWER, BULLDOZE, ICY_WIND, GIGA_IMPACT, HYPER_BEAM, HYPER_VOICE, STRENGTH, FACADE, HIDDEN_POWER, ROUND, CUT, SNORE, ECHOED_VOICE, FRUSTRATION, RETURN, CONFIDE, DOUBLE_TEAM, PAIN_SPLIT, PROTECT, PSYCH_UP, ROAR, SAFEGUARD, SLEEP_TALK, SUBSTITUTE, SWAGGER, TOXIC, DREAM_EATER, PSYCHIC, CALM_MIND, GRAVITY, REST, TELEKINESIS, STONE_EDGE, IRON_TAIL, IRON_HEAD, STEEL_WING, AQUA_TAIL, RAIN_DANCE, ENDURE, BODY_SLAM, SWIFT, SCARY_FACE, BREAKING_SWIPE, DUAL_WINGBEAT, HEX, POLTERGEIST, PHANTOM_FORCE, AURA_SPHERE
	; end