	db GOLETT ; 622

	db  59,  74,  50,  35,  35,  50
  ;  hp  atk  def  spd sat sdf

	db GROUND, GHOST ; type
	db 190 ; catch rate
	db 61 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_UNKNOWN ; gender ratio
	db 100 ; unknown 1
	db 25 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/golett/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_MINERAL, EGG_MINERAL ; egg groups

	; tm/hm learnset
	tmhm SIGNAL_BEAM, THIEF, FLING, THUNDER_PUNCH, SHOCK_WAVE, FOCUS_PUNCH, FOCUS_BLAST, SUPERPOWER, BRICK_BREAK, DRAIN_PUNCH, LOW_SWEEP, POWER_UP_PUNCH, ROCK_SMASH, LOW_KICK, FIRE_PUNCH, SHADOW_BALL, GRASS_KNOT, EARTHQUAKE, EARTH_POWER, STOMPING_TANTRUM, BULLDOZE, ICE_BEAM, ICE_PUNCH, ICY_WIND, STRENGTH, FACADE, HIDDEN_POWER, ROUND, SNORE, FRUSTRATION, RETURN, BLOCK, CONFIDE, DOUBLE_TEAM, HELPING_HAND, PROTECT, SAFEGUARD, SLEEP_TALK, SUBSTITUTE, SWAGGER, TOXIC, PSYCHIC, ALLY_SWITCH, GRAVITY, MAGIC_COAT, REST, TELEKINESIS, ROCK_SLIDE, ROCK_TOMB, ROCK_POLISH, STEALTH_ROCK, GYRO_BALL, IRON_DEFENSE, RAIN_DANCE, ENDURE, MEGA_KICK, HEAVY_SLAM, SELF_DESTRUCT, MEGA_PUNCH, SCORCHING_SANDS, DIG, IMPRISON, POLTERGEIST, PHANTOM_FORCE
	; end