	db GOLISOPOD ; 768

	db  75,  125,  140,  40,  60,  90
  ;  hp  atk  def  spd sat sdf

	db BUG, WATER ; type
	db 45 ; catch rate
	db 186 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/golisopod/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_BUG, EGG_WATER3 ; egg groups

	; tm/hm learnset
	tmhm LEECH_LIFE, X_SCISSOR, BUG_BITE, DARK_PULSE, THROAT_CHOP, KNOCK_OFF, SNARL, PAYBACK, FLING, TAUNT, DUAL_CHOP, FOCUS_BLAST, BRICK_BREAK, BULK_UP, AERIAL_ACE, SHADOW_CLAW, SPITE, DRILL_RUN, BLIZZARD, ICE_BEAM, FROST_BREATH, ICY_WIND, HAIL, GIGA_IMPACT, HYPER_BEAM, FACADE, HIDDEN_POWER, ROUND, SNORE, FALSE_SWIPE, ENDEAVOR, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, LASER_FOCUS, PAIN_SPLIT, PROTECT, PSYCH_UP, SLEEP_TALK, SUBSTITUTE, SWAGGER, SWORDS_DANCE, SLUDGE_WAVE, SLUDGE_BOMB, POISON_JAB, VENOSHOCK, TOXIC, REST, ROCK_SLIDE, ROCK_TOMB, IRON_HEAD, IRON_DEFENSE, SURF, LIQUIDATION, DIVE, SCALD, WATERFALL, WATER_PULSE, RAIN_DANCE, ENDURE, SCREECH, SWIFT, ASSURANCE, MUD_SHOT, MUDDY_WATER, BUG_BUZZ, SKITTER_SMACK, RAZOR_SHELL, SPIKES, CLOSE_COMBAT, PIN_MISSILE
	; end