	db GRENINJA ; 658

	db  72,  95,  67,  122,  103,  71
  ;  hp  atk  def  spd sat sdf

	db WATER, DARK ; type
	db 45 ; catch rate
	db 239 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F12_5 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/greninja/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_SLOW ; growth rate
	dn EGG_WATER1, EGG_WATER1 ; egg groups

	; tm/hm learnset
	tmhm U_TURN, DARK_PULSE, BRUTAL_SWING, THIEF, FLING, SNATCH, TAUNT, POWER_UP_PUNCH, ROCK_SMASH, LOW_KICK, BOUNCE, AERIAL_ACE, ACROBATICS, SPITE, GRASS_KNOT, BLIZZARD, ICE_BEAM, ICE_PUNCH, ICY_WIND, GIGA_IMPACT, HYPER_BEAM, STRENGTH, FACADE, HIDDEN_POWER, ROUND, CUT, SNORE, ECHOED_VOICE, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, PROTECT, SLEEP_TALK, SUBSTITUTE, SWAGGER, WORK_UP, GUNK_SHOT, TOXIC, REST, ROLE_PLAY, ROCK_SLIDE, ROCK_TOMB, SMACK_DOWN, HYDRO_CANNON, SURF, DIVE, SCALD, WATER_PLEDGE, WATERFALL, WATER_PULSE, RAIN_DANCE, ENDURE, DIG
	; end