	db GRIMMSNARL ; 861

	db  95,  120,  65,  60,  95,  75
  ;  hp  atk  def  spd sat sdf

	db DARK, FAIRY ; type
	db 45 ; catch rate
	db 255 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F0 ; gender ratio
	db 100 ; unknown 1
	db 21 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/grimmsnarl/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_FAIRY, EGG_HUMANLIKE ; egg groups

	; tm/hm learnset
	tmhm LEECH_LIFE, FOUL_PLAY, DARK_PULSE, THROAT_CHOP, THIEF, TAUNT, THUNDER_PUNCH, THUNDER_WAVE, DAZZLING_GLEAM, FOCUS_BLAST, SUPERPOWER, BRICK_BREAK, DRAIN_PUNCH, LOW_SWEEP, LOW_KICK, BULK_UP, FIRE_PUNCH, SHADOW_CLAW, STOMPING_TANTRUM, ICE_PUNCH, GIGA_IMPACT, HYPER_BEAM, UPROAR, FACADE, ROUND, SNORE, ATTRACT, PROTECT, SLEEP_TALK, SUBSTITUTE, LIGHT_SCREEN, REFLECT, REST, TRICK, WONDER_ROOM, ENDURE, MEGA_KICK, BODY_SLAM, DARKEST_LARIAT, BODY_PRESS, MEGA_PUNCH, FOCUS_ENERGY, ASSURANCE, SCARY_FACE, REVENGE, METRONOME, CRUNCH, NASTY_PLOT, RETALIATE, FAKE_TEARS, POWER_SWAP, PLAY_ROUGH, LASH_OUT, BURNING_JEALOUSY, POWER_WHIP, DRAINING_KISS
	; end