	db GUZZLORD ; 799

	db  223,  101,  53,  43,  97,  53
  ;  hp  atk  def  spd sat sdf

	db DARK, DRAGON ; type
	db 45 ; catch rate
	db 257 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_UNKNOWN ; gender ratio
	db 100 ; unknown 1
	db 120 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/guzzlord/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_SLOW ; growth rate
	dn EGG_NONE, EGG_NONE ; egg groups

	; tm/hm learnset
	tmhm DARK_PULSE, KNOCK_OFF, BRUTAL_SWING, THIEF, SNARL, PAYBACK, FLING, DRACO_METEOR, OUTRAGE, DRAGON_PULSE, DRAGON_CLAW, DRAGON_TAIL, DUAL_CHOP, SHOCK_WAVE, MAGNET_RISE, BRICK_BREAK, DRAIN_PUNCH, FIRE_BLAST, HEAT_WAVE, FLAMETHROWER, SHADOW_CLAW, EARTHQUAKE, STOMPING_TANTRUM, BULLDOZE, GIGA_IMPACT, HYPER_BEAM, LAST_RESORT, FACADE, HIDDEN_POWER, ROUND, SNORE, FRUSTRATION, RETURN, DOUBLE_TEAM, PROTECT, SLEEP_TALK, SUBSTITUTE, SLUDGE_WAVE, SLUDGE_BOMB, POISON_JAB, GASTRO_ACID, TOXIC, REST, STONE_EDGE, ROCK_SLIDE, ROCK_TOMB, SMACK_DOWN, IRON_TAIL, IRON_HEAD, GYRO_BALL, IRON_DEFENSE, ENDURE, MEGA_KICK, BODY_SLAM, HEAVY_SLAM, STEEL_ROLLER, BODY_PRESS, MEGA_PUNCH, HIGH_HORSEPOWER, CRUNCH, AMNESIA, LASH_OUT, HEAT_CRASH, CORROSIVE_GAS
	; end