	db HAPPINY ; 440

	db  100,  5,  5,  30,  15,  65
  ;  hp  atk  def  spd sat sdf

	db NORMAL, NORMAL ; type
	db 130 ; catch rate
	db 110 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F100 ; gender ratio
	db 100 ; unknown 1
	db 40 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/happiny/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_FAST ; growth rate
	dn EGG_NONE, EGG_NONE ; egg groups

	; tm/hm learnset
	tmhm FLING, SHOCK_WAVE, THUNDER_WAVE, DRAIN_PUNCH, FIRE_BLAST, FLAMETHROWER, SUNNY_DAY, SHADOW_BALL, SOLAR_BEAM, GRASS_KNOT, ICY_WIND, HAIL, LAST_RESORT, HYPER_VOICE, UPROAR, FACADE, COVET, HIDDEN_POWER, ROUND, SNORE, ECHOED_VOICE, ENDEAVOR, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, HEAL_BELL, HELPING_HAND, PROTECT, PSYCH_UP, RECYCLE, SAFEGUARD, SLEEP_TALK, SUBSTITUTE, SWAGGER, WORK_UP, TOXIC, DREAM_EATER, PSYCHIC, ZEN_HEADBUTT, GRAVITY, LIGHT_SCREEN, REST, WATER_PULSE, RAIN_DANCE, ENDURE, METRONOME, STORED_POWER, CHARM
	; end