	db HATTERENE ; 858

	db  57,  90,  95,  29,  136,  103
  ;  hp  atk  def  spd sat sdf

	db PSYCHIC, FAIRY ; type
	db 45 ; catch rate
	db 255 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F100 ; gender ratio
	db 100 ; unknown 1
	db 21 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/hatterene/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_SLOW ; growth rate
	dn EGG_FAIRY, EGG_FAIRY ; egg groups

	; tm/hm learnset
	tmhm DARK_PULSE, BRUTAL_SWING, THUNDER_WAVE, DAZZLING_GLEAM, SHADOW_BALL, SHADOW_CLAW, GIGA_DRAIN, GIGA_IMPACT, HYPER_BEAM, FACADE, ROUND, SNORE, ATTRACT, HELPING_HAND, PROTECT, SAFEGUARD, SLEEP_TALK, SUBSTITUTE, SWORDS_DANCE, PSYCHIC, PSYSHOCK, CALM_MIND, LIGHT_SCREEN, MAGIC_ROOM, REST, SKILL_SWAP, TRICK_ROOM, WONDER_ROOM, ENDURE, MAGICAL_LEAF, BATON_PASS, EXPANDING_FORCE, STORED_POWER, GUARD_SWAP, POWER_SWAP, FUTURE_SIGHT, IMPRISON, PSYCHO_CUT, PLAY_ROUGH, CHARM, POWER_WHIP, MYSTICAL_FIRE, DRAINING_KISS, MISTY_EXPLOSION
	; end