	db HAXORUS ; 612

	db  76,  147,  90,  97,  60,  70
  ;  hp  atk  def  spd sat sdf

	db DRAGON, DRAGON ; type
	db 45 ; catch rate
	db 243 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 40 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/haxorus/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_SLOW ; growth rate
	dn EGG_MONSTER, EGG_DRAGON ; egg groups

	; tm/hm learnset
	tmhm X_SCISSOR, BRUTAL_SWING, SNARL, PAYBACK, FLING, TAUNT, DRACO_METEOR, OUTRAGE, DRAGON_PULSE, DRAGON_CLAW, DRAGON_TAIL, DUAL_CHOP, SHOCK_WAVE, FOCUS_BLAST, SUPERPOWER, BRICK_BREAK, ROCK_SMASH, LOW_KICK, SUNNY_DAY, AERIAL_ACE, SHADOW_CLAW, GRASS_KNOT, EARTHQUAKE, STOMPING_TANTRUM, BULLDOZE, GIGA_IMPACT, HYPER_BEAM, STRENGTH, FACADE, HIDDEN_POWER, ROUND, CUT, SNORE, FALSE_SWIPE, ENDEAVOR, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, LASER_FOCUS, PROTECT, ROAR, SLEEP_TALK, SUBSTITUTE, SWAGGER, SWORDS_DANCE, POISON_JAB, TOXIC, REST, ROCK_SLIDE, ROCK_TOMB, IRON_TAIL, AQUA_TAIL, SURF, RAIN_DANCE, ENDURE, FOCUS_ENERGY, SWIFT, ASSURANCE, SCARY_FACE, REVERSAL, BREAKING_SWIPE, SCALE_SHOT, CRUNCH, DIG, PSYCHO_CUT, DRAGON_DANCE, CLOSE_COMBAT
	; end