	db HEATMOR ; 631

	db  85,  97,  66,  65,  105,  66
  ;  hp  atk  def  spd sat sdf

	db FIRE, FIRE ; type
	db 90 ; catch rate
	db 169 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/heatmor/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_FIELD, EGG_FIELD ; egg groups

	; tm/hm learnset
	tmhm BUG_BITE, THROAT_CHOP, KNOCK_OFF, BRUTAL_SWING, THIEF, FLING, SNATCH, TAUNT, THUNDER_PUNCH, FOCUS_PUNCH, FOCUS_BLAST, SUPERPOWER, DRAIN_PUNCH, POWER_UP_PUNCH, ROCK_SMASH, LOW_KICK, OVERHEAT, FIRE_BLAST, HEAT_WAVE, FLAMETHROWER, FIRE_PUNCH, SUNNY_DAY, WILL_O_WISP, AERIAL_ACE, SHADOW_CLAW, SOLAR_BEAM, GIGA_DRAIN, STOMPING_TANTRUM, GIGA_IMPACT, FACADE, HIDDEN_POWER, ROUND, CUT, SNORE, BIND, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, PROTECT, RECYCLE, SLEEP_TALK, SUBSTITUTE, SWAGGER, GASTRO_ACID, TOXIC, REST, ROCK_TOMB, RAIN_DANCE, ENDURE, BODY_SLAM, FLARE_BLITZ, SCORCHING_SANDS, FIRE_SPIN, DIG, AMNESIA, BURNING_JEALOUSY
	; end