	db HELIOPTILE ; 694

	db  44,  38,  33,  70,  61,  43
  ;  hp  atk  def  spd sat sdf

	db ELECTRIC, NORMAL ; type
	db 90 ; catch rate
	db 58 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/helioptile/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_MONSTER, EGG_DRAGON ; egg groups

	; tm/hm learnset
	tmhm SIGNAL_BEAM, U_TURN, DARK_PULSE, DRAGON_TAIL, THUNDER, THUNDERBOLT, WILD_CHARGE, VOLT_SWITCH, SHOCK_WAVE, ELECTROWEB, CHARGE_BEAM, MAGNET_RISE, THUNDER_WAVE, LOW_SWEEP, GRASS_KNOT, BULLDOZE, FACADE, HIDDEN_POWER, ROUND, CUT, SNORE, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, PROTECT, PSYCH_UP, SLEEP_TALK, SUBSTITUTE, SWAGGER, TOXIC, ALLY_SWITCH, LIGHT_SCREEN, REST, ROCK_SLIDE, ROCK_TOMB, SANDSTORM, IRON_TAIL, SURF, RAIN_DANCE, ENDURE, ELECTRIC_TERRAIN, SWIFT, AGILITY, ELECTRO_BALL, SCALE_SHOT, DIG, RISING_VOLTAGE
	; end