	db INCINEROAR ; 727

	db  95,  115,  90,  60,  80,  90
  ;  hp  atk  def  spd sat sdf

	db FIRE, DARK ; type
	db 45 ; catch rate
	db 239 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F12_5 ; gender ratio
	db 100 ; unknown 1
	db 16 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/incineroar/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_SLOW ; growth rate
	dn EGG_FIELD, EGG_FIELD ; egg groups

	; tm/hm learnset
	tmhm LEECH_LIFE, U_TURN, DARK_PULSE, THROAT_CHOP, KNOCK_OFF, BRUTAL_SWING, SNARL, FLING, EMBARGO, QUASH, SNATCH, TAUNT, TORMENT, OUTRAGE, DUAL_CHOP, THUNDER_PUNCH, FOCUS_PUNCH, FOCUS_BLAST, SUPERPOWER, BRICK_BREAK, DRAIN_PUNCH, LOW_SWEEP, LOW_KICK, BULK_UP, BLAST_BURN, OVERHEAT, FIRE_BLAST, HEAT_WAVE, FLAMETHROWER, FIRE_PLEDGE, FIRE_PUNCH, FLAME_CHARGE, SUNNY_DAY, WILL_O_WISP, ACROBATICS, SHADOW_CLAW, EARTHQUAKE, STOMPING_TANTRUM, BULLDOZE, GIGA_IMPACT, HYPER_BEAM, FACADE, COVET, HIDDEN_POWER, ROUND, SNORE, BIND, ENDEAVOR, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, PROTECT, ROAR, SLEEP_TALK, SUBSTITUTE, SWAGGER, SWORDS_DANCE, WORK_UP, TOXIC, REST, IRON_HEAD, ENDURE, MEGA_KICK, BODY_SLAM, DARKEST_LARIAT, MEGA_PUNCH, ASSURANCE, SCARY_FACE, REVERSAL, BLAZE_KICK, FIRE_FANG, FLARE_BLITZ, SCORCHING_SANDS, FIRE_SPIN, REVENGE, CRUNCH, NASTY_PLOT, LASH_OUT, BURNING_JEALOUSY, HEAT_CRASH, CLOSE_COMBAT, PAY_DAY
	; end