	db INFERNAPE ; 392

	db  76,  104,  71,  108,  104,  71
  ;  hp  atk  def  spd sat sdf

	db FIRE, FIGHTING ; type
	db 45 ; catch rate
	db 240 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F12_5 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/infernape/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_SLOW ; growth rate
	dn EGG_FIELD, EGG_HUMANLIKE ; egg groups

	; tm/hm learnset
	tmhm U_TURN, FLING, TAUNT, TORMENT, DUAL_CHOP, THUNDER_PUNCH, FOCUS_PUNCH, FOCUS_BLAST, BRICK_BREAK, LOW_SWEEP, POWER_UP_PUNCH, ROCK_SMASH, LOW_KICK, BULK_UP, BLAST_BURN, OVERHEAT, FIRE_BLAST, HEAT_WAVE, FLAMETHROWER, FIRE_PLEDGE, FIRE_PUNCH, FLAME_CHARGE, SUNNY_DAY, WILL_O_WISP, AERIAL_ACE, ACROBATICS, SHADOW_CLAW, SOLAR_BEAM, GRASS_KNOT, EARTHQUAKE, BULLDOZE, GIGA_IMPACT, HYPER_BEAM, STRENGTH, FACADE, COVET, HIDDEN_POWER, ROUND, CUT, SNORE, ENDEAVOR, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, HELPING_HAND, LASER_FOCUS, PROTECT, ROAR, SLEEP_TALK, SUBSTITUTE, SWAGGER, SWORDS_DANCE, WORK_UP, GUNK_SHOT, POISON_JAB, TOXIC, CALM_MIND, REST, ROLE_PLAY, STONE_EDGE, ROCK_SLIDE, ROCK_TOMB, STEALTH_ROCK, IRON_TAIL, ENDURE, SWIFT, DIG, RETALIATE
	; end