	db JELLICENT ; 593

	db  100,  60,  70,  60,  85,  105
  ;  hp  atk  def  spd sat sdf

	db WATER, GHOST ; type
	db 60 ; catch rate
	db 168 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/jellicent/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_AMORPHOUS, EGG_AMORPHOUS ; egg groups

	; tm/hm learnset
	tmhm DARK_PULSE, TAUNT, SHOCK_WAVE, DAZZLING_GLEAM, WILL_O_WISP, SHADOW_BALL, SPITE, ENERGY_BALL, GIGA_DRAIN, BLIZZARD, ICE_BEAM, ICY_WIND, HAIL, GIGA_IMPACT, HYPER_BEAM, FACADE, HIDDEN_POWER, ROUND, SNORE, BIND, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, PAIN_SPLIT, PROTECT, PSYCH_UP, SAFEGUARD, SLEEP_TALK, SUBSTITUTE, SWAGGER, SLUDGE_WAVE, SLUDGE_BOMB, TOXIC, DREAM_EATER, PSYCHIC, MAGIC_COAT, REST, TRICK, TRICK_ROOM, SURF, DIVE, SCALD, WATERFALL, WATER_PULSE, RAIN_DANCE, ENDURE, MUDDY_WATER, WHIRLPOOL, HYDRO_PUMP, IMPRISON, HEX, BRINE, POLTERGEIST
	; end