	db KINGLER ; 99

	db  55,  130,  115,  75,  50,  50
  ;  hp  atk  def  spd sat sdf

	db WATER, WATER ; type
	db 60 ; catch rate
	db 166 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/kingler/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_WATER3, EGG_WATER3 ; egg groups

	; tm/hm learnset
	tmhm X_SCISSOR, KNOCK_OFF, BRUTAL_SWING, THIEF, FLING, QUASH, SUPERPOWER, BRICK_BREAK, ROCK_SMASH, STOMPING_TANTRUM, BLIZZARD, ICE_BEAM, ICY_WIND, HAIL, GIGA_IMPACT, HYPER_BEAM, STRENGTH, FACADE, HIDDEN_POWER, ROUND, CUT, SNORE, FALSE_SWIPE, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, PROTECT, SLEEP_TALK, SUBSTITUTE, SWAGGER, SWORDS_DANCE, TOXIC, ALLY_SWITCH, REST, ROCK_SLIDE, ROCK_TOMB, IRON_DEFENSE, SURF, LIQUIDATION, DIVE, SCALD, WATER_PULSE, RAIN_DANCE, ENDURE, BODY_SLAM, HIGH_HORSEPOWER, MUD_SHOT, AGILITY, WHIRLPOOL, HYDRO_PUMP, DIG, AMNESIA, RAZOR_SHELL, BRINE
	; end