	db KINGDRA ; 230

	db  75,  95,  95,  85,  95,  95
  ;  hp  atk  def  spd sat sdf

	db WATER, DRAGON ; type
	db 45 ; catch rate
	db 243 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/kingdra/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_WATER1, EGG_DRAGON ; egg groups

	; tm/hm learnset
	tmhm SIGNAL_BEAM, QUASH, DRACO_METEOR, OUTRAGE, DRAGON_PULSE, BOUNCE, BLIZZARD, ICE_BEAM, ICY_WIND, HAIL, GIGA_IMPACT, HYPER_BEAM, FACADE, HIDDEN_POWER, ROUND, SNORE, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, LASER_FOCUS, PROTECT, SLEEP_TALK, SUBSTITUTE, SWAGGER, TOXIC, REST, FLASH_CANNON, IRON_HEAD, SURF, LIQUIDATION, DIVE, SCALD, WATERFALL, WATER_PULSE, RAIN_DANCE, ENDURE, BODY_SLAM, FOCUS_ENERGY, SWIFT, AGILITY, MUDDY_WATER, WHIRLPOOL, HYDRO_PUMP, BREAKING_SWIPE, SCALE_SHOT, HURRICANE, DRAGON_DANCE, FLIP_TURN, BRINE
	; end