	db KLEFKI ; 707

	db  57,  80,  91,  75,  80,  87
  ;  hp  atk  def  spd sat sdf

	db STEEL, FAIRY ; type
	db 60 ; catch rate
	db 165 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/klefki/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_FAST ; growth rate
	dn EGG_MINERAL, EGG_MINERAL ; egg groups

	; tm/hm learnset
	tmhm FOUL_PLAY, THIEF, TORMENT, MAGNET_RISE, THUNDER_WAVE, DAZZLING_GLEAM, SUNNY_DAY, DEFOG, GIGA_IMPACT, HYPER_BEAM, LAST_RESORT, FACADE, COVET, HIDDEN_POWER, ROUND, CUT, SNORE, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, PROTECT, PSYCH_UP, RECYCLE, SAFEGUARD, SLEEP_TALK, SUBSTITUTE, SWAGGER, TOXIC, PSYCHIC, PSYSHOCK, CALM_MIND, LIGHT_SCREEN, MAGIC_COAT, MAGIC_ROOM, REFLECT, REST, FLASH_CANNON, IRON_DEFENSE, RAIN_DANCE, ENDURE, STEEL_BEAM, STORED_POWER, IMPRISON, PLAY_ROUGH, SPIKES, DRAINING_KISS, MISTY_TERRAIN
	; end