	db KLINKLANG ; 601

	db  60,  100,  115,  90,  70,  85
  ;  hp  atk  def  spd sat sdf

	db STEEL, STEEL ; type
	db 30 ; catch rate
	db 234 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_UNKNOWN ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/klinklang/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_SLOW ; growth rate
	dn EGG_MINERAL, EGG_MINERAL ; egg groups

	; tm/hm learnset
	tmhm SIGNAL_BEAM, THUNDER, THUNDERBOLT, WILD_CHARGE, VOLT_SWITCH, SHOCK_WAVE, CHARGE_BEAM, MAGNET_RISE, THUNDER_WAVE, ROCK_SMASH, GIGA_IMPACT, HYPER_BEAM, UPROAR, FACADE, HIDDEN_POWER, ROUND, SNORE, BIND, FRUSTRATION, RETURN, CONFIDE, DOUBLE_TEAM, PROTECT, RECYCLE, SLEEP_TALK, SUBSTITUTE, SWAGGER, TOXIC, ALLY_SWITCH, GRAVITY, MAGIC_COAT, REST, TELEKINESIS, TRICK_ROOM, ROCK_POLISH, SANDSTORM, FLASH_CANNON, IRON_DEFENSE, ENDURE, STEEL_BEAM, ELECTRIC_TERRAIN, STEEL_ROLLER, SCREECH, ASSURANCE, RISING_VOLTAGE, POWER_GEM
	; end