	db KOFFING ; 109

	db  40,  65,  95,  35,  60,  45
  ;  hp  atk  def  spd sat sdf

	db POISON, POISON ; type
	db 190 ; catch rate
	db 68 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/koffing/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_AMORPHOUS, EGG_AMORPHOUS ; egg groups

	; tm/hm learnset
	tmhm INFESTATION, DARK_PULSE, THIEF, PAYBACK, TAUNT, TORMENT, THUNDER, THUNDERBOLT, SHOCK_WAVE, FIRE_BLAST, FLAMETHROWER, SUNNY_DAY, WILL_O_WISP, SHADOW_BALL, SPITE, EXPLOSION, UPROAR, FACADE, HIDDEN_POWER, ROUND, SNORE, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, PAIN_SPLIT, PROTECT, SLEEP_TALK, SUBSTITUTE, SWAGGER, SLUDGE_WAVE, SLUDGE_BOMB, VENOSHOCK, TOXIC, REST, GYRO_BALL, RAIN_DANCE, ENDURE, SELF_DESTRUCT, SCREECH, ASSURANCE, VENOM_DRENCH, TOXIC_SPIKES, CORROSIVE_GAS
	; end