	db KROOKODILE ; 553

	db  95,  117,  80,  92,  65,  70
  ;  hp  atk  def  spd sat sdf

	db GROUND, DARK ; type
	db 45 ; catch rate
	db 234 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/krookodile/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_SLOW ; growth rate
	dn EGG_FIELD, EGG_FIELD ; egg groups

	; tm/hm learnset
	tmhm FOUL_PLAY, DARK_PULSE, THROAT_CHOP, KNOCK_OFF, BRUTAL_SWING, THIEF, SNARL, PAYBACK, FLING, EMBARGO, SNATCH, TAUNT, TORMENT, OUTRAGE, DRAGON_PULSE, DRAGON_CLAW, DRAGON_TAIL, FOCUS_PUNCH, FOCUS_BLAST, SUPERPOWER, BRICK_BREAK, LOW_SWEEP, POWER_UP_PUNCH, ROCK_SMASH, LOW_KICK, BULK_UP, AERIAL_ACE, SHADOW_CLAW, SPITE, GRASS_KNOT, EARTHQUAKE, EARTH_POWER, STOMPING_TANTRUM, BULLDOZE, GIGA_IMPACT, HYPER_BEAM, UPROAR, STRENGTH, FACADE, HIDDEN_POWER, ROUND, CUT, SNORE, FRUSTRATION, RETURN, ATTRACT, BLOCK, CONFIDE, DOUBLE_TEAM, PROTECT, ROAR, SLEEP_TALK, SUBSTITUTE, SWAGGER, SLUDGE_BOMB, TOXIC, REST, STONE_EDGE, ROCK_SLIDE, ROCK_TOMB, SMACK_DOWN, SANDSTORM, STEALTH_ROCK, IRON_TAIL, AQUA_TAIL, ENDURE, MEGA_KICK, BODY_SLAM, DARKEST_LARIAT, MEGA_PUNCH, HIGH_HORSEPOWER, FOCUS_ENERGY, SCARY_FACE, FIRE_FANG, SCORCHING_SANDS, REVENGE, SCALE_SHOT, CRUNCH, DIG, THUNDER_FANG, RETALIATE, BEAT_UP, LASH_OUT, SKITTER_SMACK, SAND_TOMB, CLOSE_COMBAT
	; end