	db KYUREM ; 646

	db  125,  130,  90,  95,  130,  90
  ;  hp  atk  def  spd sat sdf

	db DRAGON, ICE ; type
	db 3 ; catch rate
	db 297 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_UNKNOWN ; gender ratio
	db 100 ; unknown 1
	db 120 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/kyurem/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_SLOW ; growth rate
	dn EGG_NONE, EGG_NONE ; egg groups

	; tm/hm learnset
	tmhm SIGNAL_BEAM, BRUTAL_SWING, PAYBACK, FLING, DRACO_METEOR, OUTRAGE, DRAGON_PULSE, DRAGON_CLAW, DRAGON_TAIL, FOCUS_BLAST, ROCK_SMASH, SUNNY_DAY, FLY, ROOST, SHADOW_BALL, SHADOW_CLAW, EARTH_POWER, BLIZZARD, ICE_BEAM, ICY_WIND, HAIL, GIGA_IMPACT, HYPER_BEAM, HYPER_VOICE, STRENGTH, FACADE, HIDDEN_POWER, ROUND, CUT, SNORE, ECHOED_VOICE, ENDEAVOR, FRUSTRATION, RETURN, CONFIDE, DOUBLE_TEAM, HELPING_HAND, LASER_FOCUS, PROTECT, SAFEGUARD, SLEEP_TALK, SUBSTITUTE, SWAGGER, TOXIC, PSYCHIC, ZEN_HEADBUTT, LIGHT_SCREEN, REFLECT, REST, STONE_EDGE, ROCK_SLIDE, ROCK_TOMB, FLASH_CANNON, IRON_HEAD, STEEL_WING, RAIN_DANCE, ENDURE, BODY_PRESS, SWIFT, SCARY_FACE, WEATHER_BALL, BREAKING_SWIPE, ICICLE_SPEAR, SCALE_SHOT, DUAL_WINGBEAT, IMPRISON, DRAGON_DANCE
	; end