	db LAPRAS ; 131

	db  130,  85,  80,  60,  85,  95
  ;  hp  atk  def  spd sat sdf

	db WATER, ICE ; type
	db 45 ; catch rate
	db 187 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 40 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/lapras/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_SLOW ; growth rate
	dn EGG_MONSTER, EGG_WATER1 ; egg groups

	; tm/hm learnset
	tmhm SIGNAL_BEAM, OUTRAGE, DRAGON_PULSE, THUNDER, THUNDERBOLT, SHOCK_WAVE, ROCK_SMASH, SOLAR_BEAM, DRILL_RUN, BULLDOZE, BLIZZARD, ICE_BEAM, FROST_BREATH, ICY_WIND, HAIL, GIGA_IMPACT, HYPER_BEAM, HYPER_VOICE, STRENGTH, FACADE, HIDDEN_POWER, ROUND, SNORE, ECHOED_VOICE, FRUSTRATION, RETURN, ATTRACT, BLOCK, CONFIDE, DOUBLE_TEAM, HEAL_BELL, HELPING_HAND, PROTECT, ROAR, SAFEGUARD, SLEEP_TALK, SUBSTITUTE, SWAGGER, TOXIC, DREAM_EATER, PSYCHIC, ZEN_HEADBUTT, REFLECT, REST, IRON_TAIL, IRON_HEAD, SMART_STRIKE, AQUA_TAIL, SURF, LIQUIDATION, DIVE, WATERFALL, WATER_PULSE, RAIN_DANCE, ENDURE, BODY_SLAM, BODY_PRESS, WHIRLPOOL, WEATHER_BALL, HYDRO_PUMP, FUTURE_SIGHT, CHARM, MEGAHORN, DRAGON_DANCE, BRINE, AVALANCHE
	; end