	db LIEPARD ; 510

	db  64,  88,  50,  106,  88,  50
  ;  hp  atk  def  spd sat sdf

	db DARK, DARK ; type
	db 90 ; catch rate
	db 156 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/liepard/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_FIELD, EGG_FIELD ; egg groups

	; tm/hm learnset
	tmhm U_TURN, FOUL_PLAY, DARK_PULSE, THROAT_CHOP, KNOCK_OFF, THIEF, SNARL, PAYBACK, EMBARGO, SNATCH, TAUNT, TORMENT, THUNDER_WAVE, ROCK_SMASH, SUNNY_DAY, AERIAL_ACE, SHADOW_BALL, SHADOW_CLAW, SPITE, SEED_BOMB, GRASS_KNOT, GIGA_IMPACT, HYPER_BEAM, HYPER_VOICE, FACADE, COVET, HIDDEN_POWER, ROUND, CUT, SNORE, ECHOED_VOICE, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, LASER_FOCUS, PROTECT, PSYCH_UP, SLEEP_TALK, SUBSTITUTE, SWAGGER, GUNK_SHOT, TOXIC, DREAM_EATER, REST, ROLE_PLAY, TRICK, IRON_TAIL, RAIN_DANCE, ENDURE, SCREECH, SWIFT, ASSURANCE, BATON_PASS, NASTY_PLOT, FAKE_TEARS, PSYCHO_CUT, PLAY_ROUGH, LASH_OUT, BURNING_JEALOUSY, CHARM, SKITTER_SMACK, ENCORE, PAY_DAY
	; end