	db LOPUNNY ; 428

	db  65,  76,  84,  105,  54,  96
  ;  hp  atk  def  spd sat sdf

	db NORMAL, NORMAL ; type
	db 60 ; catch rate
	db 168 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/lopunny/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_FIELD, EGG_HUMANLIKE ; egg groups

	; tm/hm learnset
	tmhm U_TURN, BRUTAL_SWING, PAYBACK, FLING, THUNDER, THUNDERBOLT, THUNDER_PUNCH, SHOCK_WAVE, CHARGE_BEAM, THUNDER_WAVE, FOCUS_PUNCH, FOCUS_BLAST, DRAIN_PUNCH, LOW_SWEEP, POWER_UP_PUNCH, ROCK_SMASH, LOW_KICK, FIRE_PUNCH, SUNNY_DAY, BOUNCE, ACROBATICS, SHADOW_BALL, SOLAR_BEAM, GRASS_KNOT, BLIZZARD, ICE_BEAM, ICE_PUNCH, GIGA_IMPACT, HYPER_BEAM, LAST_RESORT, HYPER_VOICE, UPROAR, STRENGTH, FACADE, COVET, HIDDEN_POWER, ROUND, CUT, SNORE, ENDEAVOR, FRUSTRATION, RETURN, AFTER_YOU, ATTRACT, CONFIDE, DOUBLE_TEAM, HEAL_BELL, HELPING_HAND, LASER_FOCUS, PROTECT, SLEEP_TALK, SUBSTITUTE, SWAGGER, WORK_UP, TOXIC, MAGIC_COAT, REST, IRON_TAIL, WATER_PULSE, RAIN_DANCE, ENDURE, MEGA_KICK, MEGA_PUNCH, SWIFT, AGILITY, REVERSAL, BATON_PASS, DIG, RETALIATE, FAKE_TEARS, PLAY_ROUGH, CHARM, CLOSE_COMBAT, ENCORE, TRIPLE_AXEL, COSMIC_POWER, AURA_SPHERE
	; end