	db LUCARIO ; 448

	db  70,  110,  70,  90,  115,  70
  ;  hp  atk  def  spd sat sdf

	db FIGHTING, STEEL ; type
	db 45 ; catch rate
	db 184 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F12_5 ; gender ratio
	db 100 ; unknown 1
	db 25 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/lucario/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_SLOW ; growth rate
	dn EGG_FIELD, EGG_HUMANLIKE ; egg groups

	; tm/hm learnset
	tmhm DARK_PULSE, PAYBACK, FLING, DRAGON_PULSE, DUAL_CHOP, THUNDER_PUNCH, MAGNET_RISE, FOCUS_PUNCH, FOCUS_BLAST, BRICK_BREAK, DRAIN_PUNCH, LOW_SWEEP, POWER_UP_PUNCH, ROCK_SMASH, LOW_KICK, BULK_UP, SUNNY_DAY, SHADOW_BALL, SHADOW_CLAW, EARTHQUAKE, BULLDOZE, ICE_PUNCH, GIGA_IMPACT, HYPER_BEAM, STRENGTH, FACADE, HIDDEN_POWER, ROUND, SNORE, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, HELPING_HAND, LASER_FOCUS, PROTECT, ROAR, SLEEP_TALK, SUBSTITUTE, SWAGGER, SWORDS_DANCE, WORK_UP, POISON_JAB, TOXIC, PSYCHIC, ZEN_HEADBUTT, CALM_MIND, REST, ROLE_PLAY, STONE_EDGE, ROCK_SLIDE, ROCK_TOMB, IRON_TAIL, FLASH_CANNON, IRON_DEFENSE, WATER_PULSE, RAIN_DANCE, ENDURE, STEEL_BEAM, MEGA_KICK, MEGA_PUNCH, SCREECH, FOCUS_ENERGY, SWIFT, SCARY_FACE, AGILITY, REVERSAL, BLAZE_KICK, COACHING, REVENGE, CRUNCH, DIG, NASTY_PLOT, RETALIATE, CLOSE_COMBAT, TERRAIN_PULSE, AURA_SPHERE
	; end