	db LUNATONE ; 337

	db  90,  55,  65,  70,  95,  85
  ;  hp  atk  def  spd sat sdf

	db ROCK, PSYCHIC ; type
	db 45 ; catch rate
	db 161 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_UNKNOWN ; gender ratio
	db 100 ; unknown 1
	db 25 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/lunatone/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_FAST ; growth rate
	dn EGG_MINERAL, EGG_MINERAL ; egg groups

	; tm/hm learnset
	tmhm SIGNAL_BEAM, EMBARGO, CHARGE_BEAM, ACROBATICS, SHADOW_BALL, GRASS_KNOT, EARTHQUAKE, EARTH_POWER, STOMPING_TANTRUM, BULLDOZE, BLIZZARD, ICE_BEAM, ICY_WIND, HAIL, EXPLOSION, GIGA_IMPACT, HYPER_BEAM, FACADE, HIDDEN_POWER, ROUND, SNORE, FRUSTRATION, RETURN, CONFIDE, DOUBLE_TEAM, HELPING_HAND, LASER_FOCUS, PAIN_SPLIT, PROTECT, PSYCH_UP, RECYCLE, SAFEGUARD, SLEEP_TALK, SUBSTITUTE, SWAGGER, TOXIC, DREAM_EATER, PSYCHIC, PSYSHOCK, ZEN_HEADBUTT, ALLY_SWITCH, CALM_MIND, GRAVITY, LIGHT_SCREEN, MAGIC_COAT, MAGIC_ROOM, REFLECT, REST, SKILL_SWAP, TELEKINESIS, TRICK_ROOM, STONE_EDGE, ROCK_SLIDE, ROCK_TOMB, SMACK_DOWN, ROCK_POLISH, SANDSTORM, STEALTH_ROCK, IRON_HEAD, GYRO_BALL, RAIN_DANCE, ENDURE, BODY_SLAM, SELF_DESTRUCT, SWIFT, BATON_PASS, WEATHER_BALL, NASTY_PLOT, STORED_POWER, POWER_SWAP, PSYCHIC_TERRAIN, FUTURE_SIGHT, SAND_TOMB, METEOR_BEAM, ROCK_BLAST, POWER_GEM, COSMIC_POWER
	; end