	db LUNALA ; 792

	db  137,  113,  89,  97,  137,  107
  ;  hp  atk  def  spd sat sdf

	db PSYCHIC, GHOST ; type
	db 45 ; catch rate
	db 306 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_UNKNOWN ; gender ratio
	db 100 ; unknown 1
	db 120 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/lunala/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_SLOW ; growth rate
	dn EGG_NONE, EGG_NONE ; egg groups

	; tm/hm learnset
	tmhm SIGNAL_BEAM, THUNDER, THUNDERBOLT, SHOCK_WAVE, CHARGE_BEAM, THUNDER_WAVE, DAZZLING_GLEAM, FOCUS_BLAST, HEAT_WAVE, SUNNY_DAY, WILL_O_WISP, SKY_ATTACK, FLY, AERIAL_ACE, SKY_DROP, ACROBATICS, DEFOG, ROOST, TAILWIND, SHADOW_BALL, SHADOW_CLAW, SPITE, SOLAR_BEAM, BLIZZARD, ICE_BEAM, ICY_WIND, GIGA_IMPACT, HYPER_BEAM, FACADE, HIDDEN_POWER, ROUND, SNORE, FRUSTRATION, RETURN, CONFIDE, DOUBLE_TEAM, HELPING_HAND, PROTECT, PSYCH_UP, ROAR, SAFEGUARD, SLEEP_TALK, SUBSTITUTE, SWAGGER, WORK_UP, TOXIC, DREAM_EATER, PSYCHIC, PSYSHOCK, CALM_MIND, LIGHT_SCREEN, MAGIC_COAT, MAGIC_ROOM, REFLECT, REST, TELEKINESIS, TRICK, TRICK_ROOM, WONDER_ROOM, ENDURE, SWIFT, SCARY_FACE, AGILITY, AIR_SLASH, DUAL_WINGBEAT, EXPANDING_FORCE, FUTURE_SIGHT, PSYCHO_CUT, METEOR_BEAM, HEX, POLTERGEIST, PHANTOM_FORCE, COSMIC_POWER
	; end