	db LYCANROC ; 745

	db  75,  115,  65,  112,  55,  65
  ;  hp  atk  def  spd sat sdf

	db ROCK, ROCK ; type
	db 90 ; catch rate
	db 170 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 16 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/lycanroc/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_FIELD, EGG_FIELD ; egg groups

	; tm/hm learnset
	tmhm SNARL, TAUNT, BRICK_BREAK, BULK_UP, EARTH_POWER, DRILL_RUN, STOMPING_TANTRUM, GIGA_IMPACT, LAST_RESORT, HYPER_VOICE, FACADE, COVET, HIDDEN_POWER, ROUND, SNORE, ECHOED_VOICE, ENDEAVOR, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, PROTECT, ROAR, SLEEP_TALK, SUBSTITUTE, SWAGGER, SWORDS_DANCE, TOXIC, ZEN_HEADBUTT, REST, STONE_EDGE, ROCK_SLIDE, ROCK_TOMB, ROCK_POLISH, SANDSTORM, STEALTH_ROCK, IRON_TAIL, IRON_HEAD, IRON_DEFENSE, ENDURE, SCARY_FACE, AGILITY, FIRE_FANG, REVENGE, CRUNCH, TAIL_SLAP, THUNDER_FANG, PSYCHIC_FANGS, PLAY_ROUGH, CLOSE_COMBAT
	; end