	db MALAMAR ; 687

	db  86,  92,  88,  73,  68,  75
  ;  hp  atk  def  spd sat sdf

	db DARK, PSYCHIC ; type
	db 120 ; catch rate
	db 169 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/malamar/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_WATER1, EGG_WATER2 ; egg groups

	; tm/hm learnset
	tmhm SIGNAL_BEAM, FOUL_PLAY, DARK_PULSE, THROAT_CHOP, KNOCK_OFF, BRUTAL_SWING, THIEF, PAYBACK, FLING, EMBARGO, SNATCH, TAUNT, TORMENT, THUNDERBOLT, SUPERPOWER, FLAMETHROWER, SUNNY_DAY, AERIAL_ACE, SPITE, GIGA_IMPACT, HYPER_BEAM, FACADE, HIDDEN_POWER, ROUND, CUT, SNORE, BIND, FRUSTRATION, RETURN, ATTRACT, BLOCK, CONFIDE, DOUBLE_TEAM, PROTECT, PSYCH_UP, SLEEP_TALK, SUBSTITUTE, SWAGGER, TOXIC, PSYCHIC, PSYSHOCK, ALLY_SWITCH, CALM_MIND, LIGHT_SCREEN, REFLECT, REST, ROLE_PLAY, TELEKINESIS, TRICK_ROOM, ROCK_SLIDE, LIQUIDATION, RAIN_DANCE, ENDURE, SCARY_FACE, REVERSAL, BATON_PASS, NASTY_PLOT, RETALIATE, FAKE_TEARS, EXPANDING_FORCE, STORED_POWER, GUARD_SWAP, FUTURE_SIGHT, PSYCHO_CUT, LASH_OUT
	; end