	db MEOWTH ; 52

	db  40,  45,  35,  90,  40,  40
  ;  hp  atk  def  spd sat sdf

	db NORMAL, NORMAL ; type
	db 255 ; catch rate
	db 58 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/meowth/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_FIELD, EGG_FIELD ; egg groups

	; tm/hm learnset
	tmhm U_TURN, FOUL_PLAY, DARK_PULSE, THROAT_CHOP, KNOCK_OFF, THIEF, PAYBACK, SNATCH, TAUNT, TORMENT, THUNDER, THUNDERBOLT, SHOCK_WAVE, SUNNY_DAY, AERIAL_ACE, SHADOW_BALL, SHADOW_CLAW, SPITE, SEED_BOMB, ICY_WIND, LAST_RESORT, HYPER_VOICE, UPROAR, FACADE, COVET, HIDDEN_POWER, ROUND, CUT, SNORE, ECHOED_VOICE, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, PROTECT, PSYCH_UP, SLEEP_TALK, SUBSTITUTE, SWAGGER, WORK_UP, GUNK_SHOT, TOXIC, DREAM_EATER, REST, IRON_TAIL, WATER_PULSE, RAIN_DANCE, ENDURE, BODY_SLAM, SCREECH, SWIFT, ASSURANCE, DIG, AMNESIA, NASTY_PLOT, RETALIATE, PLAY_ROUGH, LASH_OUT, CHARM, PAY_DAY
	; end