	db METANG ; 375

	db  60,  75,  100,  50,  55,  80
  ;  hp  atk  def  spd sat sdf

	db STEEL, PSYCHIC ; type
	db 3 ; catch rate
	db 147 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_UNKNOWN ; gender ratio
	db 100 ; unknown 1
	db 40 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/metang/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_SLOW ; growth rate
	dn EGG_MINERAL, EGG_MINERAL ; egg groups

	; tm/hm learnset
	tmhm SIGNAL_BEAM, THUNDER_PUNCH, MAGNET_RISE, BRICK_BREAK, POWER_UP_PUNCH, ROCK_SMASH, SUNNY_DAY, AERIAL_ACE, SHADOW_BALL, GRASS_KNOT, EARTHQUAKE, BULLDOZE, ICE_PUNCH, ICY_WIND, EXPLOSION, HYPER_BEAM, STRENGTH, FACADE, HIDDEN_POWER, ROUND, CUT, SNORE, FRUSTRATION, RETURN, CONFIDE, DOUBLE_TEAM, PROTECT, PSYCH_UP, SLEEP_TALK, SUBSTITUTE, SWAGGER, SLUDGE_BOMB, TOXIC, PSYCHIC, PSYSHOCK, ZEN_HEADBUTT, ALLY_SWITCH, GRAVITY, LIGHT_SCREEN, REFLECT, REST, TELEKINESIS, TRICK, ROCK_SLIDE, ROCK_TOMB, ROCK_POLISH, SANDSTORM, STEALTH_ROCK, FLASH_CANNON, IRON_HEAD, GYRO_BALL, IRON_DEFENSE, RAIN_DANCE, ENDURE, STEEL_BEAM, BODY_SLAM, SELF_DESTRUCT, STEEL_ROLLER, SWIFT, SCARY_FACE, AGILITY, EXPANDING_FORCE, PSYCHO_CUT, METEOR_BEAM, COSMIC_POWER
	; end