	db MEW ; 151

	db  100,  100,  100,  100,  100,  100
  ;  hp  atk  def  spd sat sdf

	db PSYCHIC, PSYCHIC ; type
	db 45 ; catch rate
	db 270 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_UNKNOWN ; gender ratio
	db 100 ; unknown 1
	db 120 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/mew/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_SLOW ; growth rate
	dn EGG_NONE, EGG_NONE ; egg groups

	; tm/hm learnset
	tmhm LEECH_LIFE, X_SCISSOR, SIGNAL_BEAM, U_TURN, BUG_BITE, STRUGGLE_BUG, INFESTATION, FOUL_PLAY, DARK_PULSE, THROAT_CHOP, KNOCK_OFF, BRUTAL_SWING, THIEF, SNARL, PAYBACK, FLING, EMBARGO, QUASH, SNATCH, TAUNT, TORMENT, OUTRAGE, DRAGON_PULSE, DRAGON_CLAW, DRAGON_TAIL, DUAL_CHOP, THUNDER, THUNDERBOLT, WILD_CHARGE, THUNDER_PUNCH, VOLT_SWITCH, SHOCK_WAVE, ELECTROWEB, CHARGE_BEAM, MAGNET_RISE, THUNDER_WAVE, DAZZLING_GLEAM, FOCUS_PUNCH, FOCUS_BLAST, SUPERPOWER, BRICK_BREAK, DRAIN_PUNCH, LOW_SWEEP, POWER_UP_PUNCH, ROCK_SMASH, LOW_KICK, BULK_UP, OVERHEAT, FIRE_BLAST, HEAT_WAVE, FLAMETHROWER, FIRE_PUNCH, FLAME_CHARGE, SUNNY_DAY, WILL_O_WISP, SKY_ATTACK, FLY, BOUNCE, AERIAL_ACE, SKY_DROP, ACROBATICS, DEFOG, ROOST, TAILWIND, SHADOW_BALL, SHADOW_CLAW, SPITE, SOLAR_BEAM, ENERGY_BALL, SEED_BOMB, GIGA_DRAIN, GRASS_KNOT, SYNTHESIS, WORRY_SEED, EARTHQUAKE, EARTH_POWER, DRILL_RUN, STOMPING_TANTRUM, BULLDOZE, BLIZZARD, ICE_BEAM, ICE_PUNCH, FROST_BREATH, ICY_WIND, AURORA_VEIL, HAIL, EXPLOSION, GIGA_IMPACT, HYPER_BEAM, LAST_RESORT, HYPER_VOICE, UPROAR, STRENGTH, FACADE, COVET, HIDDEN_POWER, ROUND, CUT, SNORE, ECHOED_VOICE, FALSE_SWIPE, BIND, ENDEAVOR, FRUSTRATION, RETURN, SUPER_FANG, AFTER_YOU, ATTRACT, BLOCK, CONFIDE, DOUBLE_TEAM, HEAL_BELL, HELPING_HAND, LASER_FOCUS, NATURE_POWER, PAIN_SPLIT, PROTECT, PSYCH_UP, RECYCLE, ROAR, SAFEGUARD, SLEEP_TALK, SUBSTITUTE, SWAGGER, SWORDS_DANCE, WORK_UP, GUNK_SHOT, SLUDGE_WAVE, SLUDGE_BOMB, POISON_JAB, VENOSHOCK, GASTRO_ACID, TOXIC, DREAM_EATER, PSYCHIC, PSYSHOCK, ZEN_HEADBUTT, ALLY_SWITCH, CALM_MIND, GRAVITY, LIGHT_SCREEN, MAGIC_COAT, MAGIC_ROOM, REFLECT, REST, ROLE_PLAY, SKILL_SWAP, TELEKINESIS, TRICK, TRICK_ROOM, WONDER_ROOM, STONE_EDGE, ROCK_SLIDE, ROCK_TOMB, SMACK_DOWN, ROCK_POLISH, SANDSTORM, STEALTH_ROCK, IRON_TAIL, FLASH_CANNON, IRON_HEAD, SMART_STRIKE, STEEL_WING, GYRO_BALL, IRON_DEFENSE, AQUA_TAIL, SURF, LIQUIDATION, DIVE, SCALD, WATERFALL, WATER_PULSE, RAIN_DANCE, ENDURE, MEGA_KICK, ELECTRIC_TERRAIN, BODY_SLAM, HEAVY_SLAM, SELF_DESTRUCT, DARKEST_LARIAT, STEEL_ROLLER, BODY_PRESS, MEGA_PUNCH, HIGH_HORSEPOWER, SCREECH, FOCUS_ENERGY, SWIFT, SOLAR_BLADE, MAGICAL_LEAF, ASSURANCE, GRASSY_GLIDE, LEAF_STORM, GRASSY_TERRAIN, BULLET_SEED, SCARY_FACE, MUD_SHOT, AGILITY, REVERSAL, BLAZE_KICK, FIRE_FANG, ELECTRO_BALL, BATON_PASS, FLARE_BLITZ, SCORCHING_SANDS, COACHING, FIRE_SPIN, REVENGE, MUDDY_WATER, WHIRLPOOL, WEATHER_BALL, HYDRO_PUMP, BREAKING_SWIPE, ICICLE_SPEAR, METRONOME, SCALE_SHOT, AIR_SLASH, CRUNCH, TAIL_SLAP, DIG, AMNESIA, THUNDER_FANG, ICE_FANG, PSYCHIC_FANGS, NASTY_PLOT, DUAL_WINGBEAT, RETALIATE, FAKE_TEARS, BRAVE_BIRD, HURRICANE, EXPANDING_FORCE, STORED_POWER, GUARD_SWAP, POWER_SWAP, PSYCHIC_TERRAIN, FUTURE_SIGHT, IMPRISON, BUG_BUZZ, PSYCHO_CUT, PLAY_ROUGH, BEAT_UP, LASH_OUT, BURNING_JEALOUSY, POLLEN_PUFF, CHARM, SKITTER_SMACK, SAND_TOMB, RAZOR_SHELL, METEOR_BEAM, ROCK_BLAST, MEGAHORN, RISING_VOLTAGE, EERIE_IMPULSE, SPIKES, HEAT_CRASH, DRAGON_DANCE, CLOSE_COMBAT, FLIP_TURN, ENCORE, HEX, VENOM_DRENCH, POWER_WHIP, MYSTICAL_FIRE, BRINE, POLTERGEIST, PHANTOM_FORCE, DRAINING_KISS, MISTY_EXPLOSION, PIN_MISSILE, CROSS_POISON, PAY_DAY, POWER_GEM, LEAF_BLADE, AVALANCHE, TRIPLE_AXEL, MISTY_TERRAIN, TOXIC_SPIKES, TRI_ATTACK, TERRAIN_PULSE, COSMIC_POWER, AURA_SPHERE, CORROSIVE_GAS, SPEED_SWAP
	; end