	db MIENFOO ; 619

	db  45,  85,  50,  65,  55,  50
  ;  hp  atk  def  spd sat sdf

	db FIGHTING, FIGHTING ; type
	db 180 ; catch rate
	db 70 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 25 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/mienfoo/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_SLOW ; growth rate
	dn EGG_FIELD, EGG_HUMANLIKE ; egg groups

	; tm/hm learnset
	tmhm U_TURN, KNOCK_OFF, PAYBACK, FLING, TAUNT, DUAL_CHOP, FOCUS_PUNCH, FOCUS_BLAST, BRICK_BREAK, DRAIN_PUNCH, LOW_SWEEP, POWER_UP_PUNCH, ROCK_SMASH, LOW_KICK, BULK_UP, SUNNY_DAY, BOUNCE, AERIAL_ACE, ACROBATICS, GRASS_KNOT, STRENGTH, FACADE, HIDDEN_POWER, ROUND, SNORE, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, HELPING_HAND, PROTECT, PSYCH_UP, SLEEP_TALK, SUBSTITUTE, SWAGGER, SWORDS_DANCE, WORK_UP, POISON_JAB, TOXIC, ALLY_SWITCH, CALM_MIND, REFLECT, REST, ROLE_PLAY, STONE_EDGE, ROCK_SLIDE, ROCK_TOMB, RAIN_DANCE, ENDURE, MEGA_KICK, MEGA_PUNCH, FOCUS_ENERGY, SWIFT, AGILITY, REVERSAL, BATON_PASS, COACHING, REVENGE, DIG, RETALIATE, CLOSE_COMBAT, AURA_SPHERE
	; end