	db MILOTIC ; 350

	db  95,  60,  79,  81,  100,  125
  ;  hp  atk  def  spd sat sdf

	db WATER, WATER ; type
	db 60 ; catch rate
	db 189 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/milotic/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_ERRATIC ; growth rate
	dn EGG_WATER1, EGG_DRAGON ; egg groups

	; tm/hm learnset
	tmhm BRUTAL_SWING, DRAGON_PULSE, DRAGON_TAIL, BULLDOZE, BLIZZARD, ICE_BEAM, ICY_WIND, HAIL, GIGA_IMPACT, HYPER_BEAM, FACADE, HIDDEN_POWER, ROUND, SNORE, BIND, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, HELPING_HAND, LASER_FOCUS, PROTECT, PSYCH_UP, SAFEGUARD, SLEEP_TALK, SUBSTITUTE, SWAGGER, TOXIC, LIGHT_SCREEN, MAGIC_COAT, REST, IRON_TAIL, IRON_HEAD, AQUA_TAIL, SURF, DIVE, SCALD, WATERFALL, WATER_PULSE, RAIN_DANCE, ENDURE, BODY_SLAM, SWIFT, MUD_SHOT, MUDDY_WATER, WHIRLPOOL, WEATHER_BALL, HYDRO_PUMP, BREAKING_SWIPE, SCALE_SHOT, IMPRISON, SKITTER_SMACK, DRAGON_DANCE, FLIP_TURN, BRINE, AVALANCHE, TRIPLE_AXEL
	; end