	db MIMIKYU ; 778

	db  55,  90,  80,  96,  50,  105
  ;  hp  atk  def  spd sat sdf

	db GHOST, FAIRY ; type
	db 45 ; catch rate
	db 167 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/mimikyu/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_AMORPHOUS, EGG_AMORPHOUS ; egg groups

	; tm/hm learnset
	tmhm LEECH_LIFE, X_SCISSOR, INFESTATION, DARK_PULSE, THIEF, PAYBACK, FLING, EMBARGO, SNATCH, TAUNT, THUNDER, THUNDERBOLT, CHARGE_BEAM, THUNDER_WAVE, DAZZLING_GLEAM, DRAIN_PUNCH, BULK_UP, WILL_O_WISP, SHADOW_BALL, SHADOW_CLAW, SPITE, GIGA_DRAIN, GIGA_IMPACT, HYPER_BEAM, LAST_RESORT, FACADE, COVET, HIDDEN_POWER, ROUND, SNORE, FRUSTRATION, RETURN, AFTER_YOU, ATTRACT, CONFIDE, DOUBLE_TEAM, PAIN_SPLIT, PROTECT, PSYCH_UP, SAFEGUARD, SLEEP_TALK, SUBSTITUTE, SWAGGER, SWORDS_DANCE, WORK_UP, TOXIC, DREAM_EATER, PSYCHIC, LIGHT_SCREEN, MAGIC_ROOM, REST, TELEKINESIS, TRICK, TRICK_ROOM, ENDURE, SCREECH, PLAY_ROUGH, BEAT_UP, BURNING_JEALOUSY, CHARM, HEX, PHANTOM_FORCE, DRAINING_KISS
	; end