	db MOLTRES ; 146

	db  90,  100,  90,  90,  125,  85
  ;  hp  atk  def  spd sat sdf

	db FIRE, FLYING ; type
	db 3 ; catch rate
	db 261 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_UNKNOWN ; gender ratio
	db 100 ; unknown 1
	db 80 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/moltres/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_SLOW ; growth rate
	dn EGG_NONE, EGG_NONE ; egg groups

	; tm/hm learnset
	tmhm U_TURN, ROCK_SMASH, OVERHEAT, FIRE_BLAST, HEAT_WAVE, FLAMETHROWER, FLAME_CHARGE, SUNNY_DAY, WILL_O_WISP, SKY_ATTACK, FLY, AERIAL_ACE, SKY_DROP, DEFOG, ROOST, TAILWIND, SOLAR_BEAM, GIGA_IMPACT, HYPER_BEAM, FACADE, HIDDEN_POWER, ROUND, SNORE, FRUSTRATION, RETURN, CONFIDE, DOUBLE_TEAM, LASER_FOCUS, PROTECT, ROAR, SAFEGUARD, SLEEP_TALK, SUBSTITUTE, SWAGGER, TOXIC, REFLECT, REST, SANDSTORM, STEEL_WING, RAIN_DANCE, ENDURE, SWIFT, AGILITY, FLARE_BLITZ, SCORCHING_SANDS, FIRE_SPIN, WEATHER_BALL, AIR_SLASH, DUAL_WINGBEAT, BRAVE_BIRD, HURRICANE, BURNING_JEALOUSY, MYSTICAL_FIRE
	; end