	db MORPEKO ; 877

	db  58,  95,  58,  97,  70,  58
  ;  hp  atk  def  spd sat sdf

	db ELECTRIC, DARK ; type
	db 180 ; catch rate
	db 153 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 11 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/morpeko/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_FIELD, EGG_FAIRY ; egg groups

	; tm/hm learnset
	tmhm FOUL_PLAY, DARK_PULSE, THIEF, SNARL, PAYBACK, FLING, TAUNT, OUTRAGE, THUNDER, THUNDERBOLT, WILD_CHARGE, THUNDER_PUNCH, VOLT_SWITCH, ELECTROWEB, THUNDER_WAVE, BRICK_BREAK, SEED_BOMB, STOMPING_TANTRUM, UPROAR, FACADE, ROUND, SNORE, ATTRACT, PROTECT, SLEEP_TALK, SUBSTITUTE, REST, ENDURE, ELECTRIC_TERRAIN, SWIFT, ASSURANCE, BULLET_SEED, SCARY_FACE, AGILITY, FIRE_FANG, ELECTRO_BALL, REVENGE, CRUNCH, THUNDER_FANG, ICE_FANG, PSYCHIC_FANGS, NASTY_PLOT, FAKE_TEARS, LASH_OUT, RISING_VOLTAGE
	; end