	db NAGANADEL ; 804

	db  73,  73,  73,  121,  127,  73
  ;  hp  atk  def  spd sat sdf

	db POISON, DRAGON ; type
	db 45 ; catch rate
	db 243 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_UNKNOWN ; gender ratio
	db 100 ; unknown 1
	db 120 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/naganadel/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_SLOW ; growth rate
	dn EGG_NONE, EGG_NONE ; egg groups

	; tm/hm learnset
	tmhm LEECH_LIFE, X_SCISSOR, SIGNAL_BEAM, U_TURN, DARK_PULSE, THROAT_CHOP, THIEF, SNARL, SNATCH, DRACO_METEOR, OUTRAGE, DRAGON_PULSE, DRAGON_CLAW, DRAGON_TAIL, THUNDERBOLT, SHOCK_WAVE, FIRE_BLAST, HEAT_WAVE, FLAMETHROWER, SKY_ATTACK, FLY, AERIAL_ACE, SKY_DROP, ACROBATICS, TAILWIND, SHADOW_CLAW, GIGA_IMPACT, HYPER_BEAM, UPROAR, FACADE, HIDDEN_POWER, ROUND, SNORE, ECHOED_VOICE, FRUSTRATION, RETURN, CONFIDE, DOUBLE_TEAM, HELPING_HAND, LASER_FOCUS, PROTECT, SLEEP_TALK, SUBSTITUTE, GUNK_SHOT, SLUDGE_WAVE, SLUDGE_BOMB, POISON_JAB, VENOSHOCK, GASTRO_ACID, TOXIC, ALLY_SWITCH, REST, IRON_TAIL, SMART_STRIKE, ENDURE, SWIFT, ASSURANCE, BREAKING_SWIPE, SCALE_SHOT, AIR_SLASH, NASTY_PLOT, DUAL_WINGBEAT, CHARM, SPIKES, DRAGON_DANCE, HEX, VENOM_DRENCH, PIN_MISSILE, CROSS_POISON, TOXIC_SPIKES
	; end