	db NIHILEGO ; 793

	db  109,  53,  47,  103,  127,  131
  ;  hp  atk  def  spd sat sdf

	db ROCK, POISON ; type
	db 45 ; catch rate
	db 257 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_UNKNOWN ; gender ratio
	db 100 ; unknown 1
	db 120 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/nihilego/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_SLOW ; growth rate
	dn EGG_NONE, EGG_NONE ; egg groups

	; tm/hm learnset
	tmhm FOUL_PLAY, KNOCK_OFF, BRUTAL_SWING, THUNDER, THUNDERBOLT, CHARGE_BEAM, THUNDER_WAVE, DAZZLING_GLEAM, SPITE, GRASS_KNOT, WORRY_SEED, FACADE, HIDDEN_POWER, ROUND, SNORE, ECHOED_VOICE, BIND, FRUSTRATION, RETURN, CONFIDE, DOUBLE_TEAM, PAIN_SPLIT, PROTECT, SAFEGUARD, SLEEP_TALK, SUBSTITUTE, SWAGGER, GUNK_SHOT, SLUDGE_WAVE, SLUDGE_BOMB, POISON_JAB, VENOSHOCK, TOXIC, PSYCHIC, PSYSHOCK, ZEN_HEADBUTT, ALLY_SWITCH, LIGHT_SCREEN, MAGIC_COAT, REFLECT, REST, ROLE_PLAY, TELEKINESIS, TRICK_ROOM, WONDER_ROOM, ROCK_SLIDE, ROCK_TOMB, SANDSTORM, STEALTH_ROCK, IRON_HEAD, ENDURE, BODY_SLAM, METEOR_BEAM, HEX, VENOM_DRENCH, CROSS_POISON, POWER_GEM, TOXIC_SPIKES, CORROSIVE_GAS
	; end