	db NOCTOWL ; 164

	db  100,  50,  50,  70,  86,  96
  ;  hp  atk  def  spd sat sdf

	db NORMAL, FLYING ; type
	db 90 ; catch rate
	db 158 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 15 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/noctowl/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_FLYING, EGG_FLYING ; egg groups

	; tm/hm learnset
	tmhm THIEF, HEAT_WAVE, SUNNY_DAY, SKY_ATTACK, FLY, AERIAL_ACE, DEFOG, ROOST, TAILWIND, SHADOW_BALL, GIGA_IMPACT, HYPER_BEAM, HYPER_VOICE, UPROAR, FACADE, HIDDEN_POWER, ROUND, SNORE, ECHOED_VOICE, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, LASER_FOCUS, PROTECT, PSYCH_UP, RECYCLE, SLEEP_TALK, SUBSTITUTE, SWAGGER, WORK_UP, TOXIC, DREAM_EATER, PSYCHIC, ZEN_HEADBUTT, CALM_MIND, MAGIC_COAT, REFLECT, REST, STEEL_WING, RAIN_DANCE, ENDURE, SCREECH, SWIFT, AGILITY, AIR_SLASH, AMNESIA, NASTY_PLOT, DUAL_WINGBEAT, HURRICANE, STORED_POWER, FUTURE_SIGHT, IMPRISON
	; end