	db NOIVERN ; 715

	db  85,  70,  80,  123,  97,  80
  ;  hp  atk  def  spd sat sdf

	db FLYING, DRAGON ; type
	db 200 ; catch rate
	db 187 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/noivern/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_FLYING, EGG_DRAGON ; egg groups

	; tm/hm learnset
	tmhm LEECH_LIFE, X_SCISSOR, U_TURN, DARK_PULSE, THIEF, SNATCH, TAUNT, TORMENT, DRACO_METEOR, OUTRAGE, DRAGON_PULSE, DRAGON_CLAW, WILD_CHARGE, FOCUS_BLAST, BRICK_BREAK, HEAT_WAVE, FLAMETHROWER, SUNNY_DAY, SKY_ATTACK, FLY, AERIAL_ACE, ACROBATICS, DEFOG, ROOST, TAILWIND, SHADOW_BALL, SHADOW_CLAW, SOLAR_BEAM, GIGA_IMPACT, HYPER_BEAM, HYPER_VOICE, UPROAR, FACADE, HIDDEN_POWER, ROUND, CUT, SNORE, ECHOED_VOICE, FRUSTRATION, RETURN, SUPER_FANG, ATTRACT, CONFIDE, DOUBLE_TEAM, LASER_FOCUS, PROTECT, SLEEP_TALK, SUBSTITUTE, SWAGGER, TOXIC, DREAM_EATER, PSYCHIC, REST, IRON_TAIL, STEEL_WING, WATER_PULSE, ENDURE, SCREECH, SWIFT, AGILITY, AIR_SLASH, DUAL_WINGBEAT, HURRICANE, DRAGON_DANCE
	; end