	db NOSEPASS ; 299

	db  30,  45,  135,  30,  45,  90
  ;  hp  atk  def  spd sat sdf

	db ROCK, ROCK ; type
	db 255 ; catch rate
	db 75 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/nosepass/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_MINERAL, EGG_MINERAL ; egg groups

	; tm/hm learnset
	tmhm TAUNT, TORMENT, THUNDER, THUNDERBOLT, THUNDER_PUNCH, VOLT_SWITCH, SHOCK_WAVE, MAGNET_RISE, THUNDER_WAVE, DAZZLING_GLEAM, ROCK_SMASH, FIRE_PUNCH, SUNNY_DAY, EARTHQUAKE, EARTH_POWER, STOMPING_TANTRUM, BULLDOZE, ICE_PUNCH, EXPLOSION, STRENGTH, FACADE, HIDDEN_POWER, ROUND, SNORE, FRUSTRATION, RETURN, ATTRACT, BLOCK, CONFIDE, DOUBLE_TEAM, PAIN_SPLIT, PROTECT, SLEEP_TALK, SUBSTITUTE, SWAGGER, TOXIC, GRAVITY, MAGIC_COAT, REST, STONE_EDGE, ROCK_SLIDE, ROCK_TOMB, SMACK_DOWN, ROCK_POLISH, SANDSTORM, STEALTH_ROCK, IRON_DEFENSE, ENDURE
	; end