	db NUZLEAF ; 274

	db  70,  70,  40,  60,  60,  40
  ;  hp  atk  def  spd sat sdf

	db GRASS, DARK ; type
	db 120 ; catch rate
	db 119 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 15 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/nuzleaf/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_SLOW ; growth rate
	dn EGG_FIELD, EGG_GRASS ; egg groups

	; tm/hm learnset
	tmhm FOUL_PLAY, DARK_PULSE, THIEF, SNARL, PAYBACK, FLING, EMBARGO, TORMENT, BRICK_BREAK, LOW_SWEEP, POWER_UP_PUNCH, ROCK_SMASH, LOW_KICK, SUNNY_DAY, DEFOG, SHADOW_BALL, SPITE, SOLAR_BEAM, ENERGY_BALL, SEED_BOMB, GIGA_DRAIN, GRASS_KNOT, SYNTHESIS, WORRY_SEED, EXPLOSION, HYPER_BEAM, STRENGTH, FACADE, HIDDEN_POWER, ROUND, CUT, SNORE, FALSE_SWIPE, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, NATURE_POWER, PROTECT, PSYCH_UP, SLEEP_TALK, SUBSTITUTE, SWAGGER, SWORDS_DANCE, TOXIC, REST, ROCK_SLIDE, ROCK_TOMB, ENDURE, MEGA_KICK, BODY_SLAM, SELF_DESTRUCT, SWIFT, SOLAR_BLADE, ASSURANCE, GRASSY_GLIDE, GRASSY_TERRAIN, BULLET_SEED, DIG, AMNESIA, NASTY_PLOT, RETALIATE, POWER_SWAP, BEAT_UP, LASH_OUT, LEAF_BLADE
	; end