	db OCTILLERY ; 224

	db  75,  105,  75,  45,  105,  75
  ;  hp  atk  def  spd sat sdf

	db WATER, WATER ; type
	db 75 ; catch rate
	db 168 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/octillery/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_WATER1, EGG_WATER2 ; egg groups

	; tm/hm learnset
	tmhm SIGNAL_BEAM, THIEF, PAYBACK, CHARGE_BEAM, THUNDER_WAVE, FIRE_BLAST, FLAMETHROWER, SUNNY_DAY, BOUNCE, ENERGY_BALL, SEED_BOMB, BLIZZARD, ICE_BEAM, ICY_WIND, GIGA_IMPACT, HYPER_BEAM, FACADE, HIDDEN_POWER, ROUND, SNORE, BIND, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, HELPING_HAND, PROTECT, SLEEP_TALK, SUBSTITUTE, SWAGGER, GUNK_SHOT, SLUDGE_WAVE, SLUDGE_BOMB, TOXIC, PSYCHIC, REST, SMACK_DOWN, FLASH_CANNON, SURF, LIQUIDATION, DIVE, SCALD, WATERFALL, WATER_PULSE, RAIN_DANCE, ENDURE, SCREECH, FOCUS_ENERGY, SWIFT, ASSURANCE, BULLET_SEED, MUD_SHOT, WHIRLPOOL, HYDRO_PUMP, SKITTER_SMACK, ROCK_BLAST, BRINE
	; end