	db ONIX ; 95

	db  35,  45,  160,  70,  30,  45
  ;  hp  atk  def  spd sat sdf

	db ROCK, GROUND ; type
	db 45 ; catch rate
	db 77 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 25 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/onix/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_MINERAL, EGG_MINERAL ; egg groups

	; tm/hm learnset
	tmhm BRUTAL_SWING, PAYBACK, TAUNT, TORMENT, DRAGON_PULSE, DRAGON_TAIL, ROCK_SMASH, SUNNY_DAY, EARTHQUAKE, EARTH_POWER, DRILL_RUN, STOMPING_TANTRUM, BULLDOZE, EXPLOSION, STRENGTH, FACADE, HIDDEN_POWER, ROUND, SNORE, BIND, FRUSTRATION, RETURN, ATTRACT, BLOCK, CONFIDE, DOUBLE_TEAM, NATURE_POWER, PROTECT, PSYCH_UP, ROAR, SLEEP_TALK, SUBSTITUTE, SWAGGER, TOXIC, REST, STONE_EDGE, ROCK_SLIDE, ROCK_TOMB, SMACK_DOWN, ROCK_POLISH, SANDSTORM, STEALTH_ROCK, IRON_TAIL, FLASH_CANNON, IRON_HEAD, GYRO_BALL, ENDURE, BODY_SLAM, HEAVY_SLAM, SELF_DESTRUCT, BODY_PRESS, HIGH_HORSEPOWER, SCREECH, SCARY_FACE, SCORCHING_SANDS, BREAKING_SWIPE, DIG, SAND_TOMB, METEOR_BEAM, ROCK_BLAST, DRAGON_DANCE
	; end