	db ORANGURU ; 765

	db  90,  60,  80,  60,  90,  110
  ;  hp  atk  def  spd sat sdf

	db NORMAL, PSYCHIC ; type
	db 45 ; catch rate
	db 172 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/oranguru/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_SLOW ; growth rate
	dn EGG_FIELD, EGG_FIELD ; egg groups

	; tm/hm learnset
	tmhm FOUL_PLAY, KNOCK_OFF, BRUTAL_SWING, PAYBACK, FLING, EMBARGO, QUASH, SNATCH, TAUNT, THUNDER, THUNDERBOLT, CHARGE_BEAM, FOCUS_BLAST, BRICK_BREAK, SUNNY_DAY, SHADOW_BALL, SPITE, ENERGY_BALL, EARTHQUAKE, BULLDOZE, GIGA_IMPACT, HYPER_BEAM, FACADE, COVET, HIDDEN_POWER, ROUND, SNORE, FRUSTRATION, RETURN, AFTER_YOU, ATTRACT, BLOCK, CONFIDE, DOUBLE_TEAM, NATURE_POWER, PAIN_SPLIT, PROTECT, PSYCH_UP, SAFEGUARD, SLEEP_TALK, SUBSTITUTE, SWAGGER, WORK_UP, TOXIC, DREAM_EATER, PSYCHIC, PSYSHOCK, ZEN_HEADBUTT, ALLY_SWITCH, CALM_MIND, GRAVITY, LIGHT_SCREEN, MAGIC_COAT, MAGIC_ROOM, REFLECT, REST, TELEKINESIS, TRICK, TRICK_ROOM, WONDER_ROOM, ROCK_SLIDE, RAIN_DANCE, ENDURE, MEGA_KICK, MEGA_PUNCH, NASTY_PLOT, EXPANDING_FORCE, STORED_POWER, PSYCHIC_TERRAIN, FUTURE_SIGHT, IMPRISON, ENCORE, TERRAIN_PULSE
	; end