	db PALKIA ; 484

	db  90,  120,  100,  100,  150,  120
  ;  hp  atk  def  spd sat sdf

	db WATER, DRAGON ; type
	db 3 ; catch rate
	db 306 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_UNKNOWN ; gender ratio
	db 100 ; unknown 1
	db 120 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/palkia/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_SLOW ; growth rate
	dn EGG_NONE, EGG_NONE ; egg groups

	; tm/hm learnset
	tmhm FLING, DRACO_METEOR, OUTRAGE, DRAGON_PULSE, DRAGON_CLAW, DRAGON_TAIL, THUNDER, THUNDERBOLT, SHOCK_WAVE, THUNDER_WAVE, FOCUS_PUNCH, FOCUS_BLAST, BRICK_BREAK, ROCK_SMASH, BULK_UP, FIRE_BLAST, FLAMETHROWER, SUNNY_DAY, AERIAL_ACE, SHADOW_CLAW, EARTHQUAKE, EARTH_POWER, STOMPING_TANTRUM, BULLDOZE, BLIZZARD, ICE_BEAM, HAIL, GIGA_IMPACT, HYPER_BEAM, HYPER_VOICE, STRENGTH, FACADE, HIDDEN_POWER, ROUND, CUT, SNORE, ECHOED_VOICE, FRUSTRATION, RETURN, CONFIDE, DOUBLE_TEAM, PROTECT, PSYCH_UP, ROAR, SAFEGUARD, SLEEP_TALK, SUBSTITUTE, SWAGGER, TOXIC, GRAVITY, REST, TRICK_ROOM, STONE_EDGE, ROCK_SLIDE, ROCK_TOMB, SANDSTORM, AQUA_TAIL, SURF, LIQUIDATION, DIVE, WATER_PULSE, RAIN_DANCE, ENDURE, BODY_SLAM, HEAVY_SLAM, BODY_PRESS, SWIFT, SCARY_FACE, WHIRLPOOL, HYDRO_PUMP, BREAKING_SWIPE, SCALE_SHOT, DUAL_WINGBEAT, BRINE, POWER_GEM, AVALANCHE, AURA_SPHERE
	; end