	db PALOSSAND ; 770

	db  85,  75,  110,  35,  100,  75
  ;  hp  atk  def  spd sat sdf

	db GHOST, GROUND ; type
	db 60 ; catch rate
	db 168 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 16 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/palossand/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_AMORPHOUS, EGG_AMORPHOUS ; egg groups

	; tm/hm learnset
	tmhm INFESTATION, FLING, EMBARGO, QUASH, SHADOW_BALL, SPITE, ENERGY_BALL, GIGA_DRAIN, EARTHQUAKE, EARTH_POWER, BULLDOZE, GIGA_IMPACT, FACADE, HIDDEN_POWER, ROUND, SNORE, FRUSTRATION, RETURN, AFTER_YOU, ATTRACT, BLOCK, CONFIDE, DOUBLE_TEAM, PAIN_SPLIT, PROTECT, RECYCLE, SLEEP_TALK, SUBSTITUTE, SWAGGER, SLUDGE_BOMB, TOXIC, PSYCHIC, GRAVITY, REST, ROLE_PLAY, SKILL_SWAP, TRICK, STONE_EDGE, ROCK_SLIDE, ROCK_TOMB, ROCK_POLISH, SANDSTORM, STEALTH_ROCK, IRON_DEFENSE, ENDURE, SCORCHING_SANDS, AMNESIA, SAND_TOMB, POLTERGEIST, TERRAIN_PULSE
	; end