	db PANGORO ; 675

	db  95,  124,  78,  58,  69,  71
  ;  hp  atk  def  spd sat sdf

	db FIGHTING, DARK ; type
	db 128 ; catch rate
	db 173 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 25 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/pangoro/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_FIELD, EGG_HUMANLIKE ; egg groups

	; tm/hm learnset
	tmhm X_SCISSOR, INFESTATION, FOUL_PLAY, DARK_PULSE, THROAT_CHOP, KNOCK_OFF, THIEF, SNARL, PAYBACK, FLING, EMBARGO, QUASH, SNATCH, TAUNT, TORMENT, OUTRAGE, DRAGON_CLAW, DUAL_CHOP, THUNDER_PUNCH, FOCUS_PUNCH, FOCUS_BLAST, SUPERPOWER, BRICK_BREAK, DRAIN_PUNCH, LOW_SWEEP, POWER_UP_PUNCH, ROCK_SMASH, LOW_KICK, BULK_UP, FIRE_PUNCH, SUNNY_DAY, AERIAL_ACE, SHADOW_CLAW, SPITE, GRASS_KNOT, EARTHQUAKE, STOMPING_TANTRUM, BULLDOZE, ICE_PUNCH, GIGA_IMPACT, HYPER_BEAM, HYPER_VOICE, UPROAR, STRENGTH, FACADE, COVET, HIDDEN_POWER, ROUND, CUT, SNORE, ECHOED_VOICE, FALSE_SWIPE, ENDEAVOR, FRUSTRATION, RETURN, ATTRACT, BLOCK, CONFIDE, DOUBLE_TEAM, HELPING_HAND, LASER_FOCUS, PROTECT, ROAR, SLEEP_TALK, SUBSTITUTE, SWAGGER, SWORDS_DANCE, WORK_UP, GUNK_SHOT, SLUDGE_BOMB, POISON_JAB, TOXIC, ZEN_HEADBUTT, REST, STONE_EDGE, ROCK_SLIDE, ROCK_TOMB, IRON_HEAD, SURF, RAIN_DANCE, ENDURE, MEGA_KICK, BODY_SLAM, DARKEST_LARIAT, MEGA_PUNCH, FOCUS_ENERGY, SCARY_FACE, REVERSAL, COACHING, REVENGE, CRUNCH, DIG, RETALIATE, BEAT_UP, LASH_OUT, CLOSE_COMBAT
	; end