	db PANPOUR ; 515

	db  50,  53,  48,  64,  53,  48
  ;  hp  atk  def  spd sat sdf

	db WATER, WATER ; type
	db 190 ; catch rate
	db 63 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F12_5 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/panpour/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_FIELD, EGG_FIELD ; egg groups

	; tm/hm learnset
	tmhm KNOCK_OFF, THIEF, PAYBACK, FLING, TAUNT, TORMENT, FOCUS_PUNCH, LOW_SWEEP, ROCK_SMASH, LOW_KICK, ACROBATICS, SHADOW_CLAW, GRASS_KNOT, BLIZZARD, ICE_BEAM, ICE_PUNCH, ICY_WIND, HAIL, UPROAR, FACADE, COVET, HIDDEN_POWER, ROUND, CUT, SNORE, ENDEAVOR, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, HELPING_HAND, PROTECT, RECYCLE, SLEEP_TALK, SUBSTITUTE, SWAGGER, WORK_UP, GUNK_SHOT, GASTRO_ACID, TOXIC, REST, ROLE_PLAY, ROCK_TOMB, IRON_TAIL, AQUA_TAIL, SURF, DIVE, SCALD, WATER_PLEDGE, WATERFALL, WATER_PULSE, RAIN_DANCE, ENDURE, DIG
	; end