	db PAWNIARD ; 624

	db  45,  85,  70,  60,  40,  40
  ;  hp  atk  def  spd sat sdf

	db DARK, STEEL ; type
	db 120 ; catch rate
	db 68 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/pawniard/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_HUMANLIKE, EGG_HUMANLIKE ; egg groups

	; tm/hm learnset
	tmhm X_SCISSOR, FOUL_PLAY, DARK_PULSE, KNOCK_OFF, THIEF, SNARL, PAYBACK, FLING, EMBARGO, SNATCH, TAUNT, TORMENT, DUAL_CHOP, MAGNET_RISE, THUNDER_WAVE, BRICK_BREAK, LOW_SWEEP, POWER_UP_PUNCH, ROCK_SMASH, LOW_KICK, AERIAL_ACE, SHADOW_CLAW, SPITE, GRASS_KNOT, FACADE, HIDDEN_POWER, ROUND, CUT, SNORE, FALSE_SWIPE, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, PROTECT, SLEEP_TALK, SUBSTITUTE, SWAGGER, SWORDS_DANCE, POISON_JAB, TOXIC, REST, ROLE_PLAY, ROCK_TOMB, ROCK_POLISH, SANDSTORM, STEALTH_ROCK, IRON_HEAD, IRON_DEFENSE, RAIN_DANCE, ENDURE, STEEL_BEAM, SCREECH, ASSURANCE, SCARY_FACE, REVENGE, DIG, RETALIATE, PSYCHO_CUT, BEAT_UP, LASH_OUT
	; end