	db PELIPPER ; 279

	db  60,  50,  100,  65,  95,  70
  ;  hp  atk  def  spd sat sdf

	db WATER, FLYING ; type
	db 45 ; catch rate
	db 154 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/pelipper/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_WATER1, EGG_FLYING ; egg groups

	; tm/hm learnset
	tmhm U_TURN, KNOCK_OFF, THIEF, PAYBACK, FLING, SHOCK_WAVE, SKY_ATTACK, FLY, AERIAL_ACE, SKY_DROP, DEFOG, ROOST, TAILWIND, SEED_BOMB, BLIZZARD, ICE_BEAM, ICY_WIND, HAIL, GIGA_IMPACT, HYPER_BEAM, UPROAR, FACADE, HIDDEN_POWER, ROUND, SNORE, ECHOED_VOICE, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, PROTECT, SLEEP_TALK, SUBSTITUTE, SWAGGER, GUNK_SHOT, TOXIC, REST, STEEL_WING, SURF, LIQUIDATION, SCALD, WATER_PULSE, RAIN_DANCE, ENDURE, SWIFT, AGILITY, WHIRLPOOL, WEATHER_BALL, HYDRO_PUMP, AIR_SLASH, DUAL_WINGBEAT, BRAVE_BIRD, HURRICANE, BRINE
	; end