	db PERRSERKER ; 863

	db  70,  110,  100,  50,  50,  60
  ;  hp  atk  def  spd sat sdf

	db STEEL, STEEL ; type
	db 90 ; catch rate
	db 154 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 21 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/perrserker/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_FIELD, EGG_FIELD ; egg groups

	; tm/hm learnset
	tmhm U_TURN, FOUL_PLAY, DARK_PULSE, THROAT_CHOP, THIEF, PAYBACK, FLING, TAUNT, THUNDER, THUNDERBOLT, SUNNY_DAY, SHADOW_BALL, SHADOW_CLAW, SEED_BOMB, GIGA_IMPACT, HYPER_BEAM, HYPER_VOICE, UPROAR, FACADE, ROUND, SNORE, ATTRACT, PROTECT, SLEEP_TALK, SUBSTITUTE, SWORDS_DANCE, WORK_UP, GUNK_SHOT, REST, IRON_TAIL, IRON_HEAD, GYRO_BALL, IRON_DEFENSE, RAIN_DANCE, ENDURE, STEEL_BEAM, BODY_SLAM, HEAVY_SLAM, SCREECH, ASSURANCE, BATON_PASS, CRUNCH, DIG, AMNESIA, NASTY_PLOT, RETALIATE, PLAY_ROUGH, LASH_OUT, CLOSE_COMBAT, PAY_DAY
	; end