	db PHEROMOSA ; 795

	db  71,  137,  37,  151,  137,  37
  ;  hp  atk  def  spd sat sdf

	db BUG, FIGHTING ; type
	db 45 ; catch rate
	db 257 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_UNKNOWN ; gender ratio
	db 100 ; unknown 1
	db 120 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/pheromosa/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_SLOW ; growth rate
	dn EGG_NONE, EGG_NONE ; egg groups

	; tm/hm learnset
	tmhm SIGNAL_BEAM, U_TURN, BUG_BITE, FOUL_PLAY, THROAT_CHOP, FLING, SNATCH, TAUNT, TORMENT, OUTRAGE, SHOCK_WAVE, ELECTROWEB, FOCUS_BLAST, BRICK_BREAK, LOW_SWEEP, LOW_KICK, BOUNCE, ROOST, DRILL_RUN, BLIZZARD, ICE_BEAM, ICY_WIND, GIGA_IMPACT, HYPER_BEAM, FACADE, HIDDEN_POWER, ROUND, SNORE, ECHOED_VOICE, FALSE_SWIPE, FRUSTRATION, RETURN, BLOCK, CONFIDE, DOUBLE_TEAM, LASER_FOCUS, PROTECT, SLEEP_TALK, SUBSTITUTE, SWAGGER, POISON_JAB, TOXIC, REST, ENDURE, SWIFT, ASSURANCE, AGILITY, COACHING, BUG_BUZZ, SKITTER_SMACK, CLOSE_COMBAT, TRIPLE_AXEL, SPEED_SWAP
	; end