	db PORYGON ; 137

	db  65,  60,  70,  40,  85,  75
  ;  hp  atk  def  spd sat sdf

	db NORMAL, NORMAL ; type
	db 45 ; catch rate
	db 79 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_UNKNOWN ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/porygon/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_MINERAL, EGG_MINERAL ; egg groups

	; tm/hm learnset
	tmhm SIGNAL_BEAM, FOUL_PLAY, THIEF, THUNDER, THUNDERBOLT, SHOCK_WAVE, ELECTROWEB, CHARGE_BEAM, MAGNET_RISE, THUNDER_WAVE, SUNNY_DAY, AERIAL_ACE, SHADOW_BALL, SOLAR_BEAM, BLIZZARD, ICE_BEAM, ICY_WIND, GIGA_IMPACT, HYPER_BEAM, LAST_RESORT, FACADE, HIDDEN_POWER, ROUND, SNORE, FRUSTRATION, RETURN, CONFIDE, DOUBLE_TEAM, PAIN_SPLIT, PROTECT, PSYCH_UP, RECYCLE, SLEEP_TALK, SUBSTITUTE, SWAGGER, TOXIC, DREAM_EATER, PSYCHIC, PSYSHOCK, ZEN_HEADBUTT, ALLY_SWITCH, GRAVITY, MAGIC_COAT, REFLECT, REST, TELEKINESIS, TRICK, TRICK_ROOM, WONDER_ROOM, IRON_TAIL, RAIN_DANCE, ENDURE, SWIFT, AGILITY, GUARD_SWAP, POWER_SWAP, EERIE_IMPULSE, TRI_ATTACK, SPEED_SWAP
	; end