	db PUPITAR ; 247

	db  70,  84,  70,  51,  65,  70
  ;  hp  atk  def  spd sat sdf

	db ROCK, GROUND ; type
	db 45 ; catch rate
	db 144 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 40 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/pupitar/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_SLOW ; growth rate
	dn EGG_MONSTER, EGG_MONSTER ; egg groups

	; tm/hm learnset
	tmhm DARK_PULSE, SNARL, PAYBACK, TAUNT, TORMENT, OUTRAGE, SUPERPOWER, BRICK_BREAK, POWER_UP_PUNCH, ROCK_SMASH, SUNNY_DAY, SPITE, EARTHQUAKE, EARTH_POWER, STOMPING_TANTRUM, BULLDOZE, HYPER_BEAM, UPROAR, FACADE, HIDDEN_POWER, ROUND, SNORE, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, PROTECT, SLEEP_TALK, SUBSTITUTE, SWAGGER, TOXIC, REST, STONE_EDGE, ROCK_SLIDE, ROCK_TOMB, SMACK_DOWN, ROCK_POLISH, SANDSTORM, STEALTH_ROCK, IRON_TAIL, IRON_HEAD, IRON_DEFENSE, RAIN_DANCE, ENDURE, BODY_SLAM, SCREECH, FOCUS_ENERGY, ASSURANCE, SCARY_FACE, MUDDY_WATER, CRUNCH, DIG, RETALIATE, SAND_TOMB, DRAGON_DANCE
	; end