	db RAYQUAZA ; 384

	db  105,  150,  90,  95,  150,  90
  ;  hp  atk  def  spd sat sdf

	db DRAGON, FLYING ; type
	db 45 ; catch rate
	db 306 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_UNKNOWN ; gender ratio
	db 100 ; unknown 1
	db 120 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/rayquaza/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_SLOW ; growth rate
	dn EGG_NONE, EGG_NONE ; egg groups

	; tm/hm learnset
	tmhm BRUTAL_SWING, FLING, DRACO_METEOR, OUTRAGE, DRAGON_PULSE, DRAGON_CLAW, DRAGON_TAIL, THUNDER, THUNDERBOLT, SHOCK_WAVE, THUNDER_WAVE, FOCUS_BLAST, BRICK_BREAK, ROCK_SMASH, BULK_UP, OVERHEAT, FIRE_BLAST, FLAMETHROWER, SUNNY_DAY, DRAGON_ASCENT, FLY, AERIAL_ACE, SKY_DROP, DEFOG, TAILWIND, SHADOW_CLAW, SOLAR_BEAM, ENERGY_BALL, EARTHQUAKE, EARTH_POWER, BULLDOZE, BLIZZARD, ICE_BEAM, ICY_WIND, GIGA_IMPACT, HYPER_BEAM, HYPER_VOICE, UPROAR, STRENGTH, FACADE, HIDDEN_POWER, ROUND, SNORE, ECHOED_VOICE, BIND, FRUSTRATION, RETURN, CONFIDE, DOUBLE_TEAM, PROTECT, PSYCH_UP, ROAR, SLEEP_TALK, SUBSTITUTE, SWAGGER, SWORDS_DANCE, TOXIC, REST, STONE_EDGE, ROCK_SLIDE, ROCK_TOMB, SANDSTORM, IRON_TAIL, IRON_HEAD, GYRO_BALL, AQUA_TAIL, SURF, DIVE, WATERFALL, WATER_PULSE, RAIN_DANCE, ENDURE, BODY_SLAM, SWIFT, SCARY_FACE, WHIRLPOOL, HYDRO_PUMP, BREAKING_SWIPE, SCALE_SHOT, AIR_SLASH, CRUNCH, HURRICANE, METEOR_BEAM, DRAGON_DANCE, AVALANCHE, COSMIC_POWER
	; end