	db REGIGIGAS ; 486

	db  110,  160,  110,  100,  80,  110
  ;  hp  atk  def  spd sat sdf

	db NORMAL, NORMAL ; type
	db 3 ; catch rate
	db 302 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_UNKNOWN ; gender ratio
	db 100 ; unknown 1
	db 120 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/regigigas/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_SLOW ; growth rate
	dn EGG_NONE, EGG_NONE ; egg groups

	; tm/hm learnset
	tmhm KNOCK_OFF, PAYBACK, FLING, THUNDER, THUNDERBOLT, THUNDER_PUNCH, SHOCK_WAVE, THUNDER_WAVE, FOCUS_PUNCH, FOCUS_BLAST, SUPERPOWER, BRICK_BREAK, DRAIN_PUNCH, POWER_UP_PUNCH, ROCK_SMASH, FIRE_PUNCH, SUNNY_DAY, AERIAL_ACE, EARTHQUAKE, EARTH_POWER, STOMPING_TANTRUM, BULLDOZE, ICE_PUNCH, ICY_WIND, GIGA_IMPACT, HYPER_BEAM, STRENGTH, FACADE, HIDDEN_POWER, ROUND, SNORE, FRUSTRATION, RETURN, BLOCK, CONFIDE, DOUBLE_TEAM, NATURE_POWER, PROTECT, PSYCH_UP, SAFEGUARD, SLEEP_TALK, SUBSTITUTE, SWAGGER, TOXIC, ZEN_HEADBUTT, GRAVITY, REST, STONE_EDGE, ROCK_SLIDE, ROCK_TOMB, SMACK_DOWN, ROCK_POLISH, IRON_HEAD, RAIN_DANCE, ENDURE, MEGA_KICK, BODY_SLAM, HEAVY_SLAM, DARKEST_LARIAT, BODY_PRESS, MEGA_PUNCH, HIGH_HORSEPOWER, REVENGE, RETALIATE, HEAT_CRASH, AVALANCHE, TERRAIN_PULSE
	; end