	db RHYHORN ; 111

	db  80,  85,  95,  25,  30,  30
  ;  hp  atk  def  spd sat sdf

	db GROUND, ROCK ; type
	db 120 ; catch rate
	db 69 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/rhyhorn/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_SLOW ; growth rate
	dn EGG_MONSTER, EGG_FIELD ; egg groups

	; tm/hm learnset
	tmhm THIEF, PAYBACK, DRAGON_PULSE, THUNDER, THUNDERBOLT, SHOCK_WAVE, SUPERPOWER, ROCK_SMASH, FIRE_BLAST, FLAMETHROWER, SUNNY_DAY, SPITE, EARTHQUAKE, EARTH_POWER, DRILL_RUN, STOMPING_TANTRUM, BULLDOZE, BLIZZARD, ICE_BEAM, ICY_WIND, UPROAR, STRENGTH, FACADE, HIDDEN_POWER, ROUND, SNORE, ENDEAVOR, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, PROTECT, ROAR, SLEEP_TALK, SUBSTITUTE, SWAGGER, SWORDS_DANCE, POISON_JAB, TOXIC, REST, STONE_EDGE, ROCK_SLIDE, ROCK_TOMB, SMACK_DOWN, ROCK_POLISH, SANDSTORM, STEALTH_ROCK, IRON_TAIL, SMART_STRIKE, AQUA_TAIL, RAIN_DANCE, ENDURE, BODY_SLAM, HIGH_HORSEPOWER, SCARY_FACE, MUD_SHOT, REVERSAL, FIRE_FANG, SCORCHING_SANDS, CRUNCH, DIG, THUNDER_FANG, ICE_FANG, ROCK_BLAST, MEGAHORN
	; end