	db RILLABOOM ; 812

	db  100,  125,  90,  85,  60,  70
  ;  hp  atk  def  spd sat sdf

	db GRASS, GRASS ; type
	db 45 ; catch rate
	db 265 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F12_5 ; gender ratio
	db 100 ; unknown 1
	db 21 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/rillaboom/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_SLOW ; growth rate
	dn EGG_FIELD, EGG_GRASS ; egg groups

	; tm/hm learnset
	tmhm U_TURN, BRUTAL_SWING, SNARL, FLING, TAUNT, FOCUS_BLAST, SUPERPOWER, BRICK_BREAK, DRAIN_PUNCH, LOW_KICK, BULK_UP, SUNNY_DAY, ACROBATICS, FRENZY_PLANT, SOLAR_BEAM, ENERGY_BALL, GRASS_PLEDGE, GIGA_DRAIN, GRASS_KNOT, EARTHQUAKE, EARTH_POWER, STOMPING_TANTRUM, BULLDOZE, GIGA_IMPACT, HYPER_BEAM, HYPER_VOICE, UPROAR, FACADE, ROUND, SNORE, FALSE_SWIPE, ATTRACT, PROTECT, SLEEP_TALK, SUBSTITUTE, SWORDS_DANCE, WORK_UP, REST, ENDURE, MEGA_KICK, BODY_SLAM, DARKEST_LARIAT, BODY_PRESS, MEGA_PUNCH, HIGH_HORSEPOWER, SCREECH, FOCUS_ENERGY, SWIFT, SOLAR_BLADE, MAGICAL_LEAF, ASSURANCE, GRASSY_GLIDE, LEAF_STORM, GRASSY_TERRAIN, BULLET_SEED, SCARY_FACE, MUD_SHOT
	; end