	db ROTOM ; 479

	db  50,  50,  77,  91,  95,  77
  ;  hp  atk  def  spd sat sdf

	db ELECTRIC, GHOST ; type
	db 45 ; catch rate
	db 154 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_UNKNOWN ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/rotom/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_AMORPHOUS, EGG_AMORPHOUS ; egg groups

	; tm/hm learnset
	tmhm SIGNAL_BEAM, FOUL_PLAY, DARK_PULSE, THIEF, SNATCH, THUNDER, THUNDERBOLT, VOLT_SWITCH, SHOCK_WAVE, ELECTROWEB, CHARGE_BEAM, THUNDER_WAVE, SUNNY_DAY, WILL_O_WISP, DEFOG, SHADOW_BALL, SPITE, HYPER_VOICE, UPROAR, FACADE, HIDDEN_POWER, ROUND, SNORE, FRUSTRATION, RETURN, CONFIDE, DOUBLE_TEAM, HELPING_HAND, PAIN_SPLIT, PROTECT, PSYCH_UP, SLEEP_TALK, SUBSTITUTE, SWAGGER, TOXIC, DREAM_EATER, ALLY_SWITCH, LIGHT_SCREEN, REFLECT, REST, TELEKINESIS, TRICK, RAIN_DANCE, ENDURE, ELECTRIC_TERRAIN, SWIFT, ELECTRO_BALL, NASTY_PLOT, STORED_POWER, RISING_VOLTAGE, EERIE_IMPULSE, HEX, POLTERGEIST
	; end