	db RUNERIGUS ; 867

	db  58,  95,  145,  30,  50,  105
  ;  hp  atk  def  spd sat sdf

	db GROUND, GHOST ; type
	db 90 ; catch rate
	db 169 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 26 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/runerigus/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_MINERAL, EGG_AMORPHOUS ; egg groups

	; tm/hm learnset
	tmhm DARK_PULSE, BRUTAL_SWING, THIEF, PAYBACK, TAUNT, DRAGON_PULSE, WILL_O_WISP, SHADOW_BALL, SHADOW_CLAW, ENERGY_BALL, GRASS_KNOT, EARTHQUAKE, EARTH_POWER, BULLDOZE, GIGA_IMPACT, HYPER_BEAM, FACADE, ROUND, SNORE, ATTRACT, PROTECT, SAFEGUARD, SLEEP_TALK, SUBSTITUTE, PSYCHIC, ZEN_HEADBUTT, ALLY_SWITCH, CALM_MIND, REST, SKILL_SWAP, TRICK, TRICK_ROOM, WONDER_ROOM, STONE_EDGE, ROCK_SLIDE, ROCK_TOMB, SANDSTORM, STEALTH_ROCK, IRON_DEFENSE, RAIN_DANCE, ENDURE, BODY_PRESS, SCARY_FACE, REVENGE, AMNESIA, NASTY_PLOT, FAKE_TEARS, GUARD_SWAP, POWER_SWAP, IMPRISON, SAND_TOMB, ROCK_BLAST, HEX, POLTERGEIST, PHANTOM_FORCE, TOXIC_SPIKES
	; end