	db SABLEYE ; 302

	db  50,  75,  75,  50,  65,  65
  ;  hp  atk  def  spd sat sdf

	db DARK, GHOST ; type
	db 45 ; catch rate
	db 133 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 25 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/sableye/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_SLOW ; growth rate
	dn EGG_HUMANLIKE, EGG_HUMANLIKE ; egg groups

	; tm/hm learnset
	tmhm SIGNAL_BEAM, FOUL_PLAY, DARK_PULSE, KNOCK_OFF, THIEF, SNARL, PAYBACK, FLING, EMBARGO, QUASH, SNATCH, TAUNT, TORMENT, THUNDER_PUNCH, SHOCK_WAVE, DAZZLING_GLEAM, FOCUS_PUNCH, BRICK_BREAK, DRAIN_PUNCH, LOW_SWEEP, POWER_UP_PUNCH, ROCK_SMASH, LOW_KICK, FIRE_PUNCH, SUNNY_DAY, WILL_O_WISP, AERIAL_ACE, SHADOW_BALL, SHADOW_CLAW, SPITE, ICE_PUNCH, ICY_WIND, FACADE, HIDDEN_POWER, ROUND, CUT, SNORE, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, HELPING_HAND, PAIN_SPLIT, PROTECT, PSYCH_UP, SLEEP_TALK, SUBSTITUTE, SWAGGER, POISON_JAB, TOXIC, DREAM_EATER, PSYCHIC, ZEN_HEADBUTT, ALLY_SWITCH, CALM_MIND, GRAVITY, MAGIC_COAT, REST, ROLE_PLAY, TELEKINESIS, TRICK, WONDER_ROOM, ROCK_TOMB, GYRO_BALL, WATER_PULSE, RAIN_DANCE, ENDURE, MEGA_KICK, BODY_SLAM, MEGA_PUNCH, METRONOME, DIG, NASTY_PLOT, RETALIATE, IMPRISON, LASH_OUT, ENCORE, HEX, POLTERGEIST, POWER_GEM
	; end