	db SALAZZLE ; 758

	db  68,  64,  60,  117,  111,  60
  ;  hp  atk  def  spd sat sdf

	db POISON, FIRE ; type
	db 45 ; catch rate
	db 168 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F100 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/salazzle/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_MONSTER, EGG_DRAGON ; egg groups

	; tm/hm learnset
	tmhm LEECH_LIFE, FOUL_PLAY, KNOCK_OFF, THIEF, PAYBACK, FLING, SNATCH, TAUNT, TORMENT, DRAGON_PULSE, DRAGON_CLAW, DRAGON_TAIL, THUNDER_WAVE, OVERHEAT, FIRE_BLAST, HEAT_WAVE, FLAMETHROWER, FLAME_CHARGE, WILL_O_WISP, ACROBATICS, SHADOW_CLAW, FACADE, COVET, HIDDEN_POWER, ROUND, SNORE, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, HELPING_HAND, LASER_FOCUS, PROTECT, SLEEP_TALK, SUBSTITUTE, SWAGGER, GUNK_SHOT, SLUDGE_WAVE, SLUDGE_BOMB, POISON_JAB, VENOSHOCK, TOXIC, REST, IRON_TAIL, ENDURE, SWIFT, FLARE_BLITZ, BREAKING_SWIPE, SCALE_SHOT, NASTY_PLOT, FAKE_TEARS, BEAT_UP, SKITTER_SMACK, DRAGON_DANCE, ENCORE, VENOM_DRENCH, CROSS_POISON, CORROSIVE_GAS
	; end