	db SALANDIT ; 757

	db  48,  44,  40,  77,  71,  40
  ;  hp  atk  def  spd sat sdf

	db POISON, FIRE ; type
	db 120 ; catch rate
	db 64 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F12_5 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/salandit/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_MONSTER, EGG_DRAGON ; egg groups

	; tm/hm learnset
	tmhm LEECH_LIFE, FOUL_PLAY, KNOCK_OFF, THIEF, PAYBACK, FLING, SNATCH, TAUNT, TORMENT, DRAGON_PULSE, DRAGON_CLAW, THUNDER_WAVE, OVERHEAT, FIRE_BLAST, HEAT_WAVE, FLAMETHROWER, FLAME_CHARGE, WILL_O_WISP, SHADOW_CLAW, FACADE, COVET, HIDDEN_POWER, ROUND, SNORE, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, HELPING_HAND, PROTECT, SLEEP_TALK, SUBSTITUTE, SWAGGER, GUNK_SHOT, SLUDGE_WAVE, SLUDGE_BOMB, POISON_JAB, VENOSHOCK, TOXIC, REST, IRON_TAIL, ENDURE, SWIFT, SCALE_SHOT, NASTY_PLOT, BEAT_UP, SKITTER_SMACK, VENOM_DRENCH
	; end