	db SANDYGAST ; 769

	db  55,  55,  80,  15,  70,  45
  ;  hp  atk  def  spd sat sdf

	db GHOST, GROUND ; type
	db 140 ; catch rate
	db 64 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 16 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/sandygast/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_AMORPHOUS, EGG_AMORPHOUS ; egg groups

	; tm/hm learnset
	tmhm INFESTATION, SHADOW_BALL, SPITE, ENERGY_BALL, GIGA_DRAIN, EARTHQUAKE, EARTH_POWER, BULLDOZE, FACADE, HIDDEN_POWER, ROUND, SNORE, FRUSTRATION, RETURN, AFTER_YOU, ATTRACT, BLOCK, CONFIDE, DOUBLE_TEAM, PAIN_SPLIT, PROTECT, RECYCLE, SLEEP_TALK, SUBSTITUTE, SWAGGER, SLUDGE_BOMB, TOXIC, PSYCHIC, GRAVITY, REST, ROLE_PLAY, SKILL_SWAP, TRICK, STONE_EDGE, ROCK_SLIDE, ROCK_TOMB, ROCK_POLISH, SANDSTORM, STEALTH_ROCK, IRON_DEFENSE, ENDURE, SCORCHING_SANDS, AMNESIA, SAND_TOMB, POLTERGEIST
	; end