	db SCIZOR ; 212

	db  70,  130,  100,  65,  55,  80
  ;  hp  atk  def  spd sat sdf

	db BUG, STEEL ; type
	db 25 ; catch rate
	db 175 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 25 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/scizor/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_BUG, EGG_BUG ; egg groups

	; tm/hm learnset
	tmhm X_SCISSOR, U_TURN, BUG_BITE, STRUGGLE_BUG, KNOCK_OFF, BRUTAL_SWING, THIEF, FLING, SUPERPOWER, BRICK_BREAK, ROCK_SMASH, SUNNY_DAY, AERIAL_ACE, ACROBATICS, DEFOG, ROOST, TAILWIND, GIGA_IMPACT, HYPER_BEAM, STRENGTH, FACADE, HIDDEN_POWER, ROUND, CUT, SNORE, FALSE_SWIPE, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, LASER_FOCUS, PROTECT, SAFEGUARD, SLEEP_TALK, SUBSTITUTE, SWAGGER, SWORDS_DANCE, VENOSHOCK, TOXIC, LIGHT_SCREEN, REST, SANDSTORM, FLASH_CANNON, IRON_HEAD, STEEL_WING, IRON_DEFENSE, RAIN_DANCE, ENDURE, STEEL_BEAM, FOCUS_ENERGY, SWIFT, AGILITY, REVERSAL, BATON_PASS, AIR_SLASH, DUAL_WINGBEAT, BUG_BUZZ, PSYCHO_CUT, SAND_TOMB, CROSS_POISON
	; end