	db SCOLIPEDE ; 545

	db  60,  100,  89,  112,  55,  69
  ;  hp  atk  def  spd sat sdf

	db BUG, POISON ; type
	db 45 ; catch rate
	db 218 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/scolipede/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_SLOW ; growth rate
	dn EGG_BUG, EGG_BUG ; egg groups

	; tm/hm learnset
	tmhm X_SCISSOR, SIGNAL_BEAM, BUG_BITE, STRUGGLE_BUG, INFESTATION, THROAT_CHOP, PAYBACK, SNATCH, SUPERPOWER, ROCK_SMASH, SUNNY_DAY, SOLAR_BEAM, EARTHQUAKE, STOMPING_TANTRUM, BULLDOZE, GIGA_IMPACT, HYPER_BEAM, STRENGTH, FACADE, HIDDEN_POWER, ROUND, CUT, SNORE, ENDEAVOR, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, PROTECT, SLEEP_TALK, SUBSTITUTE, SWAGGER, SWORDS_DANCE, SLUDGE_BOMB, POISON_JAB, VENOSHOCK, TOXIC, REST, ROCK_SLIDE, ROCK_TOMB, IRON_TAIL, SMART_STRIKE, GYRO_BALL, IRON_DEFENSE, AQUA_TAIL, ENDURE, STEEL_ROLLER, SCREECH, AGILITY, BATON_PASS, DIG, SKITTER_SMACK, MEGAHORN, SPIKES, HEX, VENOM_DRENCH, PIN_MISSILE, CROSS_POISON, TOXIC_SPIKES
	; end