	db SCYTHER ; 123

	db  70,  110,  80,  105,  55,  80
  ;  hp  atk  def  spd sat sdf

	db BUG, FLYING ; type
	db 45 ; catch rate
	db 100 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 25 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/scyther/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_BUG, EGG_BUG ; egg groups

	; tm/hm learnset
	tmhm X_SCISSOR, U_TURN, BUG_BITE, STRUGGLE_BUG, KNOCK_OFF, BRUTAL_SWING, THIEF, BRICK_BREAK, ROCK_SMASH, SUNNY_DAY, AERIAL_ACE, ACROBATICS, DEFOG, ROOST, TAILWIND, GIGA_IMPACT, HYPER_BEAM, FACADE, HIDDEN_POWER, ROUND, CUT, SNORE, FALSE_SWIPE, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, LASER_FOCUS, PROTECT, SAFEGUARD, SLEEP_TALK, SUBSTITUTE, SWAGGER, SWORDS_DANCE, TOXIC, LIGHT_SCREEN, REST, STEEL_WING, RAIN_DANCE, ENDURE, FOCUS_ENERGY, SWIFT, AGILITY, REVERSAL, BATON_PASS, AIR_SLASH, DUAL_WINGBEAT, BUG_BUZZ, PSYCHO_CUT, CROSS_POISON
	; end