	db SEISMITOAD ; 537

	db  105,  95,  75,  74,  85,  75
  ;  hp  atk  def  spd sat sdf

	db WATER, GROUND ; type
	db 45 ; catch rate
	db 229 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/seismitoad/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_SLOW ; growth rate
	dn EGG_WATER1, EGG_WATER1 ; egg groups

	; tm/hm learnset
	tmhm INFESTATION, KNOCK_OFF, PAYBACK, FLING, FOCUS_PUNCH, FOCUS_BLAST, BRICK_BREAK, DRAIN_PUNCH, POWER_UP_PUNCH, ROCK_SMASH, LOW_KICK, BOUNCE, GRASS_KNOT, EARTHQUAKE, EARTH_POWER, STOMPING_TANTRUM, BULLDOZE, ICE_PUNCH, ICY_WIND, HAIL, GIGA_IMPACT, HYPER_BEAM, HYPER_VOICE, UPROAR, STRENGTH, FACADE, HIDDEN_POWER, ROUND, SNORE, ECHOED_VOICE, ENDEAVOR, FRUSTRATION, RETURN, AFTER_YOU, ATTRACT, CONFIDE, DOUBLE_TEAM, PROTECT, SLEEP_TALK, SUBSTITUTE, SWAGGER, SLUDGE_WAVE, SLUDGE_BOMB, POISON_JAB, VENOSHOCK, GASTRO_ACID, TOXIC, REST, ROCK_SLIDE, ROCK_TOMB, STEALTH_ROCK, SURF, LIQUIDATION, DIVE, SCALD, WATER_PULSE, RAIN_DANCE, ENDURE, MEGA_KICK, MEGA_PUNCH, SCREECH, MUD_SHOT, MUDDY_WATER, WEATHER_BALL, HYDRO_PUMP, DIG, VENOM_DRENCH, POWER_WHIP
	; end