	db SHARPEDO ; 319

	db  70,  120,  40,  95,  95,  40
  ;  hp  atk  def  spd sat sdf

	db WATER, DARK ; type
	db 60 ; catch rate
	db 161 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/sharpedo/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_SLOW ; growth rate
	dn EGG_WATER2, EGG_WATER2 ; egg groups

	; tm/hm learnset
	tmhm DARK_PULSE, THIEF, SNARL, PAYBACK, TAUNT, TORMENT, ROCK_SMASH, BOUNCE, SPITE, EARTHQUAKE, BULLDOZE, BLIZZARD, ICE_BEAM, ICY_WIND, HAIL, GIGA_IMPACT, HYPER_BEAM, UPROAR, STRENGTH, FACADE, HIDDEN_POWER, ROUND, SNORE, FRUSTRATION, RETURN, SUPER_FANG, ATTRACT, CONFIDE, DOUBLE_TEAM, PROTECT, ROAR, SLEEP_TALK, SUBSTITUTE, SWAGGER, POISON_JAB, TOXIC, ZEN_HEADBUTT, REST, ROCK_TOMB, SURF, LIQUIDATION, DIVE, SCALD, WATERFALL, WATER_PULSE, RAIN_DANCE, ENDURE, SCREECH, FOCUS_ENERGY, SWIFT, SCARY_FACE, AGILITY, WHIRLPOOL, HYDRO_PUMP, SCALE_SHOT, CRUNCH, ICE_FANG, PSYCHIC_FANGS, RETALIATE, CLOSE_COMBAT, FLIP_TURN, BRINE, AVALANCHE
	; end