	db SHIFTRY ; 275

	db  90,  100,  60,  80,  90,  60
  ;  hp  atk  def  spd sat sdf

	db GRASS, DARK ; type
	db 45 ; catch rate
	db 216 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 15 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/shiftry/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_SLOW ; growth rate
	dn EGG_FIELD, EGG_GRASS ; egg groups

	; tm/hm learnset
	tmhm X_SCISSOR, FOUL_PLAY, DARK_PULSE, THROAT_CHOP, KNOCK_OFF, BRUTAL_SWING, THIEF, SNARL, PAYBACK, FLING, EMBARGO, TORMENT, FOCUS_BLAST, BRICK_BREAK, LOW_SWEEP, POWER_UP_PUNCH, ROCK_SMASH, LOW_KICK, HEAT_WAVE, SUNNY_DAY, BOUNCE, AERIAL_ACE, DEFOG, TAILWIND, SHADOW_BALL, SPITE, SOLAR_BEAM, ENERGY_BALL, SEED_BOMB, GIGA_DRAIN, GRASS_KNOT, SYNTHESIS, WORRY_SEED, ICY_WIND, EXPLOSION, GIGA_IMPACT, HYPER_BEAM, STRENGTH, FACADE, HIDDEN_POWER, ROUND, CUT, SNORE, FALSE_SWIPE, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, NATURE_POWER, PROTECT, PSYCH_UP, SLEEP_TALK, SUBSTITUTE, SWAGGER, SWORDS_DANCE, TOXIC, REST, ROCK_SLIDE, ROCK_TOMB, ENDURE, MEGA_KICK, BODY_SLAM, SELF_DESTRUCT, SCREECH, SWIFT, SOLAR_BLADE, ASSURANCE, GRASSY_GLIDE, LEAF_STORM, GRASSY_TERRAIN, BULLET_SEED, REVENGE, AIR_SLASH, DIG, AMNESIA, NASTY_PLOT, RETALIATE, HURRICANE, POWER_SWAP, BEAT_UP, LASH_OUT, LEAF_BLADE
	; end