	db SIGILYPH ; 561

	db  72,  58,  80,  97,  103,  80
  ;  hp  atk  def  spd sat sdf

	db PSYCHIC, FLYING ; type
	db 45 ; catch rate
	db 172 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/sigilyph/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_FLYING, EGG_FLYING ; egg groups

	; tm/hm learnset
	tmhm SIGNAL_BEAM, DARK_PULSE, THIEF, SHOCK_WAVE, CHARGE_BEAM, THUNDER_WAVE, DAZZLING_GLEAM, HEAT_WAVE, SKY_ATTACK, FLY, AERIAL_ACE, DEFOG, ROOST, TAILWIND, SHADOW_BALL, SOLAR_BEAM, ENERGY_BALL, ICE_BEAM, ICY_WIND, GIGA_IMPACT, HYPER_BEAM, FACADE, HIDDEN_POWER, ROUND, SNORE, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, PROTECT, PSYCH_UP, SAFEGUARD, SLEEP_TALK, SUBSTITUTE, SWAGGER, TOXIC, DREAM_EATER, PSYCHIC, PSYSHOCK, ZEN_HEADBUTT, CALM_MIND, GRAVITY, LIGHT_SCREEN, MAGIC_COAT, MAGIC_ROOM, REFLECT, REST, SKILL_SWAP, TELEKINESIS, TRICK, TRICK_ROOM, SMACK_DOWN, FLASH_CANNON, STEEL_WING, RAIN_DANCE, ENDURE, SWIFT, AIR_SLASH, DUAL_WINGBEAT, EXPANDING_FORCE, STORED_POWER, POWER_SWAP, FUTURE_SIGHT, IMPRISON, PSYCHO_CUT, COSMIC_POWER, SPEED_SWAP
	; end