	db SNORLAX ; 143

	db  160,  110,  65,  30,  65,  110
  ;  hp  atk  def  spd sat sdf

	db NORMAL, NORMAL ; type
	db 25 ; catch rate
	db 189 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F12_5 ; gender ratio
	db 100 ; unknown 1
	db 40 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/snorlax/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_SLOW ; growth rate
	dn EGG_MONSTER, EGG_MONSTER ; egg groups

	; tm/hm learnset
	tmhm FLING, SNATCH, OUTRAGE, THUNDER, THUNDERBOLT, WILD_CHARGE, THUNDER_PUNCH, SHOCK_WAVE, FOCUS_PUNCH, FOCUS_BLAST, SUPERPOWER, BRICK_BREAK, POWER_UP_PUNCH, ROCK_SMASH, FIRE_BLAST, FLAMETHROWER, FIRE_PUNCH, SUNNY_DAY, SHADOW_BALL, SOLAR_BEAM, SEED_BOMB, EARTHQUAKE, STOMPING_TANTRUM, BULLDOZE, BLIZZARD, ICE_BEAM, ICE_PUNCH, ICY_WIND, GIGA_IMPACT, HYPER_BEAM, LAST_RESORT, HYPER_VOICE, UPROAR, STRENGTH, FACADE, COVET, HIDDEN_POWER, ROUND, SNORE, FRUSTRATION, RETURN, AFTER_YOU, ATTRACT, BLOCK, CONFIDE, DOUBLE_TEAM, PROTECT, RECYCLE, SLEEP_TALK, SUBSTITUTE, SWAGGER, WORK_UP, GUNK_SHOT, TOXIC, PSYCHIC, ZEN_HEADBUTT, REFLECT, REST, ROCK_SLIDE, ROCK_TOMB, SMACK_DOWN, SANDSTORM, IRON_HEAD, SURF, WATER_PULSE, RAIN_DANCE, ENDURE, MEGA_KICK, BODY_SLAM, HEAVY_SLAM, SELF_DESTRUCT, DARKEST_LARIAT, STEEL_ROLLER, BODY_PRESS, MEGA_PUNCH, HIGH_HORSEPOWER, SCREECH, WHIRLPOOL, HYDRO_PUMP, METRONOME, CRUNCH, AMNESIA, RETALIATE, CHARM, HEAT_CRASH, ENCORE, PAY_DAY, TERRAIN_PULSE
	; end