	db SPINDA ; 327

	db  60,  60,  60,  60,  60,  60
  ;  hp  atk  def  spd sat sdf

	db NORMAL, NORMAL ; type
	db 255 ; catch rate
	db 126 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 15 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/spinda/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_FAST ; growth rate
	dn EGG_FIELD, EGG_HUMANLIKE ; egg groups

	; tm/hm learnset
	tmhm THIEF, FLING, SNATCH, WILD_CHARGE, THUNDER_PUNCH, SHOCK_WAVE, FOCUS_PUNCH, BRICK_BREAK, DRAIN_PUNCH, POWER_UP_PUNCH, ROCK_SMASH, LOW_KICK, FIRE_PUNCH, SUNNY_DAY, SHADOW_BALL, STOMPING_TANTRUM, ICE_PUNCH, ICY_WIND, LAST_RESORT, HYPER_VOICE, UPROAR, STRENGTH, FACADE, COVET, HIDDEN_POWER, ROUND, SNORE, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, HELPING_HAND, PROTECT, PSYCH_UP, RECYCLE, SAFEGUARD, SLEEP_TALK, SUBSTITUTE, SWAGGER, WORK_UP, TOXIC, DREAM_EATER, PSYCHIC, ZEN_HEADBUTT, CALM_MIND, REST, ROLE_PLAY, SKILL_SWAP, TRICK, TRICK_ROOM, ROCK_SLIDE, ROCK_TOMB, WATER_PULSE, RAIN_DANCE, ENDURE, SWIFT, DIG, RETALIATE
	; end