	db STAKATAKA ; 805

	db  61,  131,  211,  13,  53,  101
  ;  hp  atk  def  spd sat sdf

	db ROCK, STEEL ; type
	db 30 ; catch rate
	db 257 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_UNKNOWN ; gender ratio
	db 100 ; unknown 1
	db 120 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/stakataka/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_SLOW ; growth rate
	dn EGG_NONE, EGG_NONE ; egg groups

	; tm/hm learnset
	tmhm INFESTATION, BRUTAL_SWING, MAGNET_RISE, SUPERPOWER, EARTHQUAKE, STOMPING_TANTRUM, BULLDOZE, GIGA_IMPACT, FACADE, HIDDEN_POWER, ROUND, SNORE, BIND, FRUSTRATION, RETURN, BLOCK, PROTECT, RECYCLE, SAFEGUARD, SLEEP_TALK, SUBSTITUTE, TOXIC, ZEN_HEADBUTT, ALLY_SWITCH, GRAVITY, LIGHT_SCREEN, MAGIC_COAT, MAGIC_ROOM, REFLECT, REST, ROLE_PLAY, SKILL_SWAP, TELEKINESIS, TRICK_ROOM, WONDER_ROOM, STONE_EDGE, ROCK_SLIDE, ROCK_TOMB, SMACK_DOWN, ROCK_POLISH, SANDSTORM, STEALTH_ROCK, FLASH_CANNON, IRON_HEAD, GYRO_BALL, IRON_DEFENSE, ENDURE, STEEL_BEAM, MEGA_KICK, BODY_SLAM, HEAVY_SLAM, STEEL_ROLLER, BODY_PRESS, HIGH_HORSEPOWER, METEOR_BEAM, ROCK_BLAST, HEAT_CRASH
	; end