	db STARMIE ; 121

	db  60,  75,  85,  115,  100,  85
  ;  hp  atk  def  spd sat sdf

	db WATER, PSYCHIC ; type
	db 60 ; catch rate
	db 182 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_UNKNOWN ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/starmie/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_SLOW ; growth rate
	dn EGG_WATER3, EGG_WATER3 ; egg groups

	; tm/hm learnset
	tmhm SIGNAL_BEAM, THUNDER, THUNDERBOLT, THUNDER_WAVE, DAZZLING_GLEAM, GRASS_KNOT, BLIZZARD, ICE_BEAM, ICY_WIND, HAIL, GIGA_IMPACT, HYPER_BEAM, FACADE, HIDDEN_POWER, ROUND, SNORE, FRUSTRATION, RETURN, CONFIDE, DOUBLE_TEAM, PAIN_SPLIT, PROTECT, PSYCH_UP, RECYCLE, SLEEP_TALK, SUBSTITUTE, SWAGGER, TOXIC, DREAM_EATER, PSYCHIC, PSYSHOCK, ALLY_SWITCH, GRAVITY, LIGHT_SCREEN, MAGIC_COAT, REFLECT, REST, SKILL_SWAP, TELEKINESIS, TRICK, TRICK_ROOM, WONDER_ROOM, FLASH_CANNON, GYRO_BALL, SURF, DIVE, SCALD, WATERFALL, WATER_PULSE, RAIN_DANCE, ENDURE, SWIFT, AGILITY, WHIRLPOOL, HYDRO_PUMP, EXPANDING_FORCE, PSYCHO_CUT, METEOR_BEAM, FLIP_TURN, BRINE, POWER_GEM, AVALANCHE, TRI_ATTACK, COSMIC_POWER
	; end