	db STUNKY ; 434

	db  63,  63,  47,  74,  41,  41
  ;  hp  atk  def  spd sat sdf

	db POISON, DARK ; type
	db 225 ; catch rate
	db 66 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/stunky/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_FIELD, EGG_FIELD ; egg groups

	; tm/hm learnset
	tmhm FOUL_PLAY, DARK_PULSE, THROAT_CHOP, THIEF, SNARL, PAYBACK, SNATCH, TAUNT, TORMENT, ROCK_SMASH, FIRE_BLAST, FLAMETHROWER, SUNNY_DAY, DEFOG, SHADOW_BALL, SHADOW_CLAW, EXPLOSION, FACADE, HIDDEN_POWER, ROUND, CUT, SNORE, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, PROTECT, ROAR, SLEEP_TALK, SUBSTITUTE, SWAGGER, SLUDGE_BOMB, VENOSHOCK, TOXIC, REST, IRON_TAIL, RAIN_DANCE, ENDURE, SCREECH, FOCUS_ENERGY, SWIFT, ASSURANCE, SCARY_FACE, CRUNCH, TAIL_SLAP, DIG, NASTY_PLOT, PLAY_ROUGH, LASH_OUT, HEX, VENOM_DRENCH, CORROSIVE_GAS
	; end