	db TAUROS ; 128

	db  75,  100,  95,  110,  40,  70
  ;  hp  atk  def  spd sat sdf

	db NORMAL, NORMAL ; type
	db 45 ; catch rate
	db 172 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F0 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/tauros/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_SLOW ; growth rate
	dn EGG_FIELD, EGG_FIELD ; egg groups

	; tm/hm learnset
	tmhm THROAT_CHOP, PAYBACK, OUTRAGE, THUNDER, THUNDERBOLT, WILD_CHARGE, SHOCK_WAVE, ROCK_SMASH, FIRE_BLAST, FLAMETHROWER, SUNNY_DAY, SPITE, SOLAR_BEAM, EARTHQUAKE, STOMPING_TANTRUM, BULLDOZE, BLIZZARD, ICE_BEAM, ICY_WIND, GIGA_IMPACT, HYPER_BEAM, UPROAR, STRENGTH, FACADE, HIDDEN_POWER, ROUND, SNORE, ENDEAVOR, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, HELPING_HAND, PROTECT, SLEEP_TALK, SUBSTITUTE, SWAGGER, WORK_UP, TOXIC, ZEN_HEADBUTT, REST, ROLE_PLAY, STONE_EDGE, ROCK_SLIDE, ROCK_TOMB, SANDSTORM, IRON_TAIL, IRON_HEAD, SMART_STRIKE, SURF, WATER_PULSE, RAIN_DANCE, ENDURE, BODY_SLAM, HIGH_HORSEPOWER, ASSURANCE, SCARY_FACE, REVERSAL, REVENGE, WHIRLPOOL, RETALIATE, LASH_OUT, MEGAHORN, CLOSE_COMBAT
	; end