	db TENTACRUEL ; 73

	db  80,  70,  65,  100,  80,  120
  ;  hp  atk  def  spd sat sdf

	db WATER, POISON ; type
	db 60 ; catch rate
	db 180 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/tentacruel/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_SLOW ; growth rate
	dn EGG_WATER3, EGG_WATER3 ; egg groups

	; tm/hm learnset
	tmhm INFESTATION, KNOCK_OFF, BRUTAL_SWING, THIEF, PAYBACK, DAZZLING_GLEAM, GIGA_DRAIN, BLIZZARD, ICE_BEAM, ICY_WIND, HAIL, GIGA_IMPACT, HYPER_BEAM, FACADE, HIDDEN_POWER, ROUND, CUT, SNORE, BIND, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, PROTECT, SAFEGUARD, SLEEP_TALK, SUBSTITUTE, SWAGGER, SWORDS_DANCE, SLUDGE_WAVE, SLUDGE_BOMB, POISON_JAB, VENOSHOCK, TOXIC, MAGIC_COAT, REFLECT, REST, SURF, DIVE, SCALD, WATERFALL, WATER_PULSE, RAIN_DANCE, ENDURE, SCREECH, MUDDY_WATER, WHIRLPOOL, HYDRO_PUMP, HEX, VENOM_DRENCH, BRINE, CROSS_POISON, TOXIC_SPIKES, CORROSIVE_GAS
	; end