	db TOGEDEMARU ; 777

	db  65,  98,  63,  96,  40,  73
  ;  hp  atk  def  spd sat sdf

	db ELECTRIC, STEEL ; type
	db 180 ; catch rate
	db 152 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 12 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/togedemaru/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_FIELD, EGG_FAIRY ; egg groups

	; tm/hm learnset
	tmhm U_TURN, THIEF, PAYBACK, FLING, THUNDER, THUNDERBOLT, WILD_CHARGE, VOLT_SWITCH, SHOCK_WAVE, ELECTROWEB, CHARGE_BEAM, MAGNET_RISE, THUNDER_WAVE, BOUNCE, GRASS_KNOT, GIGA_IMPACT, HYPER_BEAM, LAST_RESORT, FACADE, COVET, HIDDEN_POWER, ROUND, SNORE, ENDEAVOR, FRUSTRATION, RETURN, SUPER_FANG, AFTER_YOU, ATTRACT, CONFIDE, DOUBLE_TEAM, HELPING_HAND, PROTECT, SLEEP_TALK, SUBSTITUTE, SWAGGER, WORK_UP, POISON_JAB, TOXIC, ZEN_HEADBUTT, GRAVITY, REFLECT, REST, ROLE_PLAY, IRON_TAIL, IRON_HEAD, GYRO_BALL, ENDURE, STEEL_BEAM, ELECTRIC_TERRAIN, STEEL_ROLLER, SWIFT, ASSURANCE, AGILITY, REVERSAL, ELECTRO_BALL, RISING_VOLTAGE, EERIE_IMPULSE, ENCORE, PIN_MISSILE
	; end