	db TOXAPEX ; 748

	db  50,  63,  152,  35,  53,  142
  ;  hp  atk  def  spd sat sdf

	db POISON, WATER ; type
	db 75 ; catch rate
	db 173 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/toxapex/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_WATER1, EGG_WATER1 ; egg groups

	; tm/hm learnset
	tmhm INFESTATION, KNOCK_OFF, PAYBACK, SNATCH, SPITE, BLIZZARD, ICE_BEAM, FROST_BREATH, ICY_WIND, HAIL, FACADE, COVET, HIDDEN_POWER, ROUND, SNORE, FRUSTRATION, RETURN, AFTER_YOU, ATTRACT, BLOCK, CONFIDE, DOUBLE_TEAM, PAIN_SPLIT, PROTECT, SAFEGUARD, SLEEP_TALK, SUBSTITUTE, SWAGGER, GUNK_SHOT, SLUDGE_WAVE, SLUDGE_BOMB, POISON_JAB, VENOSHOCK, GASTRO_ACID, TOXIC, LIGHT_SCREEN, MAGIC_COAT, REST, SMACK_DOWN, IRON_DEFENSE, SURF, LIQUIDATION, SCALD, WATER_PULSE, RAIN_DANCE, ENDURE, MUD_SHOT, MUDDY_WATER, HYDRO_PUMP, HEX, VENOM_DRENCH, BRINE, PIN_MISSILE, CROSS_POISON, TOXIC_SPIKES
	; end