	db TYRANTRUM ; 697

	db  82,  121,  119,  71,  69,  59
  ;  hp  atk  def  spd sat sdf

	db ROCK, DRAGON ; type
	db 45 ; catch rate
	db 182 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F12_5 ; gender ratio
	db 100 ; unknown 1
	db 30 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/tyrantrum/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_MONSTER, EGG_DRAGON ; egg groups

	; tm/hm learnset
	tmhm DARK_PULSE, BRUTAL_SWING, DRACO_METEOR, OUTRAGE, DRAGON_PULSE, DRAGON_CLAW, DRAGON_TAIL, SUPERPOWER, BRICK_BREAK, ROCK_SMASH, SUNNY_DAY, AERIAL_ACE, EARTHQUAKE, EARTH_POWER, STOMPING_TANTRUM, BULLDOZE, GIGA_IMPACT, HYPER_BEAM, HYPER_VOICE, STRENGTH, FACADE, HIDDEN_POWER, ROUND, SNORE, FRUSTRATION, RETURN, ATTRACT, BLOCK, CONFIDE, DOUBLE_TEAM, PROTECT, ROAR, SLEEP_TALK, SUBSTITUTE, SWAGGER, TOXIC, ZEN_HEADBUTT, REST, STONE_EDGE, ROCK_SLIDE, ROCK_TOMB, ROCK_POLISH, SANDSTORM, STEALTH_ROCK, IRON_TAIL, IRON_HEAD, IRON_DEFENSE, ENDURE, BODY_SLAM, HIGH_HORSEPOWER, ASSURANCE, SCARY_FACE, FIRE_FANG, BREAKING_SWIPE, SCALE_SHOT, CRUNCH, DIG, THUNDER_FANG, ICE_FANG, PSYCHIC_FANGS, PLAY_ROUGH, LASH_OUT, CHARM, METEOR_BEAM, ROCK_BLAST, DRAGON_DANCE, CLOSE_COMBAT
	; end