	db UMBREON ; 197

	db  95,  65,  110,  65,  60,  130
  ;  hp  atk  def  spd sat sdf

	db DARK, DARK ; type
	db 45 ; catch rate
	db 184 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F12_5 ; gender ratio
	db 100 ; unknown 1
	db 35 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/umbreon/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_FIELD, EGG_FIELD ; egg groups

	; tm/hm learnset
	tmhm FOUL_PLAY, DARK_PULSE, THROAT_CHOP, THIEF, SNARL, PAYBACK, SNATCH, TAUNT, TORMENT, SUNNY_DAY, SHADOW_BALL, SPITE, GIGA_IMPACT, HYPER_BEAM, LAST_RESORT, HYPER_VOICE, FACADE, COVET, HIDDEN_POWER, ROUND, CUT, SNORE, ECHOED_VOICE, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, HEAL_BELL, HELPING_HAND, LASER_FOCUS, PROTECT, PSYCH_UP, SLEEP_TALK, SUBSTITUTE, SWAGGER, WORK_UP, TOXIC, DREAM_EATER, PSYCHIC, REST, WONDER_ROOM, IRON_TAIL, RAIN_DANCE, ENDURE, BODY_SLAM, SCREECH, FOCUS_ENERGY, SWIFT, ASSURANCE, BATON_PASS, WEATHER_BALL, CRUNCH, DIG, RETALIATE, FAKE_TEARS, STORED_POWER, GUARD_SWAP, LASH_OUT, CHARM, PAY_DAY
	; end