	db UXIE ; 480

	db  75,  75,  130,  95,  75,  130
  ;  hp  atk  def  spd sat sdf

	db PSYCHIC, PSYCHIC ; type
	db 3 ; catch rate
	db 261 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_UNKNOWN ; gender ratio
	db 100 ; unknown 1
	db 80 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/uxie/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_SLOW ; growth rate
	dn EGG_NONE, EGG_NONE ; egg groups

	; tm/hm learnset
	tmhm SIGNAL_BEAM, U_TURN, FOUL_PLAY, KNOCK_OFF, FLING, THUNDER, THUNDERBOLT, THUNDER_PUNCH, SHOCK_WAVE, CHARGE_BEAM, THUNDER_WAVE, DAZZLING_GLEAM, DRAIN_PUNCH, POWER_UP_PUNCH, FIRE_PUNCH, SUNNY_DAY, ACROBATICS, SHADOW_BALL, SOLAR_BEAM, ENERGY_BALL, GIGA_DRAIN, GRASS_KNOT, ICE_PUNCH, GIGA_IMPACT, HYPER_BEAM, FACADE, HIDDEN_POWER, ROUND, SNORE, FRUSTRATION, RETURN, CONFIDE, DOUBLE_TEAM, HEAL_BELL, HELPING_HAND, LASER_FOCUS, PROTECT, PSYCH_UP, RECYCLE, SAFEGUARD, SLEEP_TALK, SUBSTITUTE, SWAGGER, TOXIC, DREAM_EATER, PSYCHIC, PSYSHOCK, ZEN_HEADBUTT, ALLY_SWITCH, CALM_MIND, LIGHT_SCREEN, MAGIC_COAT, MAGIC_ROOM, REFLECT, REST, ROLE_PLAY, SKILL_SWAP, TELEKINESIS, TRICK, TRICK_ROOM, WONDER_ROOM, SANDSTORM, STEALTH_ROCK, IRON_TAIL, WATER_PULSE, RAIN_DANCE, ENDURE, SWIFT, BATON_PASS, METRONOME, AMNESIA, NASTY_PLOT, EXPANDING_FORCE, STORED_POWER, FUTURE_SIGHT, IMPRISON, PSYCHO_CUT, PLAY_ROUGH, ENCORE, DRAINING_KISS, TRI_ATTACK
	; end