	db VIKAVOLT ; 738

	db  77,  70,  90,  43,  145,  75
  ;  hp  atk  def  spd sat sdf

	db BUG, ELECTRIC ; type
	db 45 ; catch rate
	db 225 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 16 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/vikavolt/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_BUG, EGG_BUG ; egg groups

	; tm/hm learnset
	tmhm X_SCISSOR, SIGNAL_BEAM, BUG_BITE, THUNDER, THUNDERBOLT, WILD_CHARGE, VOLT_SWITCH, SHOCK_WAVE, ELECTROWEB, CHARGE_BEAM, MAGNET_RISE, THUNDER_WAVE, FLY, SKY_DROP, ACROBATICS, ROOST, SOLAR_BEAM, ENERGY_BALL, GIGA_IMPACT, HYPER_BEAM, FACADE, HIDDEN_POWER, ROUND, SNORE, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, LASER_FOCUS, PROTECT, SLEEP_TALK, SUBSTITUTE, SWAGGER, POISON_JAB, TOXIC, LIGHT_SCREEN, REST, FLASH_CANNON, IRON_DEFENSE, RAIN_DANCE, ENDURE, SCREECH, MUD_SHOT, AGILITY, ELECTRO_BALL, AIR_SLASH, CRUNCH, DIG, DUAL_WINGBEAT, BUG_BUZZ, SKITTER_SMACK, RISING_VOLTAGE, EERIE_IMPULSE
	; end