	db VOLCANION ; 721

	db  100,  70,  120,  80,  130,  130
  ;  hp  atk  def  spd sat sdf

	db FIRE, WATER ; type
	db 3 ; catch rate
	db 270 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_UNKNOWN ; gender ratio
	db 100 ; unknown 1
	db 120 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/volcanion/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_SLOW ; growth rate
	dn EGG_NONE, EGG_NONE ; egg groups

	; tm/hm learnset
	tmhm FLING, FOCUS_BLAST, SUPERPOWER, BRICK_BREAK, ROCK_SMASH, OVERHEAT, FIRE_BLAST, HEAT_WAVE, FLAMETHROWER, FLAME_CHARGE, SUNNY_DAY, WILL_O_WISP, DEFOG, SOLAR_BEAM, EARTHQUAKE, EARTH_POWER, STOMPING_TANTRUM, BULLDOZE, EXPLOSION, GIGA_IMPACT, HYPER_BEAM, STRENGTH, FACADE, HIDDEN_POWER, ROUND, CUT, SNORE, FRUSTRATION, RETURN, CONFIDE, DOUBLE_TEAM, PROTECT, ROAR, SLEEP_TALK, SUBSTITUTE, SWAGGER, SLUDGE_WAVE, SLUDGE_BOMB, TOXIC, REST, STONE_EDGE, ROCK_SLIDE, SMACK_DOWN, SANDSTORM, FLASH_CANNON, GYRO_BALL, LIQUIDATION, SCALD, WATER_PULSE, RAIN_DANCE, ENDURE, BODY_SLAM, HEAVY_SLAM, SELF_DESTRUCT, BODY_PRESS, FOCUS_ENERGY, SCARY_FACE, MUD_SHOT, FLARE_BLITZ, SCORCHING_SANDS, FIRE_SPIN, WEATHER_BALL, HYDRO_PUMP, THUNDER_FANG, HEAT_CRASH, MISTY_TERRAIN
	; end