	db WEAVILE ; 461

	db  70,  120,  65,  125,  45,  85
  ;  hp  atk  def  spd sat sdf

	db DARK, ICE ; type
	db 45 ; catch rate
	db 179 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/weavile/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_SLOW ; growth rate
	dn EGG_FIELD, EGG_FIELD ; egg groups

	; tm/hm learnset
	tmhm X_SCISSOR, FOUL_PLAY, DARK_PULSE, THROAT_CHOP, KNOCK_OFF, THIEF, SNARL, PAYBACK, FLING, EMBARGO, SNATCH, TAUNT, TORMENT, FOCUS_PUNCH, FOCUS_BLAST, BRICK_BREAK, LOW_SWEEP, POWER_UP_PUNCH, ROCK_SMASH, LOW_KICK, SUNNY_DAY, AERIAL_ACE, SHADOW_BALL, SHADOW_CLAW, SPITE, BLIZZARD, ICE_BEAM, ICE_PUNCH, ICY_WIND, HAIL, GIGA_IMPACT, HYPER_BEAM, STRENGTH, FACADE, HIDDEN_POWER, ROUND, CUT, SNORE, FALSE_SWIPE, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, LASER_FOCUS, PROTECT, PSYCH_UP, SLEEP_TALK, SUBSTITUTE, SWAGGER, SWORDS_DANCE, POISON_JAB, TOXIC, DREAM_EATER, CALM_MIND, REFLECT, REST, IRON_TAIL, SURF, RAIN_DANCE, ENDURE, MEGA_KICK, MEGA_PUNCH, SCREECH, SWIFT, ASSURANCE, AGILITY, REVENGE, WHIRLPOOL, ICICLE_SPEAR, DIG, NASTY_PLOT, RETALIATE, FAKE_TEARS, PSYCHO_CUT, BEAT_UP, LASH_OUT, AVALANCHE, TRIPLE_AXEL
	; end