	db WHIMSICOTT ; 547

	db  60,  67,  85,  116,  77,  75
  ;  hp  atk  def  spd sat sdf

	db GRASS, FAIRY ; type
	db 75 ; catch rate
	db 168 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/whimsicott/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_FAIRY, EGG_GRASS ; egg groups

	; tm/hm learnset
	tmhm U_TURN, KNOCK_OFF, THIEF, FLING, TAUNT, DAZZLING_GLEAM, SUNNY_DAY, DEFOG, TAILWIND, SHADOW_BALL, SOLAR_BEAM, ENERGY_BALL, SEED_BOMB, GIGA_DRAIN, GRASS_KNOT, WORRY_SEED, GIGA_IMPACT, HYPER_BEAM, FACADE, COVET, HIDDEN_POWER, ROUND, SNORE, ENDEAVOR, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, HELPING_HAND, NATURE_POWER, PROTECT, SAFEGUARD, SLEEP_TALK, SUBSTITUTE, SWAGGER, TOXIC, DREAM_EATER, PSYCHIC, LIGHT_SCREEN, REST, TRICK_ROOM, ENDURE, SWIFT, GRASSY_GLIDE, GRASSY_TERRAIN, FAKE_TEARS, HURRICANE, PLAY_ROUGH, BEAT_UP, CHARM, ENCORE, MISTY_TERRAIN
	; end