	db WIGGLYTUFF ; 40

	db  140,  70,  45,  45,  85,  50
  ;  hp  atk  def  spd sat sdf

	db NORMAL, FAIRY ; type
	db 50 ; catch rate
	db 196 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F75 ; gender ratio
	db 100 ; unknown 1
	db 10 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/wigglytuff/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_FAST ; growth rate
	dn EGG_FAIRY, EGG_FAIRY ; egg groups

	; tm/hm learnset
	tmhm KNOCK_OFF, FLING, SNATCH, THUNDER, THUNDERBOLT, WILD_CHARGE, THUNDER_PUNCH, SHOCK_WAVE, CHARGE_BEAM, THUNDER_WAVE, DAZZLING_GLEAM, FOCUS_PUNCH, FOCUS_BLAST, BRICK_BREAK, DRAIN_PUNCH, POWER_UP_PUNCH, FIRE_BLAST, FLAMETHROWER, FIRE_PUNCH, SUNNY_DAY, BOUNCE, SHADOW_BALL, SOLAR_BEAM, GRASS_KNOT, BLIZZARD, ICE_BEAM, ICE_PUNCH, ICY_WIND, GIGA_IMPACT, HYPER_BEAM, LAST_RESORT, HYPER_VOICE, UPROAR, STRENGTH, FACADE, COVET, HIDDEN_POWER, ROUND, SNORE, ECHOED_VOICE, ENDEAVOR, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, HEAL_BELL, HELPING_HAND, LASER_FOCUS, PAIN_SPLIT, PROTECT, PSYCH_UP, RECYCLE, SAFEGUARD, SLEEP_TALK, SUBSTITUTE, SWAGGER, WORK_UP, TOXIC, DREAM_EATER, PSYCHIC, ALLY_SWITCH, GRAVITY, LIGHT_SCREEN, MAGIC_COAT, MAGIC_ROOM, REFLECT, REST, ROLE_PLAY, TELEKINESIS, STEALTH_ROCK, GYRO_BALL, WATER_PULSE, RAIN_DANCE, ENDURE, MEGA_KICK, BODY_SLAM, SELF_DESTRUCT, STEEL_ROLLER, MEGA_PUNCH, SCREECH, BATON_PASS, DIG, RETALIATE, FAKE_TEARS, EXPANDING_FORCE, PLAY_ROUGH, CHARM, DRAINING_KISS, MISTY_EXPLOSION, MISTY_TERRAIN, TRI_ATTACK
	; end