	db WOOBAT ; 527

	db  65,  45,  43,  72,  55,  43
  ;  hp  atk  def  spd sat sdf

	db PSYCHIC, FLYING ; type
	db 190 ; catch rate
	db 65 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 15 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/woobat/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_FLYING, EGG_FIELD ; egg groups

	; tm/hm learnset
	tmhm SIGNAL_BEAM, U_TURN, KNOCK_OFF, THIEF, EMBARGO, TAUNT, TORMENT, SHOCK_WAVE, CHARGE_BEAM, THUNDER_WAVE, HEAT_WAVE, FLY, AERIAL_ACE, ACROBATICS, DEFOG, ROOST, TAILWIND, SHADOW_BALL, ENERGY_BALL, GIGA_DRAIN, UPROAR, FACADE, HIDDEN_POWER, ROUND, SNORE, ENDEAVOR, FRUSTRATION, RETURN, SUPER_FANG, AFTER_YOU, ATTRACT, CONFIDE, DOUBLE_TEAM, HELPING_HAND, PROTECT, PSYCH_UP, SAFEGUARD, SLEEP_TALK, SUBSTITUTE, SWAGGER, TOXIC, DREAM_EATER, PSYCHIC, PSYSHOCK, ZEN_HEADBUTT, ALLY_SWITCH, CALM_MIND, LIGHT_SCREEN, MAGIC_COAT, REFLECT, REST, SKILL_SWAP, TELEKINESIS, TRICK, TRICK_ROOM, STEEL_WING, GYRO_BALL, RAIN_DANCE, ENDURE, SWIFT, ASSURANCE, BATON_PASS, AIR_SLASH, AMNESIA, NASTY_PLOT, DUAL_WINGBEAT, FAKE_TEARS, EXPANDING_FORCE, STORED_POWER, FUTURE_SIGHT, IMPRISON, PSYCHO_CUT, CHARM, VENOM_DRENCH, SPEED_SWAP
	; end