	db XATU ; 178

	db  65,  75,  70,  95,  95,  70
  ;  hp  atk  def  spd sat sdf

	db PSYCHIC, FLYING ; type
	db 75 ; catch rate
	db 165 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/xatu/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_FAST ; growth rate
	dn EGG_FLYING, EGG_FLYING ; egg groups

	; tm/hm learnset
	tmhm SIGNAL_BEAM, U_TURN, FOUL_PLAY, THIEF, THUNDER_WAVE, DAZZLING_GLEAM, HEAT_WAVE, SUNNY_DAY, SKY_ATTACK, FLY, AERIAL_ACE, DEFOG, ROOST, TAILWIND, SHADOW_BALL, SOLAR_BEAM, GIGA_DRAIN, GRASS_KNOT, GIGA_IMPACT, HYPER_BEAM, FACADE, HIDDEN_POWER, ROUND, SNORE, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, LASER_FOCUS, PAIN_SPLIT, PROTECT, PSYCH_UP, SLEEP_TALK, SUBSTITUTE, SWAGGER, TOXIC, DREAM_EATER, PSYCHIC, PSYSHOCK, ZEN_HEADBUTT, ALLY_SWITCH, CALM_MIND, LIGHT_SCREEN, MAGIC_COAT, MAGIC_ROOM, REFLECT, REST, SKILL_SWAP, TELEKINESIS, TRICK, TRICK_ROOM, STEEL_WING, RAIN_DANCE, ENDURE, SWIFT, BATON_PASS, AIR_SLASH, DUAL_WINGBEAT, EXPANDING_FORCE, STORED_POWER, GUARD_SWAP, POWER_SWAP, FUTURE_SIGHT, IMPRISON, COSMIC_POWER
	; end