	db XERNEAS ; 716

	db  126,  131,  95,  99,  131,  98
  ;  hp  atk  def  spd sat sdf

	db FAIRY, FAIRY ; type
	db 70 ; catch rate
	db 306 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_UNKNOWN ; gender ratio
	db 100 ; unknown 1
	db 120 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/xerneas/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_SLOW ; growth rate
	dn EGG_NONE, EGG_NONE ; egg groups

	; tm/hm learnset
	tmhm OUTRAGE, THUNDER, THUNDERBOLT, THUNDER_WAVE, DAZZLING_GLEAM, FOCUS_BLAST, SUNNY_DAY, DEFOG, GRASS_KNOT, HAIL, GIGA_IMPACT, HYPER_BEAM, HYPER_VOICE, FACADE, HIDDEN_POWER, ROUND, CUT, SNORE, ECHOED_VOICE, ENDEAVOR, FRUSTRATION, RETURN, BLOCK, CONFIDE, DOUBLE_TEAM, LASER_FOCUS, NATURE_POWER, PROTECT, PSYCH_UP, ROAR, SLEEP_TALK, SUBSTITUTE, SWAGGER, TOXIC, PSYCHIC, PSYSHOCK, ZEN_HEADBUTT, CALM_MIND, GRAVITY, LIGHT_SCREEN, REFLECT, REST, WONDER_ROOM, ROCK_SLIDE, FLASH_CANNON, SMART_STRIKE, RAIN_DANCE, ENDURE, BODY_SLAM, SWIFT, PLAY_ROUGH, MEGAHORN, CLOSE_COMBAT, DRAINING_KISS, MISTY_EXPLOSION, MISTY_TERRAIN, TERRAIN_PULSE
	; end