	db ZAMAZENTA ; 889

	db  92,  130,  115,  138,  80,  115
  ;  hp  atk  def  spd sat sdf

	db FIGHTING, FIGHTING ; type
	db 10 ; catch rate
	db 335 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_UNKNOWN ; gender ratio
	db 100 ; unknown 1
	db 121 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/zamazenta/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_SLOW ; growth rate
	dn EGG_NONE, EGG_NONE ; egg groups

	; tm/hm learnset
	tmhm SNARL, PAYBACK, WILD_CHARGE, DAZZLING_GLEAM, FOCUS_BLAST, SOLAR_BEAM, GIGA_IMPACT, HYPER_BEAM, HYPER_VOICE, FACADE, ROUND, SNORE, HELPING_HAND, PROTECT, SAFEGUARD, SLEEP_TALK, SUBSTITUTE, WORK_UP, LIGHT_SCREEN, REFLECT, REST, IRON_TAIL, FLASH_CANNON, IRON_HEAD, IRON_DEFENSE, ENDURE, STEEL_BEAM, FOCUS_ENERGY, SWIFT, SCARY_FACE, AGILITY, REVERSAL, FIRE_FANG, COACHING, REVENGE, CRUNCH, TAIL_SLAP, DIG, THUNDER_FANG, ICE_FANG, PSYCHIC_FANGS, RETALIATE, GUARD_SWAP, POWER_SWAP, IMPRISON, PLAY_ROUGH, CLOSE_COMBAT
	; end