	db ZANGOOSE ; 335

	db  73,  115,  60,  90,  60,  60
  ;  hp  atk  def  spd sat sdf

	db NORMAL, NORMAL ; type
	db 90 ; catch rate
	db 160 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F50 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/zangoose/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_ERRATIC ; growth rate
	dn EGG_FIELD, EGG_FIELD ; egg groups

	; tm/hm learnset
	tmhm X_SCISSOR, THROAT_CHOP, KNOCK_OFF, THIEF, PAYBACK, FLING, EMBARGO, TAUNT, THUNDER, THUNDERBOLT, THUNDER_PUNCH, SHOCK_WAVE, FOCUS_PUNCH, FOCUS_BLAST, BRICK_BREAK, POWER_UP_PUNCH, ROCK_SMASH, LOW_KICK, FIRE_BLAST, FLAMETHROWER, FIRE_PUNCH, SUNNY_DAY, AERIAL_ACE, SHADOW_BALL, SHADOW_CLAW, SOLAR_BEAM, GIGA_DRAIN, BLIZZARD, ICE_BEAM, ICE_PUNCH, ICY_WIND, LAST_RESORT, STRENGTH, FACADE, HIDDEN_POWER, ROUND, SNORE, FALSE_SWIPE, ENDEAVOR, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, PROTECT, ROAR, SLEEP_TALK, SUBSTITUTE, SWAGGER, SWORDS_DANCE, WORK_UP, POISON_JAB, TOXIC, REST, ROCK_SLIDE, ROCK_TOMB, IRON_TAIL, WATER_PULSE, RAIN_DANCE, ENDURE, SWIFT, DIG, RETALIATE
	; end