	db ZAPDOS ; 145

	db  90,  90,  85,  100,  125,  90
  ;  hp  atk  def  spd sat sdf

	db ELECTRIC, FLYING ; type
	db 3 ; catch rate
	db 261 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_UNKNOWN ; gender ratio
	db 100 ; unknown 1
	db 80 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/zapdos/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_SLOW ; growth rate
	dn EGG_NONE, EGG_NONE ; egg groups

	; tm/hm learnset
	tmhm SIGNAL_BEAM, U_TURN, THUNDER, THUNDERBOLT, WILD_CHARGE, VOLT_SWITCH, SHOCK_WAVE, CHARGE_BEAM, THUNDER_WAVE, ROCK_SMASH, HEAT_WAVE, SUNNY_DAY, SKY_ATTACK, FLY, AERIAL_ACE, SKY_DROP, DEFOG, ROOST, TAILWIND, HAIL, GIGA_IMPACT, HYPER_BEAM, FACADE, HIDDEN_POWER, ROUND, SNORE, FRUSTRATION, RETURN, CONFIDE, DOUBLE_TEAM, LASER_FOCUS, PROTECT, ROAR, SLEEP_TALK, SUBSTITUTE, SWAGGER, TOXIC, LIGHT_SCREEN, REFLECT, REST, SANDSTORM, STEEL_WING, RAIN_DANCE, ENDURE, SWIFT, AGILITY, BATON_PASS, WEATHER_BALL, DUAL_WINGBEAT, BRAVE_BIRD, HURRICANE, RISING_VOLTAGE, EERIE_IMPULSE
	; end