	db ZERAORA ; 807

	db  88,  112,  75,  143,  102,  80
  ;  hp  atk  def  spd sat sdf

	db ELECTRIC, ELECTRIC ; type
	db 3 ; catch rate
	db 270 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_UNKNOWN ; gender ratio
	db 100 ; unknown 1
	db 120 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/zeraora/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_SLOW ; growth rate
	dn EGG_NONE, EGG_NONE ; egg groups

	; tm/hm learnset
	tmhm THROAT_CHOP, KNOCK_OFF, BRUTAL_SWING, SNARL, FLING, SNATCH, TAUNT, OUTRAGE, DUAL_CHOP, THUNDER, THUNDERBOLT, WILD_CHARGE, THUNDER_PUNCH, VOLT_SWITCH, SHOCK_WAVE, ELECTROWEB, THUNDER_WAVE, FOCUS_PUNCH, FOCUS_BLAST, SUPERPOWER, BRICK_BREAK, DRAIN_PUNCH, LOW_SWEEP, LOW_KICK, BULK_UP, FIRE_PUNCH, BOUNCE, AERIAL_ACE, ACROBATICS, GRASS_KNOT, GIGA_IMPACT, HYPER_BEAM, FACADE, HIDDEN_POWER, ROUND, SNORE, ECHOED_VOICE, FALSE_SWIPE, ENDEAVOR, FRUSTRATION, RETURN, CONFIDE, DOUBLE_TEAM, HELPING_HAND, LASER_FOCUS, PROTECT, SLEEP_TALK, SUBSTITUTE, WORK_UP, TOXIC, CALM_MIND, REST, IRON_TAIL, ENDURE, MEGA_KICK, ELECTRIC_TERRAIN, MEGA_PUNCH, SWIFT, ASSURANCE, SCARY_FACE, AGILITY, REVERSAL, BLAZE_KICK, ELECTRO_BALL, COACHING, REVENGE, PLAY_ROUGH, RISING_VOLTAGE, CLOSE_COMBAT, PAY_DAY, AURA_SPHERE
	; end