	db ZOROARK ; 571

	db  60,  105,  60,  105,  120,  60
  ;  hp  atk  def  spd sat sdf

	db DARK, DARK ; type
	db 45 ; catch rate
	db 179 ; base exp
	db NO_ITEM, NO_ITEM
	db GENDER_F12_5 ; gender ratio
	db 100 ; unknown 1
	db 20 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/zoroark/front.dimensions
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_SLOW ; growth rate
	dn EGG_FIELD, EGG_FIELD ; egg groups

	; tm/hm learnset
	tmhm U_TURN, FOUL_PLAY, DARK_PULSE, THROAT_CHOP, KNOCK_OFF, THIEF, SNARL, PAYBACK, FLING, EMBARGO, SNATCH, TAUNT, TORMENT, FOCUS_BLAST, LOW_SWEEP, ROCK_SMASH, LOW_KICK, FLAMETHROWER, SUNNY_DAY, BOUNCE, AERIAL_ACE, SHADOW_BALL, SHADOW_CLAW, SPITE, GRASS_KNOT, GIGA_IMPACT, HYPER_BEAM, HYPER_VOICE, UPROAR, FACADE, COVET, HIDDEN_POWER, ROUND, CUT, SNORE, FRUSTRATION, RETURN, ATTRACT, CONFIDE, DOUBLE_TEAM, LASER_FOCUS, PROTECT, PSYCH_UP, ROAR, SLEEP_TALK, SUBSTITUTE, SWAGGER, SWORDS_DANCE, SLUDGE_BOMB, TOXIC, CALM_MIND, REST, TRICK, RAIN_DANCE, ENDURE, MEGA_KICK, MEGA_PUNCH, SWIFT, SCARY_FACE, AGILITY, REVENGE, DIG, NASTY_PLOT, RETALIATE, FAKE_TEARS, IMPRISON, LASH_OUT, BURNING_JEALOUSY, SKITTER_SMACK, ENCORE, HEX
	; end