	db EVOLVE_ITEM, SHINY_STONE, FLORGES_YELLOW
	db 0 ; no more evolutions
	db 1, TACKLE
	db 1, VINE_WHIP
	db 1, FAIRY_WIND
	db 6, FAIRY_WIND
	db 10, LUCKY_CHANT
	db 15, RAZOR_LEAF
	db 20, WISH
	db 25, MAGICAL_LEAF
	db 27, GRASSY_TERRAIN
	db 33, PETAL_BLIZZARD
	db 38, AROMATHERAPY
	db 43, MISTY_TERRAIN
	db 46, MOONBLAST
	db 51, PETAL_DANCE
	db 58, SOLARBEAM
	db 0 ; no more level-up moves