	db 0 ; no more evolutions
	db 0, SWORDS_DANCE
	db 1, SWORDS_DANCE
	db 1, FOCUS_ENERGY
	db 1, VENOM_DRENCH
	db 1, FELL_STINGER
	db 1, BUG_BITE
	db 1, POISON_STING
	db 1, STRING_SHOT
	db 1, CONSTRICT
	db 1, ABSORB
	db 5, ABSORB
	db 8, INFESTATION
	db 12, SCARY_FACE
	db 15, NIGHT_SHADE
	db 19, SHADOW_SNEAK
	db 23, FURY_SWIPES
	db 28, SUCKER_PUNCH
	db 32, SPIDER_WEB
	db 37, AGILITY
	db 41, PIN_MISSILE
	db 46, PSYCHIC
	db 50, POISON_JAB
	db 55, CROSS_POISON
	db 58, STICKY_WEB
	db 63, TOXIC_THREAD
	db 0 ; no more level-up moves