KirliaEvosAttacks:
	db EVOLVE_LEVEL, 30, GARDEVOIR
	db EVOLVE_ITEM_MALE, DAWN_STONE, GALLADE
	db 0 ; no more evolutions
	db 1, CONFUSE_RAY
	db 1, CHARM
	db 1, TELEPORT
	db 1, DRAININGKISS
	db 1, SING
	db 1, DREAM_EATER
	db 23, FUTURE_SIGHT
	db 27, SIGNAL_BEAM
	db 31, HYPNOSIS
	db 35, ZEN_HEADBUTT
	db 39, ENCORE
	db 43, DESTINY_BOND
	db 47, CALM_MIND
	db 51, PSYCHIC_M
	db 55, PAIN_SPLIT
	db 0 ; no more level-up moves
