	db 0 ; no more evolutions
	db 0, AURA_SPHERE
	db 1, AURA_SPHERE
	db 1, LIFE_DEW
	db 1, WORK_UP
	db 1, ROCK_SMASH
	db 1, NASTY_PLOT
	db 1, SCREECH
	db 1, FORCE_PALM
	db 1, HELPING_HAND
	db 1, COPYCAT
	db 1, FINAL_GAMBIT
	db 1, REVERSAL
	db 1, QUICK_ATTACK
	db 1, DETECT
	db 1, FEINT
	db 1, METAL_CLAW
	db 12, COUNTER
	db 16, LASER_FOCUS
	db 20, POWER_UP_PUNCH
	db 24, CALM_MIND
	db 28, METAL_SOUND
	db 32, QUICK_GUARD
	db 36, BONE_RUSH
	db 40, SWORDS_DANCE
	db 44, HEAL_PULSE
	db 48, METEOR_MASH
	db 52, DRAGON_PULSE
	db 56, EXTREMESPEED
	db 60, CLOSE_COMBAT
	db 0 ; no more level-up moves