AnimationPointers::
	dw BulbasaurAnimation
	dw IvysaurAnimation
	dw VenusaurAnimation
	dw CharmanderAnimation
	dw CharmeleonAnimation
	dw CharizardAnimation
	dw SquirtleAnimation
	dw WartortleAnimation
	dw BlastoiseAnimation
	dw CaterpieAnimation
	dw MetapodAnimation
	dw ButterfreeAnimation
	dw ChinglingAnimation
	dw ChimechoAnimation
	dw TorkoalAnimation
	dw PidgeyAnimation
	dw PidgeottoAnimation
	dw PidgeotAnimation
	dw TaillowAnimation
	dw SwellowAnimation
	dw SpearowAnimation
	dw FearowAnimation
	dw BunearyAnimation
	dw LopunnyAnimation
	dw PikachuAnimation
	dw RaichuAnimation
	dw ShinxAnimation
	dw LuxioAnimation
	dw LuxrayAnimation
	dw ElectrikeAnimation
	dw ManectricAnimation
	dw SnoruntAnimation
	dw GlalieAnimation
	dw FroslassAnimation
	dw VolbeatAnimation
	dw IllumiseAnimation
	dw VulpixAnimation
	dw NinetalesAnimation
	dw JigglypuffAnimation
	dw WigglytuffAnimation
	dw ZubatAnimation
	dw GolbatAnimation
	dw AronAnimation
	dw LaironAnimation
	dw AggronAnimation
	dw ParasAnimation
	dw ParasectAnimation
	dw VenonatAnimation
	dw VenomothAnimation
	dw BronzorAnimation
	dw BronzongAnimation
	dw SkorupiAnimation
	dw DrapionAnimation
	dw CranidosAnimation
	dw RampardosAnimation
	dw ShieldonAnimation
	dw BastiodonAnimation
	dw GrowlitheAnimation
	dw ArcanineAnimation
	dw WhismurAnimation
	dw LoudredAnimation
	dw ExploudAnimation
	dw AbraAnimation
	dw KadabraAnimation
	dw AlakazamAnimation
	dw MachopAnimation
	dw MachokeAnimation
	dw MachampAnimation
	dw BellsproutAnimation
	dw WeepinbellAnimation
	dw VictreebelAnimation
	dw TentacoolAnimation
	dw TentacruelAnimation
	dw GeodudeAnimation
	dw GravelerAnimation
	dw GolemAnimation
	dw PonytaAnimation
	dw RapidashAnimation
	dw SlowpokeAnimation
	dw SlowbroAnimation
	dw MagnemiteAnimation
	dw MagnetonAnimation
	dw MagnezoneAnimation
	dw DrifloonAnimation
	dw DrifblimAnimation
	dw SableyeAnimation
	dw SpiritombAnimation
	dw ShuppetAnimation
	dw BanetteAnimation
	dw DuskullAnimation
	dw DusclopsAnimation
	dw GastlyAnimation
	dw HaunterAnimation
	dw GengarAnimation
	dw OnixAnimation
	dw LunatoneAnimation
	dw SolrockAnimation
	dw VibravaAnimation
	dw FlygonAnimation
	dw MakuhitaAnimation
	dw HariyamaAnimation
	dw ExeggcuteAnimation
	dw ExeggutorAnimation
	dw CacneaAnimation
	dw CacturneAnimation
	dw HitmonleeAnimation
	dw HitmonchanAnimation
	dw TrapinchAnimation
	dw KoffingAnimation
	dw WeezingAnimation
	dw RhyhornAnimation
	dw RhydonAnimation
	dw ChanseyAnimation
	dw TangelaAnimation
	dw KangaskhanAnimation
	dw TangrowthAnimation
	dw MawileAnimation
	dw GoldeenAnimation
	dw SeakingAnimation
	dw LotadAnimation
	dw LombreAnimation
	dw LudicoloAnimation
	dw ScytherAnimation
	dw RelicanthAnimation
	dw ElectabuzzAnimation
	dw MagmarAnimation
	dw ElectivireAnimation
	dw MagmortarAnimation
	dw MagikarpAnimation
	dw GyaradosAnimation
	dw AbsolAnimation
	dw DittoAnimation
	dw EeveeAnimation
	dw VaporeonAnimation
	dw JolteonAnimation
	dw FlareonAnimation
	dw PorygonAnimation
	dw VaraneousAnimation
	dw LileepAnimation
	dw CradilyAnimation
	dw AnorithAnimation
	dw ArmaldoAnimation
	dw SnorlaxAnimation
	dw ArticunoAnimation
	dw ZapdosAnimation
	dw MoltresAnimation
	dw BeldumAnimation
	dw MetangAnimation
	dw MetagrossAnimation
	dw MewtwoAnimation
	dw MewAnimation
	dw ChikoritaAnimation
	dw BayleefAnimation
	dw MeganiumAnimation
	dw CyndaquilAnimation
	dw QuilavaAnimation
	dw TyphlosionAnimation
	dw TotodileAnimation
	dw CroconawAnimation
	dw FeraligatrAnimation
	dw SentretAnimation
	dw FurretAnimation
	dw RaltsAnimation
	dw KirliaAnimation
	dw GardevoirAnimation
	dw GalladeAnimation
	dw SpinarakAnimation
	dw AriadosAnimation
	dw CrobatAnimation
	dw ChinchouAnimation
	dw LanturnAnimation
	dw PichuAnimation
	dw CarnivineAnimation
	dw IgglybuffAnimation
	dw TogepiAnimation
	dw TogeticAnimation
	dw NatuAnimation
	dw XatuAnimation
	dw MareepAnimation
	dw FlaaffyAnimation
	dw AmpharosAnimation
	dw TogekissAnimation
	dw MarillAnimation
	dw AzumarillAnimation
	dw NumelAnimation
	dw CameruptAnimation
	dw WailmerAnimation
	dw WailordAnimation
	dw SurskitAnimation
	dw MasquerainAnimation
	dw ShroomishAnimation
	dw BreloomAnimation
	dw YanmaAnimation
	dw YanmegaAnimation
	dw LeafeonAnimation
	dw EspeonAnimation
	dw UmbreonAnimation
	dw GlaceonAnimation
	dw SlowkingAnimation
	dw MisdreavusAnimation
	dw MismagiusAnimation
	dw SwabluAnimation
	dw AltariaAnimation
	dw PinecoAnimation
	dw ForretressAnimation
	dw RhyperiorAnimation
	dw GligarAnimation
	dw SteelixAnimation
	dw GliscorAnimation
	dw FeebasAnimation
	dw MiloticAnimation
	dw ScizorAnimation
	dw RioluAnimation
	dw LucarioAnimation
	dw SneaselAnimation
	dw TeddiursaAnimation
	dw UrsaringAnimation
	dw SlugmaAnimation
	dw MagcargoAnimation
	dw SwinubAnimation
	dw PiloswineAnimation
	dw GibleAnimation
	dw GabiteAnimation
	dw GarchompAnimation
	dw BagonAnimation
	dw ShelgonAnimation
	dw SalamenceAnimation
	dw HoundourAnimation
	dw HoundoomAnimation
	dw MamoswineAnimation
	dw PhanpyAnimation
	dw DonphanAnimation
	dw Porygon2Animation
	dw PorygonzAnimation
	dw WeavileAnimation
	dw TyrogueAnimation
	dw HitmontopAnimation
	dw FambacoAnimation
	dw ElekidAnimation
	dw MagbyAnimation
	dw SylveonAnimation
	dw BlisseyAnimation
	dw GroudonAnimation
	dw KyogreAnimation
	dw RayquazaAnimation
	dw LarvitarAnimation
	dw PupitarAnimation
	dw TyranitarAnimation
	dw LugiaAnimation
	dw HoohAnimation
	dw RaiwatoAnimation
	dw PhanceroAnimation 
	dw EggAnimation
	dw LibabeelAnimation
	dw BulbasaurAnimation
	dw BulbasaurAnimation
	