BitmasksPointers::
	dw BulbasaurBitmasks
	dw IvysaurBitmasks
	dw VenusaurBitmasks
	dw CharmanderBitmasks
	dw CharmeleonBitmasks
	dw CharizardBitmasks
	dw SquirtleBitmasks
	dw WartortleBitmasks
	dw BlastoiseBitmasks
	dw CaterpieBitmasks
	dw MetapodBitmasks
	dw ButterfreeBitmasks
	dw ChinglingBitmasks
	dw ChimechoBitmasks
	dw TorkoalBitmasks
	dw PidgeyBitmasks
	dw PidgeottoBitmasks
	dw PidgeotBitmasks
	dw TaillowBitmasks
	dw SwellowBitmasks
	dw SpearowBitmasks
	dw FearowBitmasks
	dw BunearyBitmasks
	dw LopunnyBitmasks
	dw PikachuBitmasks
	dw RaichuBitmasks
	dw ShinxBitmasks
	dw LuxioBitmasks
	dw LuxrayBitmasks
	dw ElectrikeBitmasks
	dw ManectricBitmasks
	dw SnoruntBitmasks
	dw GlalieBitmasks
	dw FroslassBitmasks
	dw VolbeatBitmasks
	dw IllumiseBitmasks
	dw VulpixBitmasks
	dw NinetalesBitmasks
	dw JigglypuffBitmasks
	dw WigglytuffBitmasks
	dw ZubatBitmasks
	dw GolbatBitmasks
	dw AronBitmasks
	dw LaironBitmasks
	dw AggronBitmasks
	dw ParasBitmasks
	dw ParasectBitmasks
	dw VenonatBitmasks
	dw VenomothBitmasks
	dw BronzorBitmasks
	dw BronzongBitmasks
	dw SkorupiBitmasks
	dw DrapionBitmasks
	dw CranidosBitmasks
	dw RampardosBitmasks
	dw ShieldonBitmasks
	dw BastiodonBitmasks
	dw GrowlitheBitmasks
	dw ArcanineBitmasks
	dw WhismurBitmasks
	dw LoudredBitmasks
	dw ExploudBitmasks
	dw AbraBitmasks
	dw KadabraBitmasks
	dw AlakazamBitmasks
	dw MachopBitmasks
	dw MachokeBitmasks
	dw MachampBitmasks
	dw BellsproutBitmasks
	dw WeepinbellBitmasks
	dw VictreebelBitmasks
	dw TentacoolBitmasks
	dw TentacruelBitmasks
	dw GeodudeBitmasks
	dw GravelerBitmasks
	dw GolemBitmasks
	dw PonytaBitmasks
	dw RapidashBitmasks
	dw SlowpokeBitmasks
	dw SlowbroBitmasks
	dw MagnemiteBitmasks
	dw MagnetonBitmasks
	dw MagnezoneBitmasks
	dw DrifloonBitmasks
	dw DrifblimBitmasks
	dw SableyeBitmasks
	dw SpiritombBitmasks
	dw ShuppetBitmasks
	dw BanetteBitmasks
	dw DuskullBitmasks
	dw DusclopsBitmasks
	dw GastlyBitmasks
	dw HaunterBitmasks
	dw GengarBitmasks
	dw OnixBitmasks
	dw LunatoneBitmasks
	dw SolrockBitmasks
	dw VibravaBitmasks
	dw FlygonBitmasks
	dw MakuhitaBitmasks
	dw HariyamaBitmasks
	dw ExeggcuteBitmasks
	dw ExeggutorBitmasks
	dw CacneaBitmasks
	dw CacturneBitmasks
	dw HitmonleeBitmasks
	dw HitmonchanBitmasks
	dw TrapinchBitmasks
	dw KoffingBitmasks
	dw WeezingBitmasks
	dw RhyhornBitmasks
	dw RhydonBitmasks
	dw ChanseyBitmasks
	dw TangelaBitmasks
	dw KangaskhanBitmasks
	dw TangrowthBitmasks
	dw MawileBitmasks
	dw GoldeenBitmasks
	dw SeakingBitmasks
	dw LotadBitmasks
	dw LombreBitmasks
	dw LudicoloBitmasks
	dw ScytherBitmasks
	dw RelicanthBitmasks
	dw ElectabuzzBitmasks
	dw MagmarBitmasks
	dw ElectivireBitmasks
	dw MagmortarBitmasks
	dw MagikarpBitmasks
	dw GyaradosBitmasks
	dw AbsolBitmasks
	dw DittoBitmasks
	dw EeveeBitmasks
	dw VaporeonBitmasks
	dw JolteonBitmasks
	dw FlareonBitmasks
	dw PorygonBitmasks
	dw VaraneousBitmasks
	dw LileepBitmasks
	dw CradilyBitmasks
	dw AnorithBitmasks
	dw ArmaldoBitmasks
	dw SnorlaxBitmasks
	dw ArticunoBitmasks
	dw ZapdosBitmasks
	dw MoltresBitmasks
	dw BeldumBitmasks
	dw MetangBitmasks
	dw MetagrossBitmasks
	dw MewtwoBitmasks
	dw MewBitmasks
	dw ChikoritaBitmasks
	dw BayleefBitmasks
	dw MeganiumBitmasks
	dw CyndaquilBitmasks
	dw QuilavaBitmasks
	dw TyphlosionBitmasks
	dw TotodileBitmasks
	dw CroconawBitmasks
	dw FeraligatrBitmasks
	dw SentretBitmasks
	dw FurretBitmasks
	dw RaltsBitmasks
	dw KirliaBitmasks
	dw GardevoirBitmasks
	dw GalladeBitmasks
	dw SpinarakBitmasks
	dw AriadosBitmasks
	dw CrobatBitmasks
	dw ChinchouBitmasks
	dw LanturnBitmasks
	dw PichuBitmasks
	dw CarnivineBitmasks
	dw IgglybuffBitmasks
	dw TogepiBitmasks
	dw TogeticBitmasks
	dw NatuBitmasks
	dw XatuBitmasks
	dw MareepBitmasks
	dw FlaaffyBitmasks
	dw AmpharosBitmasks
	dw TogekissBitmasks
	dw MarillBitmasks
	dw AzumarillBitmasks
	dw NumelBitmasks
	dw CameruptBitmasks
	dw WailmerBitmasks
	dw WailordBitmasks
	dw SurskitBitmasks
	dw MasquerainBitmasks
	dw ShroomishBitmasks
	dw BreloomBitmasks
	dw YanmaBitmasks
	dw YanmegaBitmasks
	dw LeafeonBitmasks
	dw EspeonBitmasks
	dw UmbreonBitmasks
	dw GlaceonBitmasks
	dw SlowkingBitmasks
	dw MisdreavusBitmasks
	dw MismagiusBitmasks
	dw SwabluBitmasks
	dw AltariaBitmasks
	dw PinecoBitmasks
	dw ForretressBitmasks
	dw RhyperiorBitmasks
	dw GligarBitmasks
	dw SteelixBitmasks
	dw GliscorBitmasks
	dw FeebasBitmasks
	dw MiloticBitmasks
	dw ScizorBitmasks
	dw RioluBitmasks
	dw LucarioBitmasks
	dw SneaselBitmasks
	dw TeddiursaBitmasks
	dw UrsaringBitmasks
	dw SlugmaBitmasks
	dw MagcargoBitmasks
	dw SwinubBitmasks
	dw PiloswineBitmasks
	dw GibleBitmasks
	dw GabiteBitmasks
	dw GarchompBitmasks
	dw BagonBitmasks
	dw ShelgonBitmasks
	dw SalamenceBitmasks
	dw HoundourBitmasks
	dw HoundoomBitmasks
	dw MamoswineBitmasks
	dw PhanpyBitmasks
	dw DonphanBitmasks
	dw Porygon2Bitmasks
	dw PorygonzBitmasks
	dw WeavileBitmasks
	dw TyrogueBitmasks
	dw HitmontopBitmasks
	dw FambacoBitmasks
	dw ElekidBitmasks
	dw MagbyBitmasks
	dw SylveonBitmasks
	dw BlisseyBitmasks
	dw GroudonBitmasks
	dw KyogreBitmasks
	dw RayquazaBitmasks
	dw LarvitarBitmasks
	dw PupitarBitmasks
	dw TyranitarBitmasks
	dw LugiaBitmasks
	dw HoohBitmasks
	dw RaiwatoBitmasks
	dw PhanceroBitmasks
	dw EggBitmasks
	dw LibabeelBitmasks
