AnimationExtraPointers::
	dw BulbasaurAnimationExtra
	dw IvysaurAnimationExtra
	dw VenusaurAnimationExtra
	dw CharmanderAnimationExtra
	dw CharmeleonAnimationExtra
	dw CharizardAnimationExtra
	dw SquirtleAnimationExtra
	dw WartortleAnimationExtra
	dw BlastoiseAnimationExtra
	dw CaterpieAnimationExtra
	dw MetapodAnimationExtra
	dw ButterfreeAnimationExtra
	dw ChinglingAnimationExtra
	dw ChimechoAnimationExtra
	dw TorkoalAnimationExtra
	dw PidgeyAnimationExtra
	dw PidgeottoAnimationExtra
	dw PidgeotAnimationExtra
	dw TaillowAnimationExtra
	dw SwellowAnimationExtra
	dw SpearowAnimationExtra
	dw FearowAnimationExtra
	dw BunearyAnimationExtra
	dw LopunnyAnimationExtra
	dw PikachuAnimationExtra
	dw RaichuAnimationExtra
	dw ShinxAnimationExtra
	dw LuxioAnimationExtra
	dw LuxrayAnimationExtra
	dw ElectrikeAnimationExtra
	dw ManectricAnimationExtra
	dw SnoruntAnimationExtra
	dw GlalieAnimationExtra
	dw FroslassAnimationExtra
	dw VolbeatAnimationExtra
	dw IllumiseAnimationExtra
	dw VulpixAnimationExtra
	dw NinetalesAnimationExtra
	dw JigglypuffAnimationExtra
	dw WigglytuffAnimationExtra
	dw ZubatAnimationExtra
	dw GolbatAnimationExtra
	dw AronAnimationExtra
	dw LaironAnimationExtra
	dw AggronAnimationExtra
	dw ParasAnimationExtra
	dw ParasectAnimationExtra
	dw VenonatAnimationExtra
	dw VenomothAnimationExtra
	dw BronzorAnimationExtra
	dw BronzongAnimationExtra
	dw SkorupiAnimationExtra
	dw DrapionAnimationExtra
	dw CranidosAnimationExtra
	dw RampardosAnimationExtra
	dw ShieldonAnimationExtra
	dw BastiodonAnimationExtra
	dw GrowlitheAnimationExtra
	dw ArcanineAnimationExtra
	dw WhismurAnimationExtra
	dw LoudredAnimationExtra
	dw ExploudAnimationExtra
	dw AbraAnimationExtra
	dw KadabraAnimationExtra
	dw AlakazamAnimationExtra
	dw MachopAnimationExtra
	dw MachokeAnimationExtra
	dw MachampAnimationExtra
	dw BellsproutAnimationExtra
	dw WeepinbellAnimationExtra
	dw VictreebelAnimationExtra
	dw TentacoolAnimationExtra
	dw TentacruelAnimationExtra
	dw GeodudeAnimationExtra
	dw GravelerAnimationExtra
	dw GolemAnimationExtra
	dw PonytaAnimationExtra
	dw RapidashAnimationExtra
	dw SlowpokeAnimationExtra
	dw SlowbroAnimationExtra
	dw MagnemiteAnimationExtra
	dw MagnetonAnimationExtra
	dw MagnezoneAnimationExtra
	dw DrifloonAnimationExtra
	dw DrifblimAnimationExtra
	dw SableyeAnimationExtra
	dw SpiritombAnimationExtra
	dw ShuppetAnimationExtra
	dw BanetteAnimationExtra
	dw DuskullAnimationExtra
	dw DusclopsAnimationExtra
	dw GastlyAnimationExtra
	dw HaunterAnimationExtra
	dw GengarAnimationExtra
	dw OnixAnimationExtra
	dw LunatoneAnimationExtra
	dw SolrockAnimationExtra
	dw VibravaAnimationExtra
	dw FlygonAnimationExtra
	dw MakuhitaAnimationExtra
	dw HariyamaAnimationExtra
	dw ExeggcuteAnimationExtra
	dw ExeggutorAnimationExtra
	dw CacneaAnimationExtra
	dw CacturneAnimationExtra
	dw HitmonleeAnimationExtra
	dw HitmonchanAnimationExtra
	dw TrapinchAnimationExtra
	dw KoffingAnimationExtra
	dw WeezingAnimationExtra
	dw RhyhornAnimationExtra
	dw RhydonAnimationExtra
	dw ChanseyAnimationExtra
	dw TangelaAnimationExtra
	dw KangaskhanAnimationExtra
	dw TangrowthAnimationExtra
	dw MawileAnimationExtra
	dw GoldeenAnimationExtra
	dw SeakingAnimationExtra
	dw LotadAnimationExtra
	dw LombreAnimationExtra
	dw LudicoloAnimationExtra
	dw ScytherAnimationExtra
	dw RelicanthAnimationExtra
	dw ElectabuzzAnimationExtra
	dw MagmarAnimationExtra
	dw ElectivireAnimationExtra
	dw MagmortarAnimationExtra
	dw MagikarpAnimationExtra
	dw GyaradosAnimationExtra
	dw AbsolAnimationExtra
	dw DittoAnimationExtra
	dw EeveeAnimationExtra
	dw VaporeonAnimationExtra
	dw JolteonAnimationExtra
	dw FlareonAnimationExtra
	dw PorygonAnimationExtra
	dw VaraneousAnimationExtra
	dw LileepAnimationExtra
	dw CradilyAnimationExtra
	dw AnorithAnimationExtra
	dw ArmaldoAnimationExtra
	dw SnorlaxAnimationExtra
	dw ArticunoAnimationExtra
	dw ZapdosAnimationExtra
	dw MoltresAnimationExtra
	dw BeldumAnimationExtra
	dw MetangAnimationExtra
	dw MetagrossAnimationExtra
	dw MewtwoAnimationExtra
	dw MewAnimationExtra
	dw ChikoritaAnimationExtra
	dw BayleefAnimationExtra
	dw MeganiumAnimationExtra
	dw CyndaquilAnimationExtra
	dw QuilavaAnimationExtra
	dw TyphlosionAnimationExtra
	dw TotodileAnimationExtra
	dw CroconawAnimationExtra
	dw FeraligatrAnimationExtra
	dw SentretAnimationExtra
	dw FurretAnimationExtra
	dw RaltsAnimationExtra
	dw KirliaAnimationExtra
	dw GardevoirAnimationExtra
	dw GalladeAnimationExtra
	dw SpinarakAnimationExtra
	dw AriadosAnimationExtra
	dw CrobatAnimationExtra
	dw ChinchouAnimationExtra
	dw LanturnAnimationExtra
	dw PichuAnimationExtra
	dw CarnivineAnimationExtra
	dw IgglybuffAnimationExtra
	dw TogepiAnimationExtra
	dw TogeticAnimationExtra
	dw NatuAnimationExtra
	dw XatuAnimationExtra
	dw MareepAnimationExtra
	dw FlaaffyAnimationExtra
	dw AmpharosAnimationExtra
	dw TogekissAnimationExtra
	dw MarillAnimationExtra
	dw AzumarillAnimationExtra
	dw NumelAnimationExtra
	dw CameruptAnimationExtra
	dw WailmerAnimationExtra
	dw WailordAnimationExtra
	dw SurskitAnimationExtra
	dw MasquerainAnimationExtra
	dw ShroomishAnimationExtra
	dw BreloomAnimationExtra
	dw YanmaAnimationExtra
	dw YanmegaAnimationExtra
	dw LeafeonAnimationExtra
	dw EspeonAnimationExtra
	dw UmbreonAnimationExtra
	dw GlaceonAnimationExtra
	dw SlowkingAnimationExtra
	dw MisdreavusAnimationExtra
	dw MismagiusAnimationExtra
	dw SwabluAnimationExtra
	dw AltariaAnimationExtra
	dw PinecoAnimationExtra
	dw ForretressAnimationExtra
	dw RhyperiorAnimationExtra
	dw GligarAnimationExtra
	dw SteelixAnimationExtra
	dw GliscorAnimationExtra
	dw FeebasAnimationExtra
	dw MiloticAnimationExtra
	dw ScizorAnimationExtra
	dw RioluAnimationExtra
	dw LucarioAnimationExtra
	dw SneaselAnimationExtra
	dw TeddiursaAnimationExtra
	dw UrsaringAnimationExtra
	dw SlugmaAnimationExtra
	dw MagcargoAnimationExtra
	dw SwinubAnimationExtra
	dw PiloswineAnimationExtra
	dw GibleAnimationExtra
	dw GabiteAnimationExtra
	dw GarchompAnimationExtra
	dw BagonAnimationExtra
	dw ShelgonAnimationExtra
	dw SalamenceAnimationExtra
	dw HoundourAnimationExtra
	dw HoundoomAnimationExtra
	dw MamoswineAnimationExtra
	dw PhanpyAnimationExtra
	dw DonphanAnimationExtra
	dw Porygon2AnimationExtra
	dw PorygonzAnimationExtra
	dw WeavileAnimationExtra
	dw TyrogueAnimationExtra
	dw HitmontopAnimationExtra
	dw FambacoAnimationExtra
	dw ElekidAnimationExtra
	dw MagbyAnimationExtra
	dw SylveonAnimationExtra
	dw BlisseyAnimationExtra
	dw GroudonAnimationExtra
	dw KyogreAnimationExtra
	dw RayquazaAnimationExtra
	dw LarvitarAnimationExtra
	dw PupitarAnimationExtra
	dw TyranitarAnimationExtra
	dw LugiaAnimationExtra
	dw HoohAnimationExtra
	dw RaiwatoAnimationExtra
	dw PhanceroAnimationExtra
	dw EggAnimationExtra
	dw LibabeelAnimationExtra
	dw BulbasaurAnimationExtra
	dw BulbasaurAnimationExtra