FramesPointers::
	dba BulbasaurFrames
	dba IvysaurFrames
	dba VenusaurFrames
	dba CharmanderFrames
	dba CharmeleonFrames
	dba CharizardFrames
	dba SquirtleFrames
	dba WartortleFrames
	dba BlastoiseFrames
	dba CaterpieFrames
	dba MetapodFrames
	dba ButterfreeFrames
	dba ChinglingFrames
	dba ChimechoFrames
	dba TorkoalFrames
	dba PidgeyFrames
	dba PidgeottoFrames
	dba PidgeotFrames
	dba TaillowFrames
	dba SwellowFrames
	dba SpearowFrames
	dba FearowFrames
	dba BunearyFrames
	dba LopunnyFrames
	dba PikachuFrames
	dba RaichuFrames
	dba ShinxFrames
	dba LuxioFrames
	dba LuxrayFrames
	dba ElectrikeFrames
	dba ManectricFrames
	dba SnoruntFrames
	dba GlalieFrames
	dba FroslassFrames
	dba VolbeatFrames
	dba IllumiseFrames
	dba VulpixFrames
	dba NinetalesFrames
	dba JigglypuffFrames
	dba WigglytuffFrames
	dba ZubatFrames
	dba GolbatFrames
	dba AronFrames
	dba LaironFrames
	dba AggronFrames
	dba ParasFrames
	dba ParasectFrames
	dba VenonatFrames
	dba VenomothFrames
	dba BronzorFrames
	dba BronzongFrames
	dba SkorupiFrames
	dba DrapionFrames
	dba CranidosFrames
	dba RampardosFrames
	dba ShieldonFrames
	dba BastiodonFrames
	dba GrowlitheFrames
	dba ArcanineFrames
	dba WhismurFrames
	dba LoudredFrames
	dba ExploudFrames
	dba AbraFrames
	dba KadabraFrames
	dba AlakazamFrames
	dba MachopFrames
	dba MachokeFrames
	dba MachampFrames
	dba BellsproutFrames
	dba WeepinbellFrames
	dba VictreebelFrames
	dba TentacoolFrames
	dba TentacruelFrames
	dba GeodudeFrames
	dba GravelerFrames
	dba GolemFrames
	dba PonytaFrames
	dba RapidashFrames
	dba SlowpokeFrames
	dba SlowbroFrames
	dba MagnemiteFrames
	dba MagnetonFrames
	dba MagnezoneFrames
	dba DrifloonFrames
	dba DrifblimFrames
	dba SableyeFrames
	dba SpiritombFrames
	dba ShuppetFrames
	dba BanetteFrames
	dba DuskullFrames
	dba DusclopsFrames
	dba GastlyFrames
	dba HaunterFrames
	dba GengarFrames
	dba OnixFrames
	dba LunatoneFrames
	dba SolrockFrames
	dba VibravaFrames
	dba FlygonFrames
	dba MakuhitaFrames
	dba HariyamaFrames
	dba ExeggcuteFrames
	dba ExeggutorFrames
	dba CacneaFrames
	dba CacturneFrames
	dba HitmonleeFrames
	dba HitmonchanFrames
	dba TrapinchFrames
	dba KoffingFrames
	dba WeezingFrames
	dba RhyhornFrames
	dba RhydonFrames
	dba ChanseyFrames
	dba TangelaFrames
	dba KangaskhanFrames
	dba TangrowthFrames
	dba MawileFrames
	dba GoldeenFrames
	dba SeakingFrames
	dba LotadFrames
	dba LombreFrames
	dba LudicoloFrames
	dba ScytherFrames
	dba RelicanthFrames
	dba ElectabuzzFrames
	dba MagmarFrames
	dba ElectivireFrames
	dba MagmortarFrames
	dba MagikarpFrames
	dba GyaradosFrames
	dba AbsolFrames
	dba DittoFrames
	dba EeveeFrames
	dba VaporeonFrames
	dba JolteonFrames
	dba FlareonFrames
	dba PorygonFrames
	dba VaraneousFrames
	dba LileepFrames
	dba CradilyFrames
	dba AnorithFrames
	dba ArmaldoFrames
	dba SnorlaxFrames
	dba ArticunoFrames
	dba ZapdosFrames
	dba MoltresFrames
	dba BeldumFrames
	dba MetangFrames
	dba MetagrossFrames
	dba MewtwoFrames
	dba MewFrames
	dba ChikoritaFrames
	dba BayleefFrames
	dba MeganiumFrames
	dba CyndaquilFrames
	dba QuilavaFrames
	dba TyphlosionFrames
	dba TotodileFrames
	dba CroconawFrames
	dba FeraligatrFrames
	dba SentretFrames
	dba FurretFrames
	dba RaltsFrames
	dba KirliaFrames
	dba GardevoirFrames
	dba GalladeFrames
	dba SpinarakFrames
	dba AriadosFrames
	dba CrobatFrames
	dba ChinchouFrames
	dba LanturnFrames
	dba PichuFrames
	dba CarnivineFrames
	dba IgglybuffFrames
	dba TogepiFrames
	dba TogeticFrames
	dba NatuFrames
	dba XatuFrames
	dba MareepFrames
	dba FlaaffyFrames
	dba AmpharosFrames
	dba TogekissFrames
	dba MarillFrames
	dba AzumarillFrames
	dba NumelFrames
	dba CameruptFrames
	dba WailmerFrames
	dba WailordFrames
	dba SurskitFrames
	dba MasquerainFrames
	dba ShroomishFrames
	dba BreloomFrames
	dba YanmaFrames
	dba YanmegaFrames
	dba LeafeonFrames
	dba EspeonFrames
	dba UmbreonFrames
	dba GlaceonFrames
	dba SlowkingFrames
	dba MisdreavusFrames
	dba MismagiusFrames
	dba SwabluFrames
	dba AltariaFrames
	dba PinecoFrames
	dba ForretressFrames
	dba RhyperiorFrames
	dba GligarFrames
	dba SteelixFrames
	dba GliscorFrames
	dba FeebasFrames
	dba MiloticFrames
	dba ScizorFrames
	dba RioluFrames
	dba LucarioFrames
	dba SneaselFrames
	dba TeddiursaFrames
	dba UrsaringFrames
	dba SlugmaFrames
	dba MagcargoFrames
	dba SwinubFrames
	dba PiloswineFrames
	dba GibleFrames
	dba GabiteFrames
	dba GarchompFrames
	dba BagonFrames
	dba ShelgonFrames
	dba SalamenceFrames
	dba HoundourFrames
	dba HoundoomFrames
	dba MamoswineFrames
	dba PhanpyFrames
	dba DonphanFrames
	dba Porygon2Frames
	dba PorygonzFrames
	dba WeavileFrames
	dba TyrogueFrames
	dba HitmontopFrames
	dba FambacoFrames
	dba ElekidFrames
	dba MagbyFrames
	dba SylveonFrames
	dba BlisseyFrames
	dba GroudonFrames
	dba KyogreFrames
	dba RayquazaFrames
	dba LarvitarFrames
	dba PupitarFrames
	dba TyranitarFrames
	dba LugiaFrames
	dba HoohFrames
	dba RaiwatoFrames
	dba PhanceroFrames
	dba EggFrames
	dba LibabeelFrames
	dba BulbasaurFrames
	dba BulbasaurFrames
