	dba BulbasaurFrontPic
	dba BulbasaurBackPic
	dba IvysaurFrontPic
	dba IvysaurBackPic
	dba VenusaurFrontPic
	dba VenusaurBackPic
	dba CharmanderFrontPic
	dba CharmanderBackPic
	dba CharmeleonFrontPic
	dba CharmeleonBackPic
	dba CharizardFrontPic
	dba CharizardBackPic
	dba SquirtleFrontPic
	dba SquirtleBackPic
	dba WartortleFrontPic
	dba WartortleBackPic
	dba BlastoiseFrontPic
	dba BlastoiseBackPic
	dba CaterpieFrontPic
	dba CaterpieBackPic
	dba MetapodFrontPic
	dba MetapodBackPic
	dba ButterfreeFrontPic
	dba ButterfreeBackPic
	dba ChinglingFrontPic
	dba ChinglingBackPic
	dba ChimechoFrontPic
	dba ChimechoBackPic
	dba TorkoalFrontPic
	dba TorkoalBackPic
	dba PidgeyFrontPic
	dba PidgeyBackPic
	dba PidgeottoFrontPic
	dba PidgeottoBackPic
	dba PidgeotFrontPic
	dba PidgeotBackPic
	dba TaillowFrontPic
	dba TaillowBackPic
	dba SwellowFrontPic
	dba SwellowBackPic
	dba SpearowFrontPic
	dba SpearowBackPic
	dba FearowFrontPic
	dba FearowBackPic
	dba BunearyFrontPic
	dba BunearyBackPic
	dba LopunnyFrontPic
	dba LopunnyBackPic
	dba PikachuFrontPic
	dba PikachuBackPic
	dba RaichuFrontPic
	dba RaichuBackPic
	dba ShinxFrontPic
	dba ShinxBackPic
	dba LuxioFrontPic
	dba LuxioBackPic
	dba LuxrayFrontPic
	dba LuxrayBackPic
	dba ElectrikeFrontPic
	dba ElectrikeBackPic
	dba ManectricFrontPic
	dba ManectricBackPic
	dba SnoruntFrontPic
	dba SnoruntBackPic
	dba GlalieFrontPic
	dba GlalieBackPic
	dba FroslassFrontPic
	dba FroslassBackPic
	dba VolbeatFrontPic
	dba VolbeatBackPic
	dba IllumiseFrontPic
	dba IllumiseBackPic
	dba VulpixFrontPic
	dba VulpixBackPic
	dba NinetalesFrontPic
	dba NinetalesBackPic
	dba JigglypuffFrontPic
	dba JigglypuffBackPic
	dba WigglytuffFrontPic
	dba WigglytuffBackPic
	dba ZubatFrontPic
	dba ZubatBackPic
	dba GolbatFrontPic
	dba GolbatBackPic
	dba AronFrontPic
	dba AronBackPic
	dba LaironFrontPic
	dba LaironBackPic
	dba AggronFrontPic
	dba AggronBackPic
	dba ParasFrontPic
	dba ParasBackPic
	dba ParasectFrontPic
	dba ParasectBackPic
	dba VenonatFrontPic
	dba VenonatBackPic
	dba VenomothFrontPic
	dba VenomothBackPic
	dba BronzorFrontPic
	dba BronzorBackPic
	dba BronzongFrontPic
	dba BronzongBackPic
	dba SkorupiFrontPic
	dba SkorupiBackPic
	dba DrapionFrontPic
	dba DrapionBackPic
	dba CranidosFrontPic
	dba CranidosBackPic
	dba RampardosFrontPic
	dba RampardosBackPic
	dba ShieldonFrontPic
	dba ShieldonBackPic
	dba BastiodonFrontPic
	dba BastiodonBackPic
	dba GrowlitheFrontPic
	dba GrowlitheBackPic
	dba ArcanineFrontPic
	dba ArcanineBackPic
	dba WhismurFrontPic
	dba WhismurBackPic
	dba LoudredFrontPic
	dba LoudredBackPic
	dba ExploudFrontPic
	dba ExploudBackPic
	dba AbraFrontPic
	dba AbraBackPic
	dba KadabraFrontPic
	dba KadabraBackPic
	dba AlakazamFrontPic
	dba AlakazamBackPic
	dba MachopFrontPic
	dba MachopBackPic
	dba MachokeFrontPic
	dba MachokeBackPic
	dba MachampFrontPic
	dba MachampBackPic
	dba BellsproutFrontPic
	dba BellsproutBackPic
	dba WeepinbellFrontPic
	dba WeepinbellBackPic
	dba VictreebelFrontPic
	dba VictreebelBackPic
	dba TentacoolFrontPic
	dba TentacoolBackPic
	dba TentacruelFrontPic
	dba TentacruelBackPic
	dba GeodudeFrontPic
	dba GeodudeBackPic
	dba GravelerFrontPic
	dba GravelerBackPic
	dba GolemFrontPic
	dba GolemBackPic
	dba PonytaFrontPic
	dba PonytaBackPic
	dba RapidashFrontPic
	dba RapidashBackPic
	dba SlowpokeFrontPic
	dba SlowpokeBackPic
	dba SlowbroFrontPic
	dba SlowbroBackPic
	dba MagnemiteFrontPic
	dba MagnemiteBackPic
	dba MagnetonFrontPic
	dba MagnetonBackPic
	dba MagnezoneFrontPic
	dba MagnezoneBackPic
	dba DrifloonFrontPic
	dba DrifloonBackPic
	dba DrifblimFrontPic
	dba DrifblimBackPic
	dba SableyeFrontPic
	dba SableyeBackPic
	dba SpiritombFrontPic
	dba SpiritombBackPic
	dba ShuppetFrontPic
	dba ShuppetBackPic
	dba BanetteFrontPic
	dba BanetteBackPic
	dba DuskullFrontPic
	dba DuskullBackPic
	dba DusclopsFrontPic
	dba DusclopsBackPic
	dba GastlyFrontPic
	dba GastlyBackPic
	dba HaunterFrontPic
	dba HaunterBackPic
	dba GengarFrontPic
	dba GengarBackPic
	dba OnixFrontPic
	dba OnixBackPic
	dba LunatoneFrontPic
	dba LunatoneBackPic
	dba SolrockFrontPic
	dba SolrockBackPic
	dba VibravaFrontPic
	dba VibravaBackPic
	dba FlygonFrontPic
	dba FlygonBackPic
	dba MakuhitaFrontPic
	dba MakuhitaBackPic
	dba HariyamaFrontPic
	dba HariyamaBackPic
	dba ExeggcuteFrontPic
	dba ExeggcuteBackPic
	dba ExeggutorFrontPic
	dba ExeggutorBackPic
	dba CacneaFrontPic
	dba CacneaBackPic
	dba CacturneFrontPic
	dba CacturneBackPic
	dba HitmonleeFrontPic
	dba HitmonleeBackPic
	dba HitmonchanFrontPic
	dba HitmonchanBackPic
	dba TrapinchFrontPic
	dba TrapinchBackPic
	dba KoffingFrontPic
	dba KoffingBackPic
	dba WeezingFrontPic
	dba WeezingBackPic
	dba RhyhornFrontPic
	dba RhyhornBackPic
	dba RhydonFrontPic
	dba RhydonBackPic
	dba ChanseyFrontPic
	dba ChanseyBackPic
	dba TangelaFrontPic
	dba TangelaBackPic
	dba KangaskhanFrontPic
	dba KangaskhanBackPic
	dba TangrowthFrontPic
	dba TangrowthBackPic
	dba MawileFrontPic
	dba MawileBackPic
	dba GoldeenFrontPic
	dba GoldeenBackPic
	dba SeakingFrontPic
	dba SeakingBackPic
	dba LotadFrontPic
	dba LotadBackPic
	dba LombreFrontPic
	dba LombreBackPic
	dba LudicoloFrontPic
	dba LudicoloBackPic
	dba ScytherFrontPic
	dba ScytherBackPic
	dba RelicanthFrontPic
	dba RelicanthBackPic
	dba ElectabuzzFrontPic
	dba ElectabuzzBackPic
	dba MagmarFrontPic
	dba MagmarBackPic
	dba ElectivireFrontPic
	dba ElectivireBackPic
	dba MagmortarFrontPic
	dba MagmortarBackPic
	dba MagikarpFrontPic
	dba MagikarpBackPic
	dba GyaradosFrontPic
	dba GyaradosBackPic
	dba AbsolFrontPic
	dba AbsolBackPic
	dba DittoFrontPic
	dba DittoBackPic
	dba EeveeFrontPic
	dba EeveeBackPic
	dba VaporeonFrontPic
	dba VaporeonBackPic
	dba JolteonFrontPic
	dba JolteonBackPic
	dba FlareonFrontPic
	dba FlareonBackPic
	dba PorygonFrontPic
	dba PorygonBackPic
	dba VaraneousFrontPic
	dba VaraneousBackPic
	dba LileepFrontPic
	dba LileepBackPic
	dba CradilyFrontPic
	dba CradilyBackPic
	dba AnorithFrontPic
	dba AnorithBackPic
	dba ArmaldoFrontPic
	dba ArmaldoBackPic
	dba SnorlaxFrontPic
	dba SnorlaxBackPic
	dba ArticunoFrontPic
	dba ArticunoBackPic
	dba ZapdosFrontPic
	dba ZapdosBackPic
	dba MoltresFrontPic
	dba MoltresBackPic
	dba BeldumFrontPic
	dba BeldumBackPic
	dba MetangFrontPic
	dba MetangBackPic
	dba MetagrossFrontPic
	dba MetagrossBackPic
	dba MewtwoFrontPic
	dba MewtwoBackPic
	dba MewFrontPic
	dba MewBackPic
	dba ChikoritaFrontPic
	dba ChikoritaBackPic
	dba BayleefFrontPic
	dba BayleefBackPic
	dba MeganiumFrontPic
	dba MeganiumBackPic
	dba CyndaquilFrontPic
	dba CyndaquilBackPic
	dba QuilavaFrontPic
	dba QuilavaBackPic
	dba TyphlosionFrontPic
	dba TyphlosionBackPic
	dba TotodileFrontPic
	dba TotodileBackPic
	dba CroconawFrontPic
	dba CroconawBackPic
	dba FeraligatrFrontPic
	dba FeraligatrBackPic
	dba SentretFrontPic
	dba SentretBackPic
	dba FurretFrontPic
	dba FurretBackPic
	dba RaltsFrontPic
	dba RaltsBackPic
	dba KirliaFrontPic
	dba KirliaBackPic
	dba GardevoirFrontPic
	dba GardevoirBackPic
	dba GalladeFrontPic
	dba GalladeBackPic
	dba SpinarakFrontPic
	dba SpinarakBackPic
	dba AriadosFrontPic
	dba AriadosBackPic
	dba CrobatFrontPic
	dba CrobatBackPic
	dba ChinchouFrontPic
	dba ChinchouBackPic
	dba LanturnFrontPic
	dba LanturnBackPic
	dba PichuFrontPic
	dba PichuBackPic
	dba CarnivineFrontPic
	dba CarnivineBackPic
	dba IgglybuffFrontPic
	dba IgglybuffBackPic
	dba TogepiFrontPic
	dba TogepiBackPic
	dba TogeticFrontPic
	dba TogeticBackPic
	dba NatuFrontPic
	dba NatuBackPic
	dba XatuFrontPic
	dba XatuBackPic
	dba MareepFrontPic
	dba MareepBackPic
	dba FlaaffyFrontPic
	dba FlaaffyBackPic
	dba AmpharosFrontPic
	dba AmpharosBackPic
	dba TogekissFrontPic
	dba TogekissBackPic
	dba MarillFrontPic
	dba MarillBackPic
	dba AzumarillFrontPic
	dba AzumarillBackPic
	dba NumelFrontPic
	dba NumelBackPic
	dba CameruptFrontPic
	dba CameruptBackPic
	dba WailmerFrontPic
	dba WailmerBackPic
	dba WailordFrontPic
	dba WailordBackPic
	dba SurskitFrontPic
	dba SurskitBackPic
	dba MasquerainFrontPic
	dba MasquerainBackPic
	dba ShroomishFrontPic
	dba ShroomishBackPic
	dba BreloomFrontPic
	dba BreloomBackPic
	dba YanmaFrontPic
	dba YanmaBackPic
	dba YanmegaFrontPic
	dba YanmegaBackPic
	dba LeafeonFrontPic
	dba LeafeonBackPic
	dba EspeonFrontPic
	dba EspeonBackPic
	dba UmbreonFrontPic
	dba UmbreonBackPic
	dba GlaceonFrontPic
	dba GlaceonBackPic
	dba SlowkingFrontPic
	dba SlowkingBackPic
	dba MisdreavusFrontPic
	dba MisdreavusBackPic
	dba MismagiusFrontPic
	dba MismagiusBackPic
	dba SwabluFrontPic
	dba SwabluBackPic
	dba AltariaFrontPic
	dba AltariaBackPic
	dba PinecoFrontPic
	dba PinecoBackPic
	dba ForretressFrontPic
	dba ForretressBackPic
	dba RhyperiorFrontPic
	dba RhyperiorBackPic
	dba GligarFrontPic
	dba GligarBackPic
	dba SteelixFrontPic
	dba SteelixBackPic
	dba GliscorFrontPic
	dba GliscorBackPic
	dba FeebasFrontPic
	dba FeebasBackPic
	dba MiloticFrontPic
	dba MiloticBackPic
	dba ScizorFrontPic
	dba ScizorBackPic
	dba RioluFrontPic
	dba RioluBackPic
	dba LucarioFrontPic
	dba LucarioBackPic
	dba SneaselFrontPic
	dba SneaselBackPic
	dba TeddiursaFrontPic
	dba TeddiursaBackPic
	dba UrsaringFrontPic
	dba UrsaringBackPic
	dba SlugmaFrontPic
	dba SlugmaBackPic
	dba MagcargoFrontPic
	dba MagcargoBackPic
	dba SwinubFrontPic
	dba SwinubBackPic
	dba PiloswineFrontPic
	dba PiloswineBackPic
	dba GibleFrontPic
	dba GibleBackPic
	dba GabiteFrontPic
	dba GabiteBackPic
	dba GarchompFrontPic
	dba GarchompBackPic
	dba BagonFrontPic
	dba BagonBackPic
	dba ShelgonFrontPic
	dba ShelgonBackPic
	dba SalamenceFrontPic
	dba SalamenceBackPic
	dba HoundourFrontPic
	dba HoundourBackPic
	dba HoundoomFrontPic
	dba HoundoomBackPic
	dba MamoswineFrontPic
	dba MamoswineBackPic
	dba PhanpyFrontPic
	dba PhanpyBackPic
	dba DonphanFrontPic
	dba DonphanBackPic
	dba Porygon2FrontPic
	dba Porygon2BackPic
	dba PorygonzFrontPic
	dba PorygonzBackPic
	dba WeavileFrontPic
	dba WeavileBackPic
	dba TyrogueFrontPic
	dba TyrogueBackPic
	dba HitmontopFrontPic
	dba HitmontopBackPic
	dba FambacoFrontPic
	dba FambacoBackPic
	dba ElekidFrontPic
	dba ElekidBackPic
	dba MagbyFrontPic
	dba MagbyBackPic
	dba SylveonFrontPic
	dba SylveonBackPic
	dba BlisseyFrontPic
	dba BlisseyBackPic
	dba GroudonFrontPic
	dba GroudonBackPic
	dba KyogreFrontPic
	dba KyogreBackPic
	dba RayquazaFrontPic
	dba RayquazaBackPic
	dba LarvitarFrontPic
	dba LarvitarBackPic
	dba PupitarFrontPic
	dba PupitarBackPic
	dba TyranitarFrontPic
	dba TyranitarBackPic
	dba LugiaFrontPic
	dba LugiaBackPic
	dba HoOhFrontPic
	dba HoOhBackPic
	dba RaiwatoFrontPic
	dba RaiwatoBackPic
	dba PhanceroFrontPic
	dba PhanceroBackPic
	dba EggFrontPic
	dba EggBackPic
	dba LibabeelFrontPic
	dba LibabeelBackPic
	dba BulbasaurFrontPic
	dba BulbasaurBackPic
	dba BulbasaurFrontPic
	dba BulbasaurBackPic
